TABLES_MAPS = {
    # 1.基本信息
    'FTR_BASICINFO': {
        'source_table': 'AIWEFTROPT.FTR_BASICINFO',
        'date': None,
        'date_format': None,
        'instrument': 'smb',
        'schema': {
            'desc': '期货基本资料表',
            'active': True,
            'date_field': None,
            'category': '期货(原表)/基本资料',
            'rank': 4001001,
            'friendly_name': '期货基本资料表',
            'partition_date': None,
            'primary_key': ['ftr_cd', 'instrument'],
            'fields': {
                'ftr_cd': {'desc': '期货内部编码', 'type': 'str'},
                'ftr_typ': {'desc': '期货类型', 'type': 'str'},
                'ctr_cd': {'desc': '合约标的', 'type': 'str'},
                'smb': {'desc': '合约代码', 'type': 'str'},
                'chn_sht_nm': {'desc': '中文简称', 'type': 'str'},
                'exg_cd': {'desc': '交易市场', 'type': 'str'},
                'ctr_typ': {'desc': '合约类型', 'type': 'str'},
                'obj_smb': {'desc': '标的品种代码', 'type': 'str'},
                'obj_nm': {'desc': '标的品种名称', 'type': 'str'},
                'obj_trm_dscr': {'desc': '标的品种合约周期说明', 'type': 'str'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'ctr_mul': {'desc': '每手交易量(合约乘数)', 'type': 'float64'},
                'trd_unt': {'desc': '交易单位', 'type': 'str'},
                'quo_unt': {'desc': '报价单位', 'type': 'str'},
                'min_chg_prc': {'desc': '最小变动价位', 'type': 'str'},
                'pct_daily': {'desc': '每日涨跌幅度', 'type': 'str'},
                'min_mrgn': {'desc': '最低保证金比例(%)', 'type': 'float64'},
                'min_mrgn_dscr': {'desc': '最低保证金说明', 'type': 'str'},
                'eft_dt': {'desc': '生效日期', 'type': 'datetime64[ns]'},
                'ctr_sts': {'desc': '合约状态', 'type': 'str'},
                'bas_prc': {'desc': '挂牌基准价', 'type': 'float64'},
                'trd_tm_dscr': {'desc': '交易时间说明', 'type': 'str'},
                'last_trd_dt': {'desc': '最后交易日', 'type': 'datetime64[ns]'},
                'last_trd_dt_dscr': {'desc': '最后交易日说明', 'type': 'str'},
                'stl_prc_dscr': {'desc': '结算价及计算方式说明', 'type': 'str'},
                'dlv_dt': {'desc': '交割日期', 'type': 'datetime64[ns]'},
                'dlv_dt_dscr': {'desc': '交割日期说明', 'type': 'str'},
                'last_dlv_dt': {'desc': '最后交割日', 'type': 'datetime64[ns]'},
                'dlv_yrea': {'desc': '交割年份', 'type': 'str'},
                'dlv_mon': {'desc': '交割月份', 'type': 'str'},
                'dlv_mod': {'desc': '交割方式', 'type': 'str'},
                'div_grd': {'desc': '标的品种名称', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '合约代码', 'type': 'str'},
            },
        },
    },

    # 2.行情
    'FTR_EODPRICE': {
        'source_table': 'AIWEFTROPT.FTR_EODPRICE',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '期货日行情表',
            'active': True,
            'date_field': 'date',
            'category': '期货(原表)/行情',
            'rank': 4002001,
            'friendly_name': '期货日行情表',
            'partition_date': 'Y',
            'primary_key': ['ftr_cd', 'trd_dt', 'instrument', 'date'],
            'fields': {
                'ftr_cd': {'desc': '期货内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'prev_cls_prc': {'desc': '昨收盘(元)', 'type': 'float64'},
                'prev_stl_prc': {'desc': '昨结算(元)', 'type': 'float64'},
                'opn_prc': {'desc': '开盘价(元)', 'type': 'float64'},
                'hi_prc': {'desc': '最高价(元)', 'type': 'float64'},
                'lo_prc': {'desc': '最低价(元)', 'type': 'float64'},
                'cls_prc': {'desc': '收盘价(元)', 'type': 'float64'},
                'stl_prc': {'desc': '结算价(元)', 'type': 'float64'},
                'up_lmt_prc': {'desc': '涨停价(元)', 'type': 'float64'},
                'dn_lmt_prc': {'desc': '跌停价(元)', 'type': 'float64'},
                'chg_prc_cls': {'desc': '收盘涨跌(元)', 'type': 'float64'},
                'pct_chg_cls': {'desc': '收盘涨跌幅(%)', 'type': 'float64'},
                'chg_stl': {'desc': '结算涨跌(元)', 'type': 'float64'},
                'pct_chg_stl': {'desc': '结算涨跌幅(%)', 'type': 'float64'},
                'vol': {'desc': '成交量(手)', 'type': 'float64'},
                'amt': {'desc': '成交金额(万元)', 'type': 'float64'},
                'oi': {'desc': '持仓量(手)', 'type': 'float64'},
                'chg_oi': {'desc': '持仓量变化(手)', 'type': 'float64'},
                'bas_prc': {'desc': '挂牌基准价', 'type': 'float64'},
                'is_main_ctr': {'desc': '是否主力合约', 'type': 'str'},
                'is_main_ctr_scd': {'desc': '是否次主力合约', 'type': 'str'},
                'obj_smb': {'desc': '标的品种代码', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '合约代码', 'type': 'str'},
            },
        },
    },

    # 3.国债期货
    'FTR_CNVFACTOR_TF': {
        'source_table': 'AIWEFTROPT.FTR_CNVFACTOR_TF',
        'date': None,     # 表中中时间字段非主键，这里也不设置date
        'date_format': None,
        'instrument': 'smb',
        'schema': {
            'desc': '国债转换因子表',
            'active': True,
            'date_field': None,
            'category': '期货(原表)/国债期货',
            'rank': 4003001,
            'friendly_name': '国债转换因子表',
            'partition_date': None,
            'primary_key': ['bnd_cd', 'ftr_cd'],
            'fields': {
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'ftr_cd': {'desc': '期货内部编码', 'type': 'str'},
                'cnv_fct': {'desc': '转换因子', 'type': 'float64'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '合约代码', 'type': 'str'},
            },
        },
    },
}

