TABLES_MAPS = {
    # 没有按照文档的目录顺序
    # 基本资料 --> category: 股票/基本资料
    'STK_BASICINFO': {
        'source_table': 'AIWESTK.STK_BASICINFO',
        'date': None,
        'date_format': None,
        'instrument': 'smb',
        'schema': {
            'desc': '股票基本资料表',
            'active': True,
            'date_field': None,
            'category': '股票(原表)/基础信息',
            'rank': 2001001,
            'friendly_name': '股票基本资料表',
            'partition_date': None,
            'primary_key': ['stk_cd', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'smb': {'desc': '证券代码', 'type': 'str'},
                'exg_cd': {'desc': '证券市场', 'type': 'str'},
                'chn_sht_nm': {'desc': '中文简称', 'type': 'str'},
                'eng_sht_nm': {'desc': '英文简称', 'type': 'str'},
                'sec_typ': {'desc': '证券类型', 'type': 'str'},
                'pty_cd': {'desc': '主体编码', 'type': 'str'},
                'pty_chn_nm': {'desc': '主体名称', 'type': 'str'},
                'pty_eng_nm': {'desc': '主体英文名称', 'type': 'str'},
                'isin': {'desc': 'ISIN代码', 'type': 'str'},
                'sedol': {'desc': 'SEDOL代码', 'type': 'str'},
                'trd_ccy_cd': {'desc': '交易币种', 'type': 'str'},
                'cpn_ccy_cd': {'desc': '面值币种', 'type': 'str'},
                'par_val': {'desc': '面值', 'type': 'float64'},
                'lst_sts': {'desc': '上市状态', 'type': 'str'},
                'lst_dt': {'desc': '上市日期', 'type': 'datetime64[ns]'},
                'delst_dt': {'desc': '退市日期', 'type': 'datetime64[ns]'},
                'lst_brd': {'desc': '上市板块', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'STK_SPCTREAT': {
        'source_table': 'AIWESTK.STK_SPCTREAT',
        'date': 'impl_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票特别处理表',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/基础信息',
            'rank': 2001002,
            'friendly_name': '股票特别处理表',
            'partition_date': None,
            'primary_key': ['stk_cd', 'st_typ', 'impl_dt', 'instrument'],
            'fields': {
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'st_typ': {'desc': '特别处理类型', 'type': 'str'},
                'impl_dt': {'desc': '实施日期', 'type': 'datetime64[ns]'},
                'impl_rsn': {'desc': '实施原因', 'type': 'str'},
                'st_typ_prev': {'desc': '前次类型', 'type': 'str'},
                'wdw_dt': {'desc': '撤销日期', 'type': 'datetime64[ns]'},
                'st_typ_nxt': {'desc': '撤销后类型', 'type': 'str'},
                'remark': {'desc': '备注', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '实施日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'STK_INFOCHG': {
        'source_table': 'AIWESTK.STK_INFOCHG',
        'date': 'chg_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票信息变动',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/基础信息',
            'rank': 2001003,
            'friendly_name': '股票信息变动',
            'partition_date': None,
            'primary_key': ['stk_cd', 'chg_typ', 'chg_dt', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'chg_typ': {'desc': '变动类型', 'type': 'str'},
                'chg_dt': {'desc': '变动日期', 'type': 'datetime64[ns]'},
                'prev_info': {'desc': '变动前信息', 'type': 'str'},
                'aft_info': {'desc': '变动后信息', 'type': 'str'},
                'chg_rsn_dscr': {'desc': '变动原因描述', 'type': 'str'},
                'end_dt': {'desc': '变动后信息使用截止日', 'type': 'datetime64[ns]'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '变动日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'USS_BASICINFO': {
        'source_table': 'AIWESTK.USS_BASICINFO',
        'date': None,
        'date_format': None,
        'instrument': 'smb',
        'schema': {
            'desc': '美股基本资料',
            'active': True,
            'date_field': None,
            'category': '股票(原表)/基础信息',
            'rank': 2001004,
            'friendly_name': '美股基本资料',
            'partition_date': None,
            'primary_key': ['stk_cd', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'smb': {'desc': '证券代码', 'type': 'str'},
                'exg_cd': {'desc': '证券市场', 'type': 'str'},
                'chn_sht_nm': {'desc': '中文简称', 'type': 'str'},
                'eng_sht_nm': {'desc': '英文简称', 'type': 'str'},
                'sec_typ': {'desc': '证券类型', 'type': 'str'},
                'pty_cd': {'desc': '主体编码', 'type': 'str'},
                'isin': {'desc': 'ISIN代码', 'type': 'str'},
                'sedol': {'desc': 'SEDOL代码', 'type': 'str'},
                'trd_ccy_cd': {'desc': '交易币种', 'type': 'str'},
                'cpn_ccy_cd': {'desc': '面值币种', 'type': 'str'},
                'par_val': {'desc': '面值(元）', 'type': 'float64'},
                'lst_sts': {'desc': '上市状态', 'type': 'str'},
                'lst_dt': {'desc': '上市日期', 'type': 'datetime64[ns]'},
                'delst_dt': {'desc': '退市日期', 'type': 'datetime64[ns]'},
                'lst_brd': {'desc': '上市板块', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'CCS_BASICINFO': {
        'source_table': 'AIWESTK.CCS_BASICINFO',
        'date': None,
        'date_format': None,
        'instrument': 'smb',
        'schema': {
            'desc': '中国概念股股票基本资料',
            'active': True,
            'date_field': None,
            'category': '股票(原表)/基础信息',
            'rank': 2001005,
            'friendly_name': '中国概念股股票基本资料',
            'partition_date': None,
            'primary_key': ['stk_cd', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'smb': {'desc': '证券代码', 'type': 'str'},
                'exg_cd': {'desc': '证券市场', 'type': 'str'},
                'chn_sht_nm': {'desc': '中文简称', 'type': 'str'},
                'eng_sht_nm': {'desc': '英文简称', 'type': 'str'},
                'sec_typ': {'desc': '证券类型', 'type': 'str'},
                'pty_cd': {'desc': '主体编码', 'type': 'str'},
                'pty_chn_nm': {'desc': '主体名称', 'type': 'str'},
                'pty_eng_nm': {'desc': '主体英文名称', 'type': 'str'},
                'isin': {'desc': 'ISIN代码', 'type': 'str'},
                'sedol': {'desc': 'SEDOL代码', 'type': 'str'},
                'trd_ccy_cd': {'desc': '交易币种', 'type': 'str'},
                'cpn_ccy_cd': {'desc': '面值币种', 'type': 'str'},
                'par_val': {'desc': '面值(元）', 'type': 'float64'},
                'lst_sts': {'desc': '上市状态', 'type': 'str'},
                'lst_dt': {'desc': '上市日期', 'type': 'datetime64[ns]'},
                'delst_dt': {'desc': '退市日期', 'type': 'datetime64[ns]'},
                'lst_brd': {'desc': '上市板块', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    # 股本股东
    'STK_FREECRCSHR': {
        'source_table': 'AIWESTK.STK_FREECRCSHR',
        'date': 'chg_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': 'A股自由流通股本',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/股本股东',
            'rank': 2002001,
            'friendly_name': 'A股自由流通股本',
            'partition_date': None,
            'primary_key': ['stk_cd', 'chg_dt', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票编码', 'type': 'str'},
                'chg_dt': {'desc': '变动日期（除权日）', 'type': 'datetime64[ns]'},
                'chg_dt_lst': {'desc': '变动日期（上市日）', 'type': 'datetime64[ns]'},
                'fre_crc_shr': {'desc': '自由流通股本', 'type': 'float64'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '变动日期（除权日）', 'type': 'datetime64[ns]'},
            },
        },
    },
    # 沪深港通  注意这个是否需要merge港股basicinfo去找smb??
    'STK_SCMEMBERS': {
        'source_table': 'AIWESTK.STK_SCMEMBERS',
        'date': 'sel_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '沪深港股通成分股',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/沪深港通',
            'rank': 2003001,
            'friendly_name': '沪深港股通成分股',
            'partition_date': None,
            'primary_key': ['stk_cd', 'sel_dt', 'exg_cd', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'sel_dt': {'desc': '入选日期', 'type': 'datetime64[ns]'},
                'out_dt': {'desc': '剔除日期', 'type': 'datetime64[ns]'},
                'cur_sgn': {'desc': '最新标志', 'type': 'str'},
                'pty_cd': {'desc': '主体内部编码', 'type': 'str'},
                'smb_typ': {'desc': '股票代码类型', 'type': 'str'},
                'smb': {'desc': '股票代码', 'type': 'str'},
                'exg_cd': {'desc': '交易市场', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '入选日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    # 融资STK_BASICINFO
    'STK_IPO': {
        'source_table': 'AIWESTK.STK_IPO',
        'date': None,
        'date_format': None,
        'instrument': 'smb',
        'schema': {
            'desc': '股票首次公开发行信息',
            'active': True,
            'date_field': None,
            'category': '股票(原表)/融资',
            'rank': 2003002,
            'friendly_name': '股票首次公开发行信息',
            'partition_date': None,
            'primary_key': ['stk_cd'],
            'fields': {
                'stk_cd': {'desc': '证券内部编码', 'type': 'str'},
                'pty_cd': {'desc': '公司编码', 'type': 'str'},
                'anc_dt_ini': {'desc': '首次公告日期', 'type': 'datetime64[ns]'},
                'anc_dt_lat': {'desc': '最新公告日期', 'type': 'datetime64[ns]'},
                'iec_dt': {'desc': '发审委通过日期', 'type': 'datetime64[ns]'},
                'anc_dt_prspts': {'desc': '招股公告日', 'type': 'datetime64[ns]'},
                'file_nbr': {'desc': '发文字号', 'type': 'str'},
                'anc_dt_iss': {'desc': '发行公告日', 'type': 'datetime64[ns]'},
                'iss_mod_ch': {'desc': '发行方式（财汇）', 'type': 'str'},
                'iss_mod_dscr': {'desc': '发行方式说明', 'type': 'str'},
                'iss_sbj': {'desc': '发行对象', 'type': 'str'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'iss_sts': {'desc': '发行状态', 'type': 'str'},
                'iss_vol_ceil_plan': {'desc': '拟发行数量上限（股）', 'type': 'float64'},
                'iss_vol_flr_plan': {'desc': '拟发行数量下限（股）', 'type': 'float64'},
                'iss_vol_tsy_plan': {'desc': '拟存量发行上限（股）', 'type': 'float64'},
                'ovr_pla_vol_plan': {'desc': '拟超额配售数量（股）', 'type': 'float64'},
                'ras_amt_est': {'desc': '预计公司募集资金总额（元）', 'type': 'float64'},
                'pla_vol_strt_plan': {'desc': '拟战略配售数量（股）', 'type': 'float64'},
                'tgt_pla_vol_plan': {'desc': '定向拟配售数量（股）', 'type': 'float64'},
                'iss_vol_onl_plan': {'desc': '网上拟发行数量（股）', 'type': 'float64'},
                'iss_vol_ofl_plan': {'desc': '网下拟发行数量（股）', 'type': 'float64'},
                'uw_mod': {'desc': '承销方式', 'type': 'str'},
                'lead_uw': {'desc': '主承销商', 'type': 'str'},
                'dpt_uw': {'desc': '副承销商', 'type': 'str'},
                'distrbt': {'desc': '分销商', 'type': 'str'},
                'lst_sps': {'desc': '上市推荐人', 'type': 'str'},
                'sps_org': {'desc': '保荐机构', 'type': 'str'},
                'start_dt_uw': {'desc': '承销起始日', 'type': 'datetime64[ns]'},
                'end_dt_uw': {'desc': '承销截止日', 'type': 'datetime64[ns]'},
                'pos_mkv_dt': {'desc': '市值计算参考日', 'type': 'datetime64[ns]'},
                'mkv_trhd_inq_ofl': {'desc': '网下询价市值门槛（元）', 'type': 'float64'},
                'mkv_trhd_inq_ofl_a': {'desc': '网下询价市值门槛（A类）（元）', 'type': 'float64'},
                'mkv_trhd_inq_ofl_star': {'desc': '网下询价市值门槛（科创主题与战略）（元）', 'type': 'float64'},
                'ivstr_reg_dt_ofl': {'desc': '网下投资者截止备案日期（协会）', 'type': 'datetime64[ns]'},
                'ivstr_chk_dt_ofl': {'desc': '网下投资者核查认证日期', 'type': 'datetime64[ns]'},
                'apl_rule_org': {'desc': '机构投资者申购规则', 'type': 'str'},
                'anc_dt_pre_inq': {'desc': '初步询价公告日', 'type': 'datetime64[ns]'},
                'start_dt_pre_inq': {'desc': '初步询价（预路演）起始日期', 'type': 'datetime64[ns]'},
                'end_dt_pre_inq': {'desc': '初步询价（预路演）终止日期', 'type': 'datetime64[ns]'},
                'iss_prc_cfm_dt': {'desc': '发行价格确认日', 'type': 'datetime64[ns]'},
                'min_prgr_prc_pre_inq': {'desc': '初步询价最小累进价格（元）', 'type': 'float64'},
                'sbj_num_pre_inq': {'desc': '初步询价对象家数（家）', 'type': 'float64'},
                'pla_sbj_num_pre_inq': {'desc': '初步询价配售对象家数（家）', 'type': 'float64'},
                'apl_vol_pre_inq': {'desc': '初步询价申报总量（股）', 'type': 'float64'},
                'min_prc_pre_inq': {'desc': '初步询价报价结果下限（元）', 'type': 'float64'},
                'max_prc_pre_inq': {'desc': '初步询价报价结果上限（元）', 'type': 'float64'},
                'out_hi_prc_flr': {'desc': '剔除的最高报价下限(含)（元）', 'type': 'float64'},
                'out_apl_vol_hi_prc': {'desc': '剔除的最高报价的申购量（股）', 'type': 'float64'},
                'ovr_apl_mul_pre_inq': {'desc': '初步询价有效报价对应的超额认购倍数', 'type': 'float64'},
                'anc_dt_rsl_pre_inq': {'desc': '初步询价结果公告日', 'type': 'datetime64[ns]'},
                'iss_prc_ceil': {'desc': '发行价上限（元）', 'type': 'float64'},
                'iss_prc_flr': {'desc': '发行价下限（元）', 'type': 'float64'},
                'pe_ceil_prev': {'desc': '价格区间上限市盈率（发行前）', 'type': 'float64'},
                'pe_flr_prev': {'desc': '价格区间下限市盈率（发行前）', 'type': 'float64'},
                'pe_ceil_aft': {'desc': '价格区间上限市盈率（发行后）', 'type': 'float64'},
                'pe_flr_aft': {'desc': '价格区间下限市盈率（发行后）', 'type': 'float64'},
                'pe_indu': {'desc': '行业PE', 'type': 'float64'},
                'anc_dt_prc_ofl': {'desc': '网下定价公告日', 'type': 'datetime64[ns]'},
                'pla_start_dt_ofl': {'desc': '网下申购起始日', 'type': 'datetime64[ns]'},
                'pla_end_dt_ofl': {'desc': '网下申购截止日', 'type': 'datetime64[ns]'},
                'pla_start_time_ofl': {'desc': '网下配售申购起始时间', 'type': 'datetime64[ns]'},
                'pla_end_time_ofl': {'desc': '网下配售申购截止时间', 'type': 'datetime64[ns]'},
                'apl_vol_ceil_ofl': {'desc': '网下账户申购上限（股）', 'type': 'float64'},
                'apl_vol_flr_ofl': {'desc': '网下账户申购下限（股）', 'type': 'float64'},
                'apl_prgr_vol_ofl': {'desc': '网下申购累进数量（股）', 'type': 'float64'},
                'prgr_prc_acm_inq': {'desc': '累计询价最小累进价格（元）', 'type': 'float64'},
                'sbj_num_acm_inq': {'desc': '网下累计投标询价对象家数', 'type': 'float64'},
                'apl_vol_ofl': {'desc': '网下申购总量（股）', 'type': 'float64'},
                'vld_apl_vol_ofl': {'desc': '网下有效申购总量（股）', 'type': 'float64'},
                'vld_inq_num_ofl': {'desc': '网下有效报价询价对象家数', 'type': 'float64'},
                'apl_vol_abvp_ofl': {'desc': '网下发行价格以上有效申购总量（股）', 'type': 'float64'},
                'ovr_apl_mul_ofl': {'desc': '网下超额认购倍数', 'type': 'float64'},
                'iss_mul_ofl': {'desc': '网下发行倍数', 'type': 'float64'},
                'prc_max_bias': {'desc': '价格最大偏离度', 'type': 'float64'},
                'vld_apl_amt_ofl': {'desc': '网下有效申购资金总额（元）', 'type': 'float64'},
                'nvld_apl_amt_ofl': {'desc': '网下无效申购资金总额（元）', 'type': 'float64'},
                'fro_amt_ofl': {'desc': '网下冻结资金总额（元）', 'type': 'float64'},
                'alc_nbr_dt_ofl': {'desc': '网下申购配号日', 'type': 'datetime64[ns]'},
                'nbr_num_ofl': {'desc': '网下发行配号总数', 'type': 'float64'},
                'dt_drw_lot_ofl': {'desc': '网下申购摇号抽签日', 'type': 'datetime64[ns]'},
                'win_nbr_vol_ofl': {'desc': '网下发行中签号码个数', 'type': 'float64'},
                'win_nbr_ofl': {'desc': '网下发行中签号码', 'type': 'str'},
                'pla_vol_spc_ofl': {'desc': '网下特殊中签号配售股数（股）', 'type': 'float64'},
                'win_nbr_spc_ofl': {'desc': '网下特殊中签号', 'type': 'str'},
                'tgt_pla_vol': {'desc': '定向配售数量（股）', 'type': 'float64'},
                'tgt_pla_dt': {'desc': '定向配售日', 'type': 'datetime64[ns]'},
                'anc_dt_tgt_pla_rsl': {'desc': '定向配售结果公告日', 'type': 'datetime64[ns]'},
                'pla_smb_2nd_szmkt': {'desc': '二级市场深配售代码', 'type': 'str'},
                'pla_smb_2nd_shmkt': {'desc': '二级市场沪配售代码', 'type': 'str'},
                'pla_chn_sht_nm_2nd_mkt': {'desc': '二级市场配售简称', 'type': 'str'},
                'pla_vol_2nd_mkt': {'desc': '二级市场配售股数（股）', 'type': 'float64'},
                'win_rat_2nd_mkt_pla': {'desc': '二级市场配售中签率（%）', 'type': 'float64'},
                'pla_dt_2nd_mkt': {'desc': '二级市场配售日期', 'type': 'datetime64[ns]'},
                'anc_dt_win_rat_2nd_mkt': {'desc': '二级市场配售中签率公告日', 'type': 'datetime64[ns]'},
                'anc_dt_pla_ofl': {'desc': '网下配售发行公告日', 'type': 'datetime64[ns]'},
                'vld_quo_sbj_num_ofl': {'desc': '网下有效报价配售对象家数', 'type': 'float64'},
                'vld_apl_sbj_num_ofl': {'desc': '网下有效申购配售对象家数', 'type': 'float64'},
                'pla_sbj_num_ofl': {'desc': '网下配售对象家数', 'type': 'float64'},
                'nvld_pla_sbj_num_ofl': {'desc': '网下无效申购配售对象家数', 'type': 'float64'},
                'nvld_apl_vol_ofl': {'desc': '网下无效申购总量（股）', 'type': 'float64'},
                'pla_rat_ofl': {'desc': '网下配售比例（%）', 'type': 'float64'},
                'anc_dt_pla_rsl_ofl': {'desc': '网下初步配售结果公告日', 'type': 'datetime64[ns]'},
                'start_pay_dt_ofl': {'desc': '网下配售缴款起始日', 'type': 'datetime64[ns]'},
                'end_pay_dt_ofl': {'desc': '网下配售缴款截止日', 'type': 'datetime64[ns]'},
                'pay_dt_strt': {'desc': '战略投资者申购缴款日', 'type': 'datetime64[ns]'},
                'mny_chk_dt_ofl': {'desc': '网下验资日', 'type': 'datetime64[ns]'},
                'pay_rat_ofl': {'desc': '网下账户申购缴款比例（%）', 'type': 'float64'},
                'sbj_num_ful_pay_ofl': {'desc': '网下足额缴申购款配售对象家数', 'type': 'float64'},
                'anc_dt_rsl_ofl': {'desc': '网下配售结果公告日', 'type': 'datetime64[ns]'},
                'rfnd_dt_ofl': {'desc': '网下申购资金退款日', 'type': 'datetime64[ns]'},
                'rfnd_dt_clbk_ofl': {'desc': '网下申购资金退款日（回拨机制实施后）', 'type': 'datetime64[ns]'},
                'anc_dt_prc_onl': {'desc': '网上定价发行公告日', 'type': 'datetime64[ns]'},
                'anc_dt_rd_show_onl': {'desc': '网上路演公告日', 'type': 'datetime64[ns]'},
                'start_dt_rd_show_onl': {'desc': '网上路演起始日', 'type': 'datetime64[ns]'},
                'end_dt_rd_show_onl': {'desc': '网上路演截止日', 'type': 'datetime64[ns]'},
                'url_rd_show_onl': {'desc': '网上路演地址', 'type': 'str'},
                'anc_dt_apl_onl': {'desc': '网上申购发行公告日', 'type': 'datetime64[ns]'},
                'apl_smb_onl': {'desc': '网上申购代码', 'type': 'str'},
                'apl_chn_sht_nm_onl': {'desc': '网上申购简称', 'type': 'str'},
                'start_apl_dt_onl': {'desc': '网上申购起始日', 'type': 'datetime64[ns]'},
                'end_apl_dt_onl': {'desc': '网上申购截止日', 'type': 'datetime64[ns]'},
                'reg_dt_mkv_onl': {'desc': '网上市值申购登记日', 'type': 'datetime64[ns]'},
                'apl_vol_ceil_onl': {'desc': '网上账户申购上限（股）', 'type': 'float64'},
                'min_prgr_vol_onl': {'desc': '网上申购累进数量（股）', 'type': 'float64'},
                'vld_apl_num_onl': {'desc': '网上发行有效申购户数', 'type': 'float64'},
                'vld_apl_vol_onl': {'desc': '网上发行有效申购股数（股）', 'type': 'float64'},
                'ovr_apl_mul_onl': {'desc': '网上超额认购倍数', 'type': 'float64'},
                'alc_nbr_dt_onl': {'desc': '网上配号日', 'type': 'datetime64[ns]'},
                'dt_draw_lot_onl': {'desc': '网上摇号抽签日', 'type': 'datetime64[ns]'},
                'sgn_num_onl': {'desc': '网上发行配号总数', 'type': 'float64'},
                'anc_dt_win_rat_onl': {'desc': '网上中签率公告日', 'type': 'datetime64[ns]'},
                'win_rat_onl': {'desc': '网上发行中签率（%）', 'type': 'float64'},
                'anc_dt_win_nbr_onl': {'desc': '网上中签结果公告日', 'type': 'datetime64[ns]'},
                'win_nbr_vol_onl': {'desc': '网上发行中签号个数', 'type': 'float64'},
                'win_nbr_onl': {'desc': '网上发行中签号码', 'type': 'str'},
                'pay_dt_onl': {'desc': '网上申购缴款日', 'type': 'datetime64[ns]'},
                'mny_chk_dt_onl': {'desc': '网上申购资金验资日', 'type': 'datetime64[ns]'},
                'cfm_dt_vld_apl_onl': {'desc': '确认网上有效申购日', 'type': 'datetime64[ns]'},
                'pay_rat_onl': {'desc': '网上账户申购缴款比例（%）', 'type': 'float64'},
                'start_dt_fro_onl': {'desc': '网上资金冻结起始日', 'type': 'datetime64[ns]'},
                'end_dt_fro_onl': {'desc': '网上资金冻结截止日', 'type': 'datetime64[ns]'},
                'unfro_dt_onl': {'desc': '网上申购款解冻日', 'type': 'datetime64[ns]'},
                'rfnd_dt_onl': {'desc': '网上申购资金退款日', 'type': 'datetime64[ns]'},
                'fro_amt_onl': {'desc': '网上冻结资金总额（元）', 'type': 'float64'},
                'anc_dt_rsl_onl': {'desc': '网上发行结果公告日', 'type': 'datetime64[ns]'},
                'onl_iss_vol': {'desc': '网上发行数量（股）', 'type': 'float64'},
                'iss_rsl': {'desc': '发行结果', 'type': 'str'},
                'cfm_dt_ssp_iss': {'desc': '中止发行确定日期', 'type': 'datetime64[ns]'},
                'clbk_rat': {'desc': '网上网下回拨比例', 'type': 'int64'},
                'clbk_vol': {'desc': '回拨数量（股）', 'type': 'float64'},
                'par_val': {'desc': '每股面值（元）', 'type': 'float64'},
                'iss_prc': {'desc': '发行价格（元）', 'type': 'float64'},
                'iss_vol': {'desc': '发行总量（股）', 'type': 'float64'},
                'iss_vol_tsy': {'desc': '存量发行量（股）', 'type': 'float64'},
                'ovr_pla_vol': {'desc': '超额配售数量（股）', 'type': 'float64'},
                'iss_vol_new': {'desc': '新增发行量（股）', 'type': 'float64'},
                'apl_vol_ceil_org': {'desc': '机构申购数量上限', 'type': 'float64'},
                'apl_amt_ceil_org': {'desc': '机构申购金额上限', 'type': 'float64'},
                'ras_amt_tot': {'desc': '公司募集资金总额（元）', 'type': 'float64'},
                'ras_amt_net': {'desc': '公司募集资金净额（元）', 'type': 'float64'},
                'pla_vol_ofl': {'desc': '网下发行数量（股）', 'type': 'float64'},
                'pla_vol_lp': {'desc': '向一般法人配售数量（股）', 'type': 'float64'},
                'pla_vol_strt': {'desc': '向战略投资者配售数量（股）', 'type': 'float64'},
                'pla_vol_stt': {'desc': '国家股股东实际配售量（股）', 'type': 'float64'},
                'pla_vol_pub': {'desc': '社会公众股实际认购量（股）', 'type': 'float64'},
                'pla_vol_fund': {'desc': '基金投资者实际认购量（股）', 'type': 'float64'},
                'pla_vol_oth': {'desc': '其他投资者实际认购量（股）', 'type': 'float64'},
                'pla_vol_stf': {'desc': '配售职工股数（股）', 'type': 'float64'},
                'vol_uw_buy': {'desc': '承销商自包数量（股）', 'type': 'float64'},
                'iss_amt_tot': {'desc': '发行资金总额（元）', 'type': 'float64'},
                'iss_amt_net': {'desc': '发行资金净额（元）', 'type': 'float64'},
                'amt_tsy_iss': {'desc': '存量发行转让资金总额（元）', 'type': 'float64'},
                'mny_rcv_dt': {'desc': '募集资金到帐日', 'type': 'datetime64[ns]'},
                'iss_fail_rfnd_dt': {'desc': '发行失败退款日', 'type': 'datetime64[ns]'},
                'shh_num_thsd': {'desc': '千股以上户数', 'type': 'float64'},
                'iss_fee': {'desc': '发行费用总额（元）', 'type': 'float64'},
                'new_iss_fee': {'desc': '新股发行费用总额（元）', 'type': 'float64'},
                'tsy_iss_fee': {'desc': '存量发行费用总额（元）', 'type': 'float64'},
                'iss_fee_per_shr': {'desc': '每股发行费用（元）', 'type': 'float64'},
                'cmsn_fee_rat': {'desc': '新股配售经纪佣金费率（%）', 'type': 'float64'},
                'tot_shr_prev': {'desc': '发行前总股数（股）', 'type': 'float64'},
                'tot_shr_aft': {'desc': '发行后总股数（股）', 'type': 'float64'},
                'eps_prev': {'desc': '发行前每股收益（全面摊薄）', 'type': 'float64'},
                'eps_aft': {'desc': '发行后每股收益（全面摊薄）', 'type': 'float64'},
                'pb_iss': {'desc': '发行市净率', 'type': 'float64'},
                'bps_prev': {'desc': '发行前每股净资产', 'type': 'float64'},
                'bps_aft': {'desc': '发行后每股净资产', 'type': 'float64'},
                'pe_prev': {'desc': '发行前市盈率', 'type': 'float64'},
                'pe_aft': {'desc': '发行后市盈率', 'type': 'float64'},
                'anc_dt_lst': {'desc': '上市公告日', 'type': 'datetime64[ns]'},
                'lst_dt': {'desc': '上市日', 'type': 'datetime64[ns]'},
                'exg_cd': {'desc': '上市市场', 'type': 'str'},
                'lst_vol_iss': {'desc': '本次发行的首次上市流通数量（股）', 'type': 'float64'},
                'lst_dt_glp': {'desc': '向一般法人配售部分上市日期', 'type': 'datetime64[ns]'},
                'lst_dt_strt': {'desc': '向战略投资者配售部分上市日期', 'type': 'datetime64[ns]'},


                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    # 分红
    # 没有公告日，除权除息日是主键，用来作为date列
    'STK_EXRIGHT': {
        'source_table': 'AIWESTK.STK_EXRIGHT',
        'date': 'xrt_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票除权除息',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/分红',
            'rank': 2004001,
            'friendly_name': '股票除权除息',
            'partition_date': None,
            'primary_key': ['stk_cd', 'xrt_dt', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票编码', 'type': 'str'},
                'xrt_dt': {'desc': '除权除息日', 'type': 'datetime64[ns]'},
                'reg_dt': {'desc': '股权登记日', 'type': 'datetime64[ns]'},
                'xrt_typ': {'desc': '除权类型', 'type': 'str'},
                'xrt_dscr': {'desc': '除权说明', 'type': 'str'},
                'csh_dvd_rat': {'desc': '每股派息（1股派X）', 'type': 'float64'},
                'bns_shr_rat': {'desc': '送股比例（1股送X）', 'type': 'float64'},
                'dnt_shr_rat': {'desc': '赠股比例（1股赠X）', 'type': 'float64'},
                'alc_shr_rat': {'desc': '配股比例（1股配X）', 'type': 'float64'},
                'alc_prc': {'desc': '配股价格', 'type': 'float64'},
                'seo_shr_rat': {'desc': '增发比例（1股增发X）', 'type': 'float64'},
                'seo_prc': {'desc': '增发价格', 'type': 'float64'},
                'shr_srk_rat': {'desc': '缩减比例(1股拆缩为X)', 'type': 'float64'},
                'csh_dtrb_dt': {'desc': '现金红利发放日', 'type': 'datetime64[ns]'},
                'shr_act_dt': {'desc': '股份到帐日', 'type': 'datetime64[ns]'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '除权除息日', 'type': 'datetime64[ns]'},
            },
        },
    },
    # 没有日期作为主键，是分红年度+年内第N次分红+分红进程作为主键，date列用最初公告日期构建，非主键
    'STK_DIVIDEND': {
        'source_table': 'AIWESTK.STK_DIVIDEND',
        'date': 'anc_dt_ini',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票分红进度表',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/分红',
            'rank': 2004002,
            'friendly_name': '股票分红进度表',
            'partition_date': None,
            'primary_key': ['stk_cd', 'dvd_year', 'dvd_tms', 'dvd_obj', 'dvd_prgr', 'instrument'],
            'fields': {
                'anc_dt_ini': {'desc': '最初公告日期', 'type': 'datetime64[ns]'},
                'anc_dt_late': {'desc': '最新公告日期', 'type': 'datetime64[ns]'},
                'stk_cd': {'desc': '股票编码', 'type': 'str'},
                'dvd_year': {'desc': '分红年度', 'type': 'str'},
                'dvd_tms': {'desc': '年度第N次分红', 'type': 'str'},
                'dvd_trm': {'desc': '分红周期', 'type': 'str'},
                'dvd_obj': {'desc': '分红对象', 'type': 'str'},
                'dvd_prgr': {'desc': '分红进程', 'type': 'str'},
                'anc_dt_prps': {'desc': '预案公告日', 'type': 'datetime64[ns]'},
                'anc_dt_gm': {'desc': '股东大会决议公告日', 'type': 'datetime64[ns]'},
                'anc_dt_impl': {'desc': '分红实施公告日', 'type': 'datetime64[ns]'},
                'reg_dt': {'desc': '股权登记日', 'type': 'datetime64[ns]'},
                'xrt_dt': {'desc': '除权除息日', 'type': 'datetime64[ns]'},
                'shr_bas_dt': {'desc': '股本基准日', 'type': 'datetime64[ns]'},
                'shr_vol': {'desc': '股本基数', 'type': 'float64'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'csh_dtrb_dt': {'desc': '现金红利发放日', 'type': 'datetime64[ns]'},
                'dvd_bfr_tax': {'desc': '每股派息（税前）', 'type': 'float64'},
                'dvd_aft_tax': {'desc': '每股派息（税后）', 'type': 'float64'},
                'dvd_aft_tax_qfii': {'desc': 'QFII每股派息（税后）', 'type': 'float64'},
                'dvd_bfr_tax_cny': {'desc': '每股派息（税前，人民币）', 'type': 'float64'},
                'dvd_aft_tax_cny': {'desc': '每股派息（税后，人民币）', 'type': 'float64'},
                'dvd_aft_tax_qfii_cny': {'desc': 'QFII每股派息（税后，人民币）', 'type': 'float64'},
                'fx_rat': {'desc': '外币折算汇率', 'type': 'float64'},
                'fx_rat_dt': {'desc': '汇率折算日', 'type': 'datetime64[ns]'},
                'dvd_tot_cny': {'desc': '分红金额合计（人民币）', 'type': 'float64'},
                'bns_shr_rat': {'desc': '送股比例（10：X）', 'type': 'float64'},
                'trsf_shr_rat': {'desc': '转增比例（10：X）', 'type': 'float64'},
                'dnt_shr_rat': {'desc': '赠股比例（10：X）', 'type': 'float64'},
                'bns_trsf_rat': {'desc': '送转比例（10：X）', 'type': 'float64'},
                'shr_act_dt': {'desc': '股份到帐日', 'type': 'datetime64[ns]'},
                'lst_dt': {'desc': '红股上市日期', 'type': 'datetime64[ns]'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '最初公告日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    # 交易 --> category: 股票/行情
    'STK_EODPRICE': {
        'source_table': 'AIWESTK.STK_EODPRICE',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票日行情',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/行情',
            'rank': 2005001,
            'friendly_name': '股票日行情',
            'partition_date': 'Y',  # 单纯按照年存，没有分instrument
            'primary_key': ['stk_cd', 'trd_dt', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'prev_cls_prc': {'desc': '昨收盘（元）', 'type': 'float64'},
                'opn_prc': {'desc': '开盘价（元）', 'type': 'float64'},
                'hi_prc': {'desc': '最高价（元）', 'type': 'float64'},
                'lo_prc': {'desc': '最低价（元）', 'type': 'float64'},
                'cls_prc': {'desc': '收盘价（元）', 'type': 'float64'},
                'vol': {'desc': '成交量（股）', 'type': 'float64'},
                'amt': {'desc': '成交金额（元）', 'type': 'float64'},
                'deals': {'desc': '成交笔数（笔）', 'type': 'float64'},
                'avg_prc': {'desc': '成交均价（元）', 'type': 'float64'},
                'vol_per_deal': {'desc': '平均每笔成交量（股）', 'type': 'float64'},
                'amt_per_deal': {'desc': '平均每笔成交额（元）', 'type': 'float64'},
                'chg_prc': {'desc': '涨跌', 'type': 'float64'},
                'pct_chg': {'desc': '涨跌幅', 'type': 'float64'},
                'amplt': {'desc': '振幅', 'type': 'float64'},
                'trn_rat': {'desc': '换手率', 'type': 'float64'},
                'adj_fct': {'desc': '复权因子', 'type': 'float64'},
                'prev_cls_prc_adj': {'desc': '复权昨收盘价（元）', 'type': 'float64'},
                'opn_prc_adj': {'desc': '复权开盘价（元）', 'type': 'float64'},
                'hi_prc_adj': {'desc': '复权最高价（元）', 'type': 'float64'},
                'lo_prc_adj': {'desc': '复权最低价（元）', 'type': 'float64'},
                'cls_prc_adj': {'desc': '复权收盘价（元）', 'type': 'float64'},
                'trd_sts': {'desc': '交易状态', 'type': 'str'},
                'prc_lmt_sts': {'desc': '涨跌停状态', 'type': 'str'},
                'hi_lo_sts': {'desc': '最高最低价状态', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'STK_VALUATION': {
        'source_table': 'AIWESTK.STK_VALUATION',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票日行情估值',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/行情',
            'rank': 2005002,
            'friendly_name': '股票日行情估值',
            'partition_date': 'Y',  # 和EODPRICE表一样，按照年拆表存
            'primary_key': ['stk_cd', 'end_dt', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'end_dt': {'desc': '日期', 'type': 'datetime64[ns]'},
                'cls_prc': {'desc': '收盘价(元)', 'type': 'float64'},
                'tot_shr': {'desc': '总股本(股)', 'type': 'float64'},
                'crc_shr': {'desc': '流通股本(股)', 'type': 'float64'},
                'tot_mkv': {'desc': '总市值(人民币元)', 'type': 'float64'},
                'crc_mkv': {'desc': '流通市值(人民币元)', 'type': 'float64'},
                'entp_val': {'desc': '企业价值(人民币元)', 'type': 'float64'},
                'pe_lyr': {'desc': '市盈率(LYR)', 'type': 'float64'},
                'pe_ttm': {'desc': '市盈率(TTM)', 'type': 'float64'},
                'pe_mrq': {'desc': '市盈率(MRQ)', 'type': 'float64'},
                'pe_lyr_ddct': {'desc': '市盈率(扣非）', 'type': 'float64'},
                'pe_ttm_ddct': {'desc': '市盈率(TTM、扣非)', 'type': 'float64'},
                'pe_mrq_ddct': {'desc': '市盈率(MRQ、扣非)', 'type': 'float64'},
                'pb_lf': {'desc': '市净率(LF)', 'type': 'float64'},
                'pcf_ocf_lyr': {'desc': '市现率(经营现金流)', 'type': 'float64'},
                'pcf_ocf_ttm': {'desc': '市现率(经营现金流TTM)', 'type': 'float64'},
                'pcf_ncf_lyr': {'desc': '市现率(现金净流量)', 'type': 'float64'},
                'pcf_ncf_ttm': {'desc': '市现率(现金净流量TTM)', 'type': 'float64'},
                'ps_lyr': {'desc': '市销率(LYR)', 'type': 'float64'},
                'ps_ttm': {'desc': '市销率(TTM)', 'type': 'float64'},
                'ps_mrq': {'desc': '市销率(MRQ)', 'type': 'float64'},
                'dvd_yld': {'desc': '股息率(%)', 'type': 'float64'},
                'fre_crc_shr': {'desc': '当日自由流通股本(股)', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'STK_SUSPENSION': {
        'source_table': 'AIWESTK.STK_SUSPENSION',
        'date': 'ssp_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票停复牌信息',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/行情',
            'rank': 2005003,
            'friendly_name': '股票停复牌信息',
            'partition_date': None,
            'primary_key': ['stk_cd', 'ssp_dt', 'ssp_nbr', 'instrument'],
            'fields': {
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'stk_cd': {'desc': '股票编码', 'type': 'str'},
                'ssp_dt': {'desc': '停牌日期', 'type': 'datetime64[ns]'},
                'ssp_nbr': {'desc': '停牌序号', 'type': 'int64'},
                'ssp_tm': {'desc': '停牌时间', 'type': 'str'},
                'ssp_rsn': {'desc': '停牌原因', 'type': 'str'},
                'ssp_dscr': {'desc': '停牌事项描述', 'type': 'str'},
                'ssp_trm': {'desc': '停牌期限', 'type': 'str'},
                'rsm_dt': {'desc': '复牌日期', 'type': 'datetime64[ns]'},
                'rsm_tm': {'desc': '复牌时间', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '停牌日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'STK_TA_VOLUME': {
        'source_table': 'AIWESTK.STK_TA_VOLUME',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票成交量技术指标',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/行情',
            'rank': 2005004,
            'friendly_name': '股票成交量技术指标',
            'partition_date': 'Y',
            'primary_key': ['stk_cd', 'trd_dt', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'vol_rat_5d': {'desc': '量比(5日)', 'type': 'float64'},
                'vol_ma_1m': {'desc': '成交量简单移动平均MA(1月)', 'type': 'float64'},
                'vol_ma_22d': {'desc': '成交量简单移动平均MA(22日)', 'type': 'float64'},
                'vol_ma_60d': {'desc': '成交量简单移动平均MA(60日)', 'type': 'float64'},
                'vol_macd_dif': {'desc': '成交量MACD_DIF(12,26,9日)', 'type': 'float64'},
                'vol_macd_dea': {'desc': '成交量MACD_DEA(12,26,9日)', 'type': 'float64'},
                'vol_macd': {'desc': '成交量MACD(12,26,9日)', 'type': 'float64'},
                'vol_osc': {'desc': '成交量震荡VOSC(12,26日)', 'type': 'float64'},
                'tapi_6d': {'desc': '加权指数成交值TAPI(6日)', 'type': 'float64'},
                'tapi_ma_6d': {'desc': '加权指数成交值TAPIMA(6日)', 'type': 'float64'},
                'vol_std_10d': {'desc': '成交量标准差STD(10日)', 'type': 'float64'},
                'vol_rsi_6d': {'desc': '成交量相对强弱RSI(6日)', 'type': 'float64'},
                'vol_roc_12d': {'desc': '成交量变动速率ROC(12日)', 'type': 'float64'},
                'sobv': {'desc': '能量潮SOBV', 'type': 'float64'},
                'vr_26d': {'desc': 'VR成交量比率(26日)', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'STK_BLOCKTRADE': {
        'source_table': 'AIWESTK.STK_BLOCKTRADE',
        'date': 'trd_dt',   # 非主键
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',  # 股票内部编码非主键
        'schema': {
            'desc': 'A股大宗交易',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/行情',
            'rank': 2005005,
            'friendly_name': 'A股大宗交易',
            'partition_date': None,
            'primary_key': ['blc_trd_id', 'instrument'],
            'fields': {
                'blc_trd_id': {'desc': '大宗交易ID', 'type': 'str'},
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'deal_prc': {'desc': '成交价（元）', 'type': 'float64'},
                'deals': {'desc': '笔数', 'type': 'float64'},
                'vol': {'desc': '成交量（万股）', 'type': 'float64'},
                'amt': {'desc': '成交金额（万元）', 'type': 'float64'},
                'ccy_cd': {'desc': '货币代码', 'type': 'str'},
                'buy_nm': {'desc': '买方营业部名称', 'type': 'str'},
                'sel_nm': {'desc': '卖方营业部名称', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
            },
        },
    },

    # add in 2022-12-07
    'STK_MONEYFLOW': {
        'source_table': 'AIWESTK.STK_MONEYFLOW',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票资金流向数据',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/行情',
            'rank': 2005007,
            'friendly_name': '股票资金流向数据',
            'partition_date': 'Y',
            'primary_key': ['stk_cd', 'trd_dt', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'trd_dt': {'desc': '日期', 'type': 'datetime64[ns]'},
                'org_buy_amt': {'desc': '机构买入金额(万元)', 'type': 'float64'},
                'org_sel_amt': {'desc': '机构卖出金额(万元)', 'type': 'float64'},
                'org_buy_vol': {'desc': '机构买入总量(手)', 'type': 'float64'},
                'org_sel_vol': {'desc': '机构卖出总量(手)', 'type': 'float64'},
                'org_buy_ord_nbr': {'desc': '机构买入单数(单)', 'type': 'float64'},
                'org_sel_ord_nbr': {'desc': '机构卖出单数(单)', 'type': 'float64'},
                'org_vol_dif': {'desc': '机构量差(含主动被动)(手)', 'type': 'float64'},
                'org_vol_dif_actv': {'desc': '机构量差(仅主动)(手)', 'type': 'float64'},
                'org_amt_dif': {'desc': '机构金额差(含主动被动)(万元)', 'type': 'float64'},
                'org_amt_dif_actv': {'desc': '机构金额差(仅主动)(万元)', 'type': 'float64'},
                'org_buy_amt_actv': {'desc': '机构买入金额(仅主动)(万元)', 'type': 'float64'},
                'org_sel_amt_actv': {'desc': '机构卖出金额(仅主动)(万元)', 'type': 'float64'},
                'org_buy_vol_actv': {'desc': '机构买入总量(仅主动)(万股)', 'type': 'float64'},
                'org_sel_vol_actv': {'desc': '机构卖出总量(仅主动)(万股)', 'type': 'float64'},
                'lrg_trd_buy_amt': {'desc': '大户买入金额(万元)', 'type': 'float64'},
                'lrg_trd_sel_amt': {'desc': '大户卖出金额(万元)', 'type': 'float64'},
                'lrg_trd_buy_vol': {'desc': '大户买入总量(手)', 'type': 'float64'},
                'lrg_trd_sel_vol': {'desc': '大户卖出总量(手)', 'type': 'float64'},
                'lrg_trd_buy_ord_nbr': {'desc': '大户买入单数(单)', 'type': 'float64'},
                'lrg_trd_sel_ord_nbr': {'desc': '大户卖出单数(单)', 'type': 'float64'},
                'lrg_trd_vol_dif': {'desc': '大户量差(含主动被动)(手)', 'type': 'float64'},
                'lrg_trd_vol_dif_actv': {'desc': '大户量差(仅主动)(手)', 'type': 'float64'},
                'lrg_trd_amt_dif': {'desc': '大户金额差(含主动被动)(万元)', 'type': 'float64'},
                'lrg_trd_amt_dif_actv': {'desc': '大户金额差(仅主动)(万元)', 'type': 'float64'},
                'lrg_trd_buy_amt_actv': {'desc': '大户买入金额(仅主动)(万元)', 'type': 'float64'},
                'lrg_trd_sel_amt_actv': {'desc': '大户卖出金额(仅主动)(万元)', 'type': 'float64'},
                'lrg_trd_buy_vol_actv': {'desc': '大户买入总量(仅主动)(万股)', 'type': 'float64'},
                'lrg_trd_sel_vol_actv': {'desc': '大户卖出总量(仅主动)(万股)', 'type': 'float64'},
                'med_trd_buy_amt': {'desc': '中户买入金额(万元)', 'type': 'float64'},
                'med_trd_sel_amt': {'desc': '中户卖出金额(万元)', 'type': 'float64'},
                'med_trd_buy_vol': {'desc': '中户买入总量(手)', 'type': 'float64'},
                'med_trd_sel_vol': {'desc': '中户卖出总量(手)', 'type': 'float64'},
                'med_trd_buy_ord_nbr': {'desc': '中户买入单数(单)', 'type': 'float64'},
                'med_trd_sel_ord_nbr': {'desc': '中户卖出单数(单)', 'type': 'float64'},
                'med_trd_vol_dif': {'desc': '中户量差(含主动被动)(手)', 'type': 'float64'},
                'med_trd_vol_dif_actv': {'desc': '中户量差(仅主动)(手)', 'type': 'float64'},
                'med_trd_amt_dif': {'desc': '中户金额差(含主动被动)(万元)', 'type': 'float64'},
                'med_trd_amt_dif_actv': {'desc': '中户金额差(仅主动)(万元)', 'type': 'float64'},
                'med_trd_buy_amt_actv': {'desc': '中户买入金额(仅主动)(万元)', 'type': 'float64'},
                'med_trd_sel_amt_actv': {'desc': '中户卖出金额(仅主动)(万元)', 'type': 'float64'},
                'med_trd_buy_vol_actv': {'desc': '中户买入总量(仅主动)(万股)', 'type': 'float64'},
                'med_trd_sel_vol_actv': {'desc': '中户卖出总量(仅主动)(万股)', 'type': 'float64'},
                'sml_trd_buy_amt': {'desc': '散户买入金额(万元)', 'type': 'float64'},
                'sml_trd_sel_amt': {'desc': '散户卖出金额(万元)', 'type': 'float64'},
                'sml_trd_buy_vol': {'desc': '散户买入总量(手)', 'type': 'float64'},
                'sml_trd_sel_vol': {'desc': '散户卖出总量(手)', 'type': 'float64'},
                'sml_trd_buy_ord_nbr': {'desc': '散户买入单数(单)', 'type': 'float64'},
                'sml_trd_sel_ord_nbr': {'desc': '散户卖出单数(单)', 'type': 'float64'},
                'sml_trd_vol_dif': {'desc': '散户量差(含主动被动)(手)', 'type': 'float64'},
                'sml_trd_vol_dif_actv': {'desc': '散户量差(仅主动)(手)', 'type': 'float64'},
                'sml_trd_amt_dif': {'desc': '散户金额差(含主动被动)(万元)', 'type': 'float64'},
                'sml_trd_amt_dif_actv': {'desc': '散户金额差(仅主动)(万元)', 'type': 'float64'},
                'sml_trd_buy_amt_actv': {'desc': '散户买入金额(仅主动)(万元)', 'type': 'float64'},
                'sml_trd_sel_amt_actv': {'desc': '散户卖出金额(仅主动)(万元)', 'type': 'float64'},
                'sml_trd_buy_vol_actv': {'desc': '散户买入总量(仅主动)(万股)', 'type': 'float64'},
                'sml_trd_sel_vol_actv': {'desc': '散户卖出总量(仅主动)(万股)', 'type': 'float64'},
                'barg_cnt': {'desc': '成交笔数(笔)', 'type': 'float64'},
                'net_infl_vol': {'desc': '净流入量(手)', 'type': 'float64'},
                'infl_vol_rat': {'desc': '流入率(量)(%)', 'type': 'float64'},
                'net_infl_amt': {'desc': '净流入金额(万元)', 'type': 'float64'},
                'infl_amt_rat': {'desc': '流入率(金额)', 'type': 'float64'},
                'tot_entr_buy_vol': {'desc': '委买总量(手)', 'type': 'float64'},
                'tot_entr_sel_vol': {'desc': '委卖总量(手)', 'type': 'float64'},
                'mny_flw_pct_vol': {'desc': '资金流向占比(量)(%)', 'type': 'float64'},
                'mny_flw_amt_pct': {'desc': '资金流向占比(金额)', 'type': 'float64'},

                'date': {'desc': '日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '证券代码', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},
            },
        },
    },
    'STK_CSS_ROLLINGDATA': {
        'source_table': 'AIWESTK.STK_CSS_ROLLINGDATA',
        'date': 'css_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票一致预测滚动指标',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/行情',
            'rank': 2005008,
            'friendly_name': '股票一致预测滚动指标',
            'partition_date': 'Y',
            'primary_key': ['css_dt', 'roll_typ', 'stk_cd', 'instrument'],
            'fields': {
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},
                'css_dt': {'desc': '日期', 'type': 'datetime64[ns]'},
                'roll_typ': {'desc': '类型', 'type': 'str'},
                'net_pft': {'desc': '净利润', 'type': 'float64'},
                'css_eps': {'desc': '每股收益', 'type': 'float64'},
                'css_pe': {'desc': '市盈率', 'type': 'float64'},
                'css_peg': {'desc': 'PEG', 'type': 'float64'},
                'css_pb': {'desc': '市净率', 'type': 'float64'},
                'css_roe': {'desc': '净资产收益率', 'type': 'float64'},
                'css_bus_inc': {'desc': '营业收入', 'type': 'float64'},
                'css_cfps': {'desc': '每股现金流', 'type': 'float64'},
                'css_dps': {'desc': '每股股利', 'type': 'float64'},
                'css_bps': {'desc': '每股净资产', 'type': 'float64'},
                'css_ebit': {'desc': '息税前利润', 'type': 'float64'},
                'css_ebitda': {'desc': '息税折旧摊销前利润', 'type': 'float64'},
                'css_tot_pft': {'desc': '利润总额', 'type': 'float64'},
                'css_bus_pft': {'desc': '营业利润', 'type': 'float64'},
                'css_bus_cst': {'desc': '营业成本及附加', 'type': 'float64'},
                'bchm_anl': {'desc': '基准年度', 'type': 'datetime64[ns]'},
                'css_bchm_shr_val': {'desc': '预测基准股本综合值', 'type': 'float64'},

                'date': {'desc': '日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '证券代码', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

            },
        },
    },

    # 它实际是主体表，在aiweglobal;
    'PTY_PFMNOTICE': {
        'source_table': 'AIWESTK.PTY_PFMNOTICE',
        'date': 'anc_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',    # 对应的stk_cd不是主键，主键是公司内部编码，需要判断stk_cd是否有异常值
        'schema': {
            'desc': '股票业绩预告',
            'active': True,
            'date_field': 'date',
            'category': '股票(原表)/行情',
            'rank': 2005006,
            'friendly_name': '股票业绩预告',
            'partition_date': None,
            'primary_key': ['pty_cd', 'anc_dt', 'end_dt', 'instrument'],
            'fields': {
                'pty_cd': {'desc': '公司内部编码', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'start_dt': {'desc': '预告期起始日', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '预告期截止日(报告期)', 'type': 'datetime64[ns]'},
                'bpd_start_dt': {'desc': '预告基期起始日', 'type': 'datetime64[ns]'},
                'bpd_end_dt': {'desc': '预告基期截止日', 'type': 'datetime64[ns]'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'npfm_typ': {'desc': '业绩预告类型', 'type': 'str'},
                'ch_npftn_typ_flr': {'desc': '财汇净利润预告类型下限', 'type': 'str'},
                'ch_npftn_typ_ceil': {'desc': '财汇净利润预告类型上限', 'type': 'str'},
                'npftn_flr': {'desc': '净利润预告下限（万元）', 'type': 'float64'},
                'npftn_ceil': {'desc': '净利润预告上限（万元）', 'type': 'float64'},
                'cha_npftn_flr': {'desc': '净利润预告变动幅度下限（%）', 'type': 'float64'},
                'cha_npftn_ceil': {'desc': '净利润预告变动幅度上限（%）', 'type': 'float64'},
                'npfm_smr': {'desc': '业绩预告摘要', 'type': 'str'},
                'pfm_chg_rsn': {'desc': '业绩变动原因', 'type': 'str'},
                'laty_tbt_npft': {'desc': '上年同期归母净利润', 'type': 'float64'},
                'ch_epsn_typ_flr': {'desc': '财汇每股收益预告类型下限', 'type': 'str'},
                'ch_epsn_typ_ceil': {'desc': '财汇每股收益预告类型上限', 'type': 'str'},
                'eps_flr': {'desc': '每股收益下限（元）', 'type': 'float64'},
                'eps_ceil': {'desc': '每股收益上限（元）', 'type': 'float64'},
                'cha_epsn_flr': {'desc': '每股收益预告变动幅度下限（%）', 'type': 'float64'},
                'cha_epsn_ceil': {'desc': '每股收益预告变动幅度上限（%）', 'type': 'float64'},
                'pbl_num': {'desc': '公布次数', 'type': 'float64'},
                'frs_anc_dt': {'desc': '首次公告日', 'type': 'datetime64[ns]'},
                'is_chg': {'desc': '是否变脸', 'type': 'str'},
                'stk_cd': {'desc': '股票内部编码', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '公告日期', 'type': 'datetime64[ns]'},
            },
        },
    },

}


if __name__ == "__main__":
    print(len(list(TABLES_MAPS.keys())))
    #
    table_lst = [
        'STK_BASICINFO',
        'STK_SPCTREAT', 'STK_INFOCHG', 'USS_BASICINFO', 'CCS_BASICINFO', 'STK_FREECRCSHR', 'STK_SCMEMBERS', 'STK_IPO',
        'STK_EXRIGHT', 'STK_DIVIDEND', 'STK_EODPRICE', 'STK_VALUATION', 'STK_SUSPENSION', 'STK_TA_VOLUME',
        'STK_BLOCKTRADE', 'PTY_PFMNOTICE']
