# 注意：指数的数据都是包含所有指数，因此指数相关的原表instrument都不加后缀，直接用的idx_basicinfo里面的smb字段
TABLES_MAPS = {
    # 基本资料
    # 1.指数基本资料
    'IDX_BASICINFO': {
        'source_table': 'AIWEINDEX.IDX_BASICINFO',
        'date': None,
        'date_format': None,
        'instrument': 'smb',
        'schema': {
            'desc': '指数基本资料',
            'active': True,
            'date_field': None,
            'category': '指数(原表)/基本资料',
            'rank': 3001001,
            'friendly_name': '指数基本资料',
            'partition_date': None,
            'primary_key': ['idx_cd', 'instrument'],
            'fields': {
                'idx_cd': {'desc': '指数内部编码', 'type': 'str'},
                'chn_nm': {'desc': '指数名称', 'type': 'str'},
                'eng_nm': {'desc': '指数英文名', 'type': 'str'},
                'smb': {'desc': '指数代码', 'type': 'str'},
                'chn_sht_nm': {'desc': '指数简称', 'type': 'str'},
                'idx_dscr': {'desc': '指数简介', 'type': 'str'},
                'pbl_dt': {'desc': '指数发布日期', 'type': 'datetime64[ns]'},
                'bas_dt': {'desc': '基准日期', 'type': 'datetime64[ns]'},
                'bas_pnt': {'desc': '基准点数', 'type': 'float64'},
                'idx_mkt': {'desc': '所属MSCI市场', 'type': 'str'},
                'prod_pty_cd': {'desc': '指数编制方编码', 'type': 'str'},
                'prod_pty_nm': {'desc': '指数编制方名称', 'type': 'str'},
                'pbl_pty_cd': {'desc': '指数发布方编码', 'type': 'str'},
                'pbl_pty_nm': {'desc': '指数发布方名称', 'type': 'str'},
                'idx_cls_1st': {'desc': '一级指数类别', 'type': 'str'},
                'idx_cls_2nd': {'desc': '二级指数类别', 'type': 'str'},
                'idx_styl': {'desc': '指数风格', 'type': 'str'},
                'idx_typ_wind': {'desc': '指数类别(WIND)', 'type': 'str'},
                'smpl_spc': {'desc': '选样空间', 'type': 'str'},
                'smpl_mth': {'desc': '选样方法', 'type': 'str'},
                'cpn_num': {'desc': '成份数量(个）', 'type': 'float64'},
                'cpn_adj_prd': {'desc': '成份变动周期', 'type': 'str'},
                'cpn_prc_typ': {'desc': '计算用价格类型', 'type': 'str'},
                'cpn_reve_typ': {'desc': '收益处理方式', 'type': 'str'},
                'wt_mod': {'desc': '加权方式', 'type': 'str'},
                'wt_typ': {'desc': '权重类型', 'type': 'str'},
                'idx_calc_dscr': {'desc': '指数计算说明', 'type': 'str'},
                'idx_adj_dscr': {'desc': '指数修正调整说明', 'type': 'str'},
                'cur_sgn': {'desc': '当前标记', 'type': 'str'},
                'tmn_dt': {'desc': '停用日期', 'type': 'datetime64[ns]'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '指数代码(未加后缀)', 'type': 'str'},
            },
        },
    },
    # 行情
    # 1.指数行情表
    'IDX_EODVALUE': {
        'source_table': 'AIWEINDEX.IDX_EODVALUE',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '指数行情',
            'active': True,
            'date_field': 'date',
            'category': '指数(原表)/行情',
            'rank': 3002001,
            'friendly_name': '指数行情',
            'partition_date': 'Y',
            'primary_key': ['idx_cd', 'trd_dt', 'instrument'],
            'fields': {
                'idx_cd': {'desc': '指数内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'pre_cls_prc': {'desc': '昨收盘价(点)', 'type': 'float64'},
                'opn_prc': {'desc': '开盘价(点)', 'type': 'float64'},
                'hi_prc': {'desc': '最高价(点)', 'type': 'float64'},
                'lo_prc': {'desc': '最低价(点)', 'type': 'float64'},
                'cls_prc': {'desc': '收盘价(点)', 'type': 'float64'},
                'chg_prc': {'desc': '涨跌(点)', 'type': 'float64'},
                'pct_chg': {'desc': '涨跌幅(%)', 'type': 'float64'},
                'vol': {'desc': '成交量(手)', 'type': 'float64'},
                'amt': {'desc': '成交金额(千元)', 'type': 'float64'},
                'idx_pe': {'desc': '指数市盈率', 'type': 'float64'},
                'idx_pb': {'desc': '指数市净率', 'type': 'float64'},
                'astk_crc_mkv': {'desc': 'A股流通市值(万元)', 'type': 'float64'},
                'tot_mkv': {'desc': '总市值(万元)', 'type': 'float64'},
                'stl_prc': {'desc': '结算价（点）', 'type': 'float64'},
                'opn_int': {'desc': '持仓量（手）', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '指数代码', 'type': 'str'},
            },
        },
    },
    'IDX_EODVALUE_CNBD': {
        'source_table': 'AIWEINDEX.IDX_EODVALUE_CNBD',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '中债指数行情衍生指标',
            'active': True,
            'date_field': 'date',
            'category': '指数(原表)/行情',
            'rank': 3002002,
            'friendly_name': '中债指数行情衍生指标',
            'partition_date': 'Y',
            'primary_key': ['idx_cd', 'trd_dt', 'instrument'],
            'fields': {
                'idx_cd': {'desc': '指数内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'cls_prc': {'desc': '收盘价(点)', 'type': 'float64'},
                'net_cls_prc': {'desc': '净价收盘价(点)', 'type': 'float64'},
                'wlth_cls_prc': {'desc': '财富收盘价(点)', 'type': 'float64'},
                'avg_prc': {'desc': '平均价(点)', 'type': 'float64'},
                'avg_mkv_dur': {'desc': '平均市值法久期', 'type': 'float64'},
                'avg_mkv_mdf_dur': {'desc': '平均市值法修正久期', 'type': 'float64'},
                'avg_csh_dur': {'desc': '平均现金流法久期', 'type': 'float64'},
                'avg_mkv_cvx': {'desc': '平均市值法凸性', 'type': 'float64'},
                'avg_csh_cvx': {'desc': '平均现金流法凸性', 'type': 'float64'},
                'avg_due_yld': {'desc': '平均到期收益率(%)', 'type': 'float64'},
                'avg_mkv_due_yld': {'desc': '平均市值法到期收益率(%)', 'type': 'float64'},
                'avg_csh_due_yld': {'desc': '平均现金流法到期收益率(%)', 'type': 'float64'},
                'avg_dvd_rat': {'desc': '平均派息率(%)', 'type': 'float64'},
                'avg_bp_val': {'desc': '平均基点价值(元)', 'type': 'float64'},
                'avg_rmn_year': {'desc': '平均剩余年限(年)', 'type': 'float64'},
                'avg_rmn_day': {'desc': '平均剩余天数(天)', 'type': 'float64'},
                'cur_scr_stl_amt': {'desc': '现券结算量(亿元)', 'type': 'float64'},
                'tot_mkv': {'desc': '指数总市值(亿元)', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '指数代码', 'type': 'str'},
            },
        },
    },

    # 成分权重
    # 1.指数成分表
    'IDX_COMPONENTS': {
        'source_table': 'AIWEINDEX.IDX_COMPONENTS',
        'date': 'sel_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '指数成分',
            'active': True,
            'date_field': 'date',
            'category': '指数(原表)/成分权重',
            'rank': 3003001,
            'friendly_name': '指数成分',
            'partition_date': 'Y',
            'primary_key': ['cpn_cd', 'idx_cd', 'sel_dt', 'instrument'],
            'fields': {
                'idx_cd': {'desc': '指数内部编码', 'type': 'str'},
                'cpn_cd': {'desc': '成份内部编码', 'type': 'str'},
                'sel_dt': {'desc': '入选日期', 'type': 'datetime64[ns]'},
                'out_dt': {'desc': '剔除日期', 'type': 'datetime64[ns]'},
                'cur_sgn': {'desc': '当前标记', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '入选日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '指数代码(未加后缀)', 'type': 'str'},
            },
        },
    },
    # 2.股票指数权重表
    'IDX_WT_STK': {
        'source_table': 'AIWEINDEX.IDX_WT_STK',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '股票指数权重表',
            'active': True,
            'date_field': 'date',
            'category': '指数(原表)/成分权重',
            'rank': 3003002,
            'friendly_name': '股票指数权重表',
            'partition_date': 'Y',
            'primary_key': ['cpn_cd', 'idx_cd', 'trd_dt', 'instrument'],
            'fields': {
                'idx_cd': {'desc': '指数内部编码', 'type': 'str'},
                'cpn_cd': {'desc': '成份内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'wt': {'desc': '权重(%)', 'type': 'float64'},
                'tot_shr': {'desc': '总股本(股)', 'type': 'float64'},
                'crc_shr_rat': {'desc': '自由流通比例(%)', 'type': 'float64'},
                'crc_shr': {'desc': '自由流通股本(股)', 'type': 'float64'},
                'shr_calc': {'desc': '计算用股本(股)', 'type': 'float64'},
                'tot_mkv': {'desc': '总市值', 'type': 'float64'},
                'crc_mkv': {'desc': '自由流通市值', 'type': 'float64'},
                'mkv_calc': {'desc': '计算用市值', 'type': 'float64'},
                'wt_fct': {'desc': '权重因子', 'type': 'float64'},
                'cls_prc': {'desc': '收盘价(元)', 'type': 'float64'},
                'opn_adj': {'desc': '开盘参考价(元)', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '指数代码(未加后缀)', 'type': 'str'},
            },
        },
    },
    'IDX_WT_CNBD': {
        'source_table': 'AIWEINDEX.IDX_WT_CNBD',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '中债登指数权重表',
            'active': True,
            'date_field': 'date',
            'category': '指数(原表)/成分权重',
            'rank': 3003003,
            'friendly_name': '中债登指数权重表',
            'partition_date': 'M',
            'primary_key': ['cpn_cd', 'idx_cd', 'trd_dt', 'instrument'],
            'fields': {
                'idx_cd': {'desc': '指数内部编码', 'type': 'str'},
                'cpn_cd': {'desc': '成份内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'wt': {'desc': '权重(%)', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '指数代码(未加后缀)', 'type': 'str'},
            },
        },
    },
}

if __name__ == "__main__":
    print(list(TABLES_MAPS.keys()))
