TABLES_MAPS = {
    # 5003系列 5001/5002xxx留给前面的基本信息
    'FI_CURV_CNBD': {
        'source_table': 'AIWEBOND.FI_CURV_CNBD',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'curv_cd',
        'schema': {
            'desc': '中债登收益率曲线表',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/收益率曲线',
            'rank': 5009001,
            'friendly_name': '中债登收益率曲线表',
            'partition_date': 'M',
            'primary_key': ['curv_cd', 'fwd_trm_n', 'std_trm', 'trd_dt'],
            'fields': {
                'curv_cd': {'desc': '曲线代码', 'type': 'str'},
                'curv_nm': {'desc': '曲线名称', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'curv_typ': {'desc': '曲线类型', 'type': 'str'},
                'std_trm': {'desc': '标准期限(年)', 'type': 'str'},
                'fwd_trm_n': {'desc': '远期期限(年)', 'type': 'str'},
                'yld': {'desc': '收益率(%)', 'type': 'float64'},
                'val_dt_bas_ir': {'desc': '估值日基础利率（%）', 'type': 'float64'},
                'yld_val': {'desc': '收益率曲线数值（%）', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '曲线代码', 'type': 'str'},
            },
        },
    },
    'FI_CURV_SAMPLE': {
        'source_table': 'AIWEBOND.FI_CURV_SAMPLE',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'curv_cd',
        'schema': {
            'desc': '收益率曲线样本券',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/收益率曲线',
            'rank': 5009002,
            'friendly_name': '收益率曲线样本券',
            'partition_date': 'Y',
            'primary_key': ['trd_dt', 'curv_cd', 'bnd_cd'],
            'fields': {
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'curv_cd': {'desc': '曲线代码', 'type': 'str'},
                'curv_nm': {'desc': '曲线名称', 'type': 'str'},
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'impl_rat': {'desc': '隐含评级', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '曲线代码', 'type': 'str'},
            },
        },
    },
    'FI_BASICINFO': {
        'source_table': 'AIWEBOND.FI_BASICINFO',
        'date': None,
        'date_format': None,
        'instrument': 'bnd_smb',
        'schema': {
            'desc': '债券基本资料',
            'active': True,
            'date_field': None,
            'category': '固定收益（原表）/基本资料',
            'rank': 5001001,
            'friendly_name': '债券基本资料',
            'partition_date': None,
            'primary_key': ['bnd_cd', 'instrument'],
            'fields': {
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'exg_cd': {'desc': '交易所编码', 'type': 'str'},
                'bnd_smb': {'desc': '债券代码', 'type': 'str'},
                'stk_smb': {'desc': '正股代码', 'type': 'str'},
                'chn_nm': {'desc': '债券全称', 'type': 'str'},
                'chn_sht_nm': {'desc': '债券简称', 'type': 'str'},
                'py_nm': {'desc': '拼音简称', 'type': 'str'},
                'bnd_typ': {'desc': '债券类别', 'type': 'str'},
                'pty_cd': {'desc': '发行人代码', 'type': 'str'},
                'pty_nm': {'desc': '发行人名称', 'type': 'str'},
                'pty_typ': {'desc': '发行人类别', 'type': 'str'},
                'bnd_trm_year': {'desc': '债券期限(年)', 'type': 'float64'},
                'bnd_trm_day': {'desc': '债券期限(天)', 'type': 'float64'},
                #'trm_emb_opt': {'desc': '含权期限', 'type': 'str'},
                'bnd_nbr': {'desc': '债券期次', 'type': 'str'},
                'bnd_form': {'desc': '债券形态', 'type': 'str'},
                'ras_mod': {'desc': '募集方式', 'type': 'str'},
                'cmb_ras_mod': {'desc': '招行募集方式', 'type': 'str'},
                'cpn_typ': {'desc': '付息方式', 'type': 'str'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'par_val_iss': {'desc': '发行面值', 'type': 'float64'},
                'par_val_lat': {'desc': '最新面值', 'type': 'float64'},
                'iss_prc': {'desc': '发行价格', 'type': 'float64'},
                'par_ann_ir': {'desc': '发行时票面利率', 'type': 'float64'},
                'cur_amt': {'desc': '当前规模(亿元)', 'type': 'float64'},
                'val_dt': {'desc': '计息起始日', 'type': 'datetime64[ns]'},
                'stop_dt': {'desc': '计息截止日', 'type': 'datetime64[ns]'},
                'iss_start_dt': {'desc': '发行起始日', 'type': 'datetime64[ns]'},
                'iss_end_dt': {'desc': '发行截止日', 'type': 'datetime64[ns]'},
                'lst_dt': {'desc': '上市日期', 'type': 'datetime64[ns]'},
                'xpc_due_dt': {'desc': '预估到期日期', 'type': 'datetime64[ns]'},
                'act_due_dt': {'desc': '实际到期日期', 'type': 'datetime64[ns]'},
                'act_csh_dt': {'desc': '实际兑付日期', 'type': 'datetime64[ns]'},
                'delst_dt': {'desc': '退市日期', 'type': 'datetime64[ns]'},
                'pay_day_year': {'desc': '年付息日', 'type': 'str'},
                'ir_typ': {'desc': '利率类型', 'type': 'str'},
                'cmb_ir_typ': {'desc': '招行利率类型', 'type': 'str'},
                'pay_freq': {'desc': '付息周期', 'type': 'str'},
                'intr_rule': {'desc': '计息规则', 'type': 'str'},
                'intr_rul_ch': {'desc': '计息规则_财汇', 'type': 'str'},
                'intr_rul_wind': {'desc': '计息规则_万得', 'type': 'str'},
                'intr_rul_cb': {'desc': '计息规则_中债登', 'type': 'str'},
                'intr_rul_cm': {'desc': '计息规则_外汇交易中心', 'type': 'str'},
                'prgr_mod': {'desc': '递进利率递进方式', 'type': 'str'},
                'prgr_mrgn': {'desc': '递进利率递进利差', 'type': 'float64'},
                'flt_bm': {'desc': '浮息债基准利率', 'type': 'str'},
                'ir_cd': {'desc': '浮息债基准利率内码', 'type': 'str'},
                'ir_trm': {'desc': '基准利率中债收益率期限(年)', 'type': 'float64'},
                'ir_ave_prd': {'desc': '基准利率均值时间窗口(天)', 'type': 'float64'},
                'flt_ir_sprd': {'desc': '浮息债利差', 'type': 'float64'},
                'intr_adj_mod': {'desc': '浮息债调息时间类型', 'type': 'str'},
                'ann_ir_flr': {'desc': '债券保底利率', 'type': 'float64'},
                'due_compen_ir': {'desc': '到期补偿利率', 'type': 'float64'},
                'intr_fml': {'desc': '付息周期小于一年计息方法', 'type': 'str'},
                'gua_pty_nm': {'desc': '担保人名称', 'type': 'str'},
                'gua_mod': {'desc': '担保方式', 'type': 'str'},
                'frs_rat': {'desc': '首次债券评级', 'type': 'str'},
                'is_failure': {'desc': '是否发行失败', 'type': 'str'},
                'is_crs_mkt': {'desc': '是否跨市场', 'type': 'str'},
                'pay_dscr': {'desc': '利息支付方式说明', 'type': 'str'},
                'intr_claus': {'desc': '利息条款描述', 'type': 'str'},
                'trd_mod': {'desc': '交易方式', 'type': 'str'},
                'set_way': {'desc': '是否非担保交收', 'type': 'str'},
                'is_tmp_cd': {'desc': '是否临时券', 'type': 'str'},
                'iss_plc': {'desc': '发行地', 'type': 'str'},
                'due_dt': {'desc': '到期日期', 'type': 'datetime64[ns]'},
                'csh_dt': {'desc': '兑付日期', 'type': 'datetime64[ns]'},
                'pay_intr_day_norm': {'desc': '付息日准则', 'type': 'str'},
                #'pyf_ord': {'desc': '偿付顺序', 'type': 'str'},
                'remark': {'desc': '备注', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'FI_CLASSIFICATION': {
        'source_table': 'AIWEBOND.FI_CLASSIFICATION',
        'date': None,
        'date_format': None,
        'instrument': 'bnd_smb',
        'schema': {
            'desc': '债券分类表',
            'active': True,
            'date_field': None,
            'category': '固定收益（原表）/基本资料',
            'rank': 5001002,
            'friendly_name': '债券分类表',
            'partition_date': None,
            'primary_key': ['bnd_cd', 'cls_sys_cd','cls_cd_1st','instrument'],
            'fields': {
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'cls_sys_cd': {'desc': '分类口径代码', 'type': 'str'},
                'cls_cd_1st': {'desc': '一级分类代码', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'FI_CNVBONDINFO': {
        'source_table': 'AIWEBOND.FI_CNVBONDINFO',
        'date': None,
        'date_format': None,
        'instrument': 'bnd_smb',
        'schema': {
            'desc': '可转债信息表',
            'active': True,
            'date_field': None,
            'category': '固定收益（原表）/基本资料',
            'rank': 5001003,
            'friendly_name': '可转债信息表',
            'partition_date': None,
            'primary_key': ['bnd_cd', 'instrument'],
            'fields': {
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'evt_typ': {'desc': '事件类型', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'prps_anc_dt': {'desc': '预案公告日', 'type': 'datetime64[ns]'},
                'gm_anc_dt': {'desc': '股东大会公告日', 'type': 'datetime64[ns]'},
                'iec_pass_anc_dt': {'desc': '发审委通过公告日', 'type': 'datetime64[ns]'},
                'csrc_aprv_anc_dt': {'desc': '证监会核准公告日', 'type': 'datetime64[ns]'},
                'iss_anc_dt': {'desc': '发行公告日', 'type': 'datetime64[ns]'},
                'uw_start_dt': {'desc': '承销期起始日', 'type': 'datetime64[ns]'},
                'uw_end_dt': {'desc': '承销期截止日', 'type': 'datetime64[ns]'},
                'iss_rsl_anc_dt': {'desc': '发行结果公告日', 'type': 'datetime64[ns]'},
                'lst_anc_dt': {'desc': '上市公告日', 'type': 'datetime64[ns]'},
                'ndwrt_amt': {'desc': '余额包销数量(万元)', 'type': 'float64'},
                'onl_iss_dt': {'desc': '网上发行日期', 'type': 'datetime64[ns]'},
                'onl_apl_nm': {'desc': '网上申购名称', 'type': 'str'},
                'onl_apl_prc': {'desc': '网上申购价格(元)', 'type': 'float64'},
                'onl_apl_pay_dt': {'desc': '网上申购缴款日', 'type': 'datetime64[ns]'},
                'onl_vld_apl_num': {'desc': '网上有效申购户数(不含优先配售)(户)', 'type': 'float64'},
                'onl_vld_apl_amt': {'desc': '网上有效申购金额(不含优先配售)(元)', 'type': 'float64'},
                'onl_act_amt': {'desc': '网上实际获配金额(元)', 'type': 'float64'},
                'onl_win_rat_anc_dt': {'desc': '网上中签率公告日', 'type': 'datetime64[ns]'},
                'onl_win_rsl_anc_dt': {'desc': '网上中签结果公告日', 'type': 'datetime64[ns]'},
                'onl_win_rat': {'desc': '网上中签率(不含优先配售)(%)', 'type': 'float64'},
                'onl_win_nbr_vol': {'desc': '网上中签号码数量(个)', 'type': 'float64'},
                'onl_win_nbr': {'desc': '网上中签号码', 'type': 'str'},
                'onl_apl_tms': {'desc': '网上发行超额认购倍数(不含优先配售)', 'type': 'float64'},
                'onl_iss_vol': {'desc': '网上发行数量(不含优先配售)(张)', 'type': 'float64'},
                'ofl_iss_dt': {'desc': '网下发行日期', 'type': 'datetime64[ns]'},
                'ofl_vld_apl_num': {'desc': '网下有效申购户数(不含优先配售)(户)', 'type': 'float64'},
                'ofl_vld_apl_amt': {'desc': '网下有效申购金额(不含优先配售)(元)', 'type': 'float64'},
                'ofl_act_amt': {'desc': '网下实际获配金额(元)', 'type': 'float64'},
                'ofl_pay_rat': {'desc': '网下缴纳申购定金比例(%)', 'type': 'float64'},
                'ofl_win_rat': {'desc': '网下中签率(不含优先配售)(%)', 'type': 'float64'},
                'ofl_iss_vol': {'desc': '网下发行数量(不含优先配售)(张)', 'type': 'float64'},
                'ofl_pla_vol': {'desc': '网下配售数量(张)', 'type': 'float64'},
                'shh_pla_reg_dt': {'desc': '老股东配售股权登记日', 'type': 'datetime64[ns]'},
                'shh_pla_dt': {'desc': '老股东配售日期', 'type': 'datetime64[ns]'},
                'shh_pla_pay_dt': {'desc': '老股东配售缴款日', 'type': 'datetime64[ns]'},
                'shh_pla_smb': {'desc': '老股东配售代码', 'type': 'str'},
                'shh_pla_nm': {'desc': '老股东配售名称', 'type': 'str'},
                'shh_pla_prc': {'desc': '老股东配售价格(元)', 'type': 'float64'},
                'shh_pla_rat': {'desc': '老股东配售比例(%)', 'type': 'float64'},
                'shh_pla_amt': {'desc': '老股东配售总额(万元)', 'type': 'float64'},
                'shh_pla_vol': {'desc': '老股东配售数量(张)', 'type': 'float64'},
                'shh_pla_num': {'desc': '老股东配售户数(户)', 'type': 'float64'},
                'shh_vld_apl_vol': {'desc': '老股东配售有效申购张数(张)', 'type': 'float64'},
                'shh_vld_apl_num': {'desc': '老股东有效申购户数(户)', 'type': 'float64'},
                'cnv_stk_cd': {'desc': '转股内码', 'type': 'str'},
                'cnv_dcl_smb': {'desc': '转股申报代码', 'type': 'str'},
                'cnv_start_dt': {'desc': '转换起始日', 'type': 'datetime64[ns]'},
                'cnv_end_dt': {'desc': '转换结束日', 'type': 'datetime64[ns]'},
                'ncnv_dur': {'desc': '不可转股时长(月)', 'type': 'str'},
                'ini_cnv_prc': {'desc': '初始转换价格(元)', 'type': 'float64'},
                'ini_cnv_rat': {'desc': '初始转换比例', 'type': 'float64'},
                'cnv_prem_rat': {'desc': '初始转股价溢价比例(%)', 'type': 'float64'},
                'cnv_prc_adj_std': {'desc': '转股价格调整标准', 'type': 'str'},
                'cnv_prc_cfm_std': {'desc': '转股价格确定标准', 'type': 'str'},
                'cnv_rmn_prcs': {'desc': '转换余股处理', 'type': 'str'},
                'pay_dvd_aft_cnv': {'desc': '转股后的股利分配', 'type': 'str'},
                'is_cnv_cncl': {'desc': '转股是否允许撤单', 'type': 'str'},
                'is_mnd_cnv': {'desc': '是否到期无条件强制性转股', 'type': 'str'},
                'rvis_start_dt': {'desc': '转股价格修正起始日', 'type': 'datetime64[ns]'},
                'rvis_end_dt': {'desc': '转股价格修正结束日', 'type': 'datetime64[ns]'},
                'is_down_rvis': {'desc': '是否可向下修正转股价', 'type': 'str'},
                'rvis_cnt_day': {'desc': '转股价格修正触发计算天数(天)', 'type': 'str'},
                'rvis_trg_day': {'desc': '转股价格修正触发天数(天)', 'type': 'str'},
                'rvis_trg_rat': {'desc': '转股价格修正触发比例(%)', 'type': 'float64'},
                'rvis_claus': {'desc': '转股价格修正条款', 'type': 'str'},
                'spc_down_rvis_claus': {'desc': '特别向下修正条款', 'type': 'str'},
                'rvis_flr_claus': {'desc': '转股价格修正底线条款', 'type': 'str'},
                'is_avg_prc': {'desc': '参考价格是否为算术平均价', 'type': 'str'},
                'rvis_frq_lmt': {'desc': '转股价格修正频率限制', 'type': 'str'},
                'rdm_start_dt': {'desc': '赎回起始日', 'type': 'datetime64[ns]'},
                'rdm_end_dt': {'desc': '赎回结束日', 'type': 'datetime64[ns]'},
                'rdm_claus': {'desc': '赎回条款', 'type': 'str'},
                'rdm_prc': {'desc': '赎回价格(元)', 'type': 'float64'},
                'rdm_prc_cfm_mod': {'desc': '赎回价格确定方式', 'type': 'str'},
                'rdm_frq_lmt': {'desc': '赎回频率限制', 'type': 'str'},
                'nrdm_start_dt': {'desc': '锁定赎回起始日', 'type': 'datetime64[ns]'},
                'nrdm_end_dt': {'desc': '锁定赎回截止日', 'type': 'datetime64[ns]'},
                'nrdm_dur': {'desc': '不可赎回时长(月)', 'type': 'str'},
                'rdm_cnt_day': {'desc': '有条件赎回触发计算天数(天)', 'type': 'str'},
                'rdm_trg_day': {'desc': '有条件赎回触发天数(天)', 'type': 'str'},
                'rdm_trg_rat': {'desc': '有条件赎回触发比例(%)', 'type': 'float64'},
                'is_incl_int_rdm': {'desc': '有条件赎回价格是否包含利息', 'type': 'str'},
                'due_rdm_claus': {'desc': '到期赎回条款', 'type': 'str'},
                'due_rdm_prc': {'desc': '到期赎回价格(元)', 'type': 'float64'},
                'is_incl_int_due': {'desc': '到期赎回价格是否包含利息', 'type': 'str'},
                'put_start_dt': {'desc': '回售起始日', 'type': 'datetime64[ns]'},
                'put_end_dt': {'desc': '回售结束日', 'type': 'datetime64[ns]'},
                'put_claus': {'desc': '回售条款', 'type': 'str'},
                'put_prc': {'desc': '回售价格(元)', 'type': 'float64'},
                'put_prc_cfm_mod': {'desc': '回售价格确定方式', 'type': 'str'},
                'put_frq_lmt': {'desc': '回售频率限制', 'type': 'str'},
                'nput_start_dt': {'desc': '锁定回售起始日', 'type': 'datetime64[ns]'},
                'nput_end_dt': {'desc': '锁定回售截止日', 'type': 'datetime64[ns]'},
                'nput_dur': {'desc': '不可回售时长(月)', 'type': 'str'},
                'put_acm_day': {'desc': '有条件回售触发计算天数(天)', 'type': 'str'},
                'put_trg_day': {'desc': '有条件回售触发天数(天)', 'type': 'str'},
                'put_trg_rat': {'desc': '有条件回售触发比例(%)', 'type': 'float64'},
                'is_incl_int_put': {'desc': '有条件回售价格是否包含利息', 'type': 'str'},
                'put_prc_adt': {'desc': '附加回售价格(元)', 'type': 'float64'},
                'cfm_mod_adt': {'desc': '附加回售价格确定方式', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'FI_VAL_CNBD': {
        'source_table': 'AIWEBOND.FI_VAL_CNBD',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'bnd_smb',
        'schema': {
            'desc': '中债估值',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/估值',
            'rank': 5008001,
            'friendly_name': '中债估值',
            'partition_date': 'M',
            'primary_key': ['bnd_cd', 'trd_dt','dat_src','is_rcm','instrument'],
            'fields': {
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'dat_src': {'desc': '数据来源', 'type': 'str'},
                'is_rcm': {'desc': '是否推荐', 'type': 'str'},
                'val_typ': {'desc': '估值类型', 'type': 'str'},
                'net_prc': {'desc': '净价(元)', 'type': 'float64'},
                'ful_prc': {'desc': '全价(元)', 'type': 'float64'},
                'acr_int': {'desc': '应计利息(元)', 'type': 'float64'},
                'rmn_year': {'desc': '剩余年限(年)', 'type': 'float64'},
                'yld': {'desc': '收益率(%)', 'type': 'float64'},
                #'dur': {'desc': '久期', 'type': 'float64'},
                'mdf_dur': {'desc': '修正久期', 'type': 'float64'},
                'cvx': {'desc': '凸性', 'type': 'float64'},
                'bp_val': {'desc': '基点价值', 'type': 'float64'},
                'ir_dur': {'desc': '利率久期', 'type': 'float64'},
                'ir_cvx': {'desc': '利率凸性', 'type': 'float64'},
                'sprd_dur': {'desc': '利差久期', 'type': 'float64'},
                'sprd_cvx': {'desc': '利差凸性', 'type': 'float64'},
                'day_ful_prc': {'desc': '日终全价(元)', 'type': 'float64'},
                'day_acr_int': {'desc': '日终应计利息(元)', 'type': 'float64'},
                'rmn_prcp': {'desc': '剩余本金(元)', 'type': 'float64'},
                'pnt': {'desc': '点差', 'type': 'float64'},
                'crc_exst_vol': {'desc': '可流通存量', 'type': 'float64'},
                'xcs_par_ir': {'desc': '行权后票面利率(估算)', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'FI_CASHFLOW': {
        'source_table': 'AIWEBOND.FI_CASHFLOW',
        'date': 'csh_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'bnd_smb',
        'schema': {
            'desc': '债券现金流表',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/付息兑付',
            'rank': 5008001,
            'friendly_name': '债券现金流表',
            'partition_date': None,
            'primary_key': ['bnd_cd', 'is_act_cf','csh_dt','instrument'],
            'fields': {
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'is_act_cf': {'desc': '是否实际现金流', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'intr_start_dt': {'desc': '计息起始日', 'type': 'datetime64[ns]'},
                'intr_end_dt': {'desc': '计息截止日', 'type': 'datetime64[ns]'},
                'reg_dt': {'desc': '债权登记日', 'type': 'datetime64[ns]'},
                'xrt_dt': {'desc': '除权除息日', 'type': 'datetime64[ns]'},
                'csh_dt': {'desc': '兑付付息日', 'type': 'datetime64[ns]'},
                'par_ir': {'desc': '票面利率(%)', 'type': 'float64'},
                'cf': {'desc': '税前现金流(元)', 'type': 'float64'},
                'pay_intr': {'desc': '偿还利息(元)', 'type': 'float64'},
                'prcp_csh': {'desc': '偿付本金(元)', 'type': 'float64'},
                'csh_amt_fir': {'desc': '偿还前期初金额(元)', 'type': 'float64'},
                'csh_amt_aft': {'desc': '偿还后期末金额(元)', 'type': 'float64'},
                'ccy_cd': {'desc': '货币代码', 'type': 'str'},
                'cf_typ': {'desc': '现金流类型', 'type': 'str'},
                'prcp_csh_mod': {'desc': '本金偿还方式', 'type': 'str'},
                'is_due_pay': {'desc': '是否到期支付', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '兑付付息日', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'FI_IMPLRATING': {
        'source_table': 'AIWEBOND.FI_IMPLRATING',
        'date': 'rat_eft_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'bnd_smb',
        'schema': {
            'desc': '债券隐含评级',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/债券评级',
            'rank': 5011001,
            'friendly_name': '债券隐含评级',
            'partition_date': None,
            'primary_key': ['bnd_cd', 'rat_eft_dt','rat_org','instrument'],
            'fields': {
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'anc_dt': {'desc': '评级发布日期', 'type': 'datetime64[ns]'},
                'rat_eft_dt': {'desc': '评级生效日', 'type': 'datetime64[ns]'},
                'rat_mod': {'desc': '评级方式', 'type': 'str'},
                'crd_rat': {'desc': '信用评级', 'type': 'str'},
                'rat_org': {'desc': '评级机构', 'type': 'str'},
                'rat_chg_dir': {'desc': '评级变动方向', 'type': 'str'},
                'curv_cd': {'desc': '对应收益率曲线编码', 'type': 'str'},
                'curv_nm': {'desc': '对应收益率曲线名称', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '评级生效日', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'FI_DRVIND': {
        'source_table': 'AIWEBOND.FI_DRVIND',
        'date': 'trd_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'bnd_smb',
        'schema': {
            'desc': '债券衍生指标',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/债券衍生',
            'rank': 5012001,
            'friendly_name': '债券衍生指标',
            'partition_date': 'M',
            'primary_key': ['bnd_cd', 'trd_dt','instrument'],
            'fields': {
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'dur': {'desc': '久期', 'type': 'float64'},
                'mdf_dur': {'desc': '修正久期', 'type': 'float64'},
                'bas_dur': {'desc': '基准久期', 'type': 'float64'},
                'sprd_dur': {'desc': '利差久期', 'type': 'float64'},
                'cvx': {'desc': '凸性', 'type': 'float64'},
                'intr_acr_day': {'desc': '已计息时间', 'type': 'float64'},
                'acr_intr': {'desc': '应计利息', 'type': 'float64'},
                'rdm_yld': {'desc': '赎回收益率(%)', 'type': 'float64'},
                'put_yld': {'desc': '回售收益率(%)', 'type': 'float64'},
                'rmn_trm': {'desc': '剩余期限(年)', 'type': 'float64'},
                'due_yld': {'desc': '到期收益率(%)', 'type': 'float64'},
                'wt_rmn_trm': {'desc': '加权剩余期限(年)', 'type': 'float64'},
                'cls_ytm_simp': {'desc': '收盘价到期收益率(单利)(%)', 'type': 'float64'},
                'cls_ytm_cmpd': {'desc': '收盘价到期收益率(复利)(%)', 'type': 'float64'},
                'cls_ytm_be': {'desc': '收盘价到期收益率(复利BE)(%)', 'type': 'float64'},
                'opn_ytm': {'desc': '开盘价到期收益率(%)', 'type': 'float64'},
                'hi_ytm': {'desc': '最高价到期收益率(%)', 'type': 'float64'},
                'lo_ytm': {'desc': '最低价到期收益率(%)', 'type': 'float64'},
                'bchm_cvx': {'desc': '基准凸性', 'type': 'float64'},
                'frnt_cls_yld': {'desc': '前台收盘收益率', 'type': 'float64'},
                'frnt_wt_yld': {'desc': '前台加权收益率', 'type': 'float64'},
                'cls_yld_cntr_bnk': {'desc': '收盘收益率_央行规则', 'type': 'float64'},
                'cls_yld_simp': {'desc': '收盘收益率_单利', 'type': 'float64'},
                'cls_yld_cmpd': {'desc': '收盘收益率_复利', 'type': 'float64'},
                'cls_yld_be': {'desc': '收盘收益率BE_复利', 'type': 'float64'},
                'rdm_yld_cntr_bnk': {'desc': '赎回收益率_央行规则', 'type': 'float64'},
                'rdm_yld_cmpd': {'desc': '赎回收益率_复利', 'type': 'float64'},
                'rdm_yld_be': {'desc': '赎回收益率_复利BE', 'type': 'float64'},
                'rdm_yld_simp': {'desc': '赎回收益率_单利', 'type': 'float64'},
                'put_yld_cntr_bnk': {'desc': '回售收益率_央行规则', 'type': 'float64'},
                'put_yld_cmpd': {'desc': '回售收益率_复利', 'type': 'float64'},
                'put_yld_be': {'desc': '回售收益率_复利BE', 'type': 'float64'},
                'put_yld_simp': {'desc': '回售收益率_单利', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'FI_RATING': {
        'source_table': 'AIWEBOND.FI_RATING',
        'date': 'rat_eft_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'bnd_smb',
        'schema': {
            'desc': '债券信用评级',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/债券评级',
            'rank': 5011001,
            'friendly_name': '债券信用评级',
            'partition_date': None,
            'primary_key': ['bnd_cd', 'rat_eft_dt','instrument'],
            'fields': {
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'anc_dt': {'desc': '评级发布日期', 'type': 'datetime64[ns]'},
                'rat_eft_dt': {'desc': '评级生效日', 'type': 'datetime64[ns]'},
                'rat_nvld_dt': {'desc': '评级失效日', 'type': 'datetime64[ns]'},
                'rat_mod': {'desc': '评级方式', 'type': 'str'},
                'rat_typ': {'desc': '评级类型', 'type': 'str'},
                'crd_rat': {'desc': '信用评级', 'type': 'str'},
                'cbcd': {'desc': '对应央行标准代码', 'type': 'str'},
                'rat_org': {'desc': '评级机构', 'type': 'str'},
                'rat_chg_dir': {'desc': '评级变动方向', 'type': 'str'},
                'rat_xpc': {'desc': '评级展望', 'type': 'str'},
                'chg_rsn': {'desc': '变动原因', 'type': 'str'},
                'remark': {'desc': '备注', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '评级生效日', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'FI_DFTINFO': {
        'source_table': 'AIWEBOND.FI_DFTINFO',
        'date': 'dft_dt',
        'date_format':'%Y-%m-%d' ,
        'instrument': 'bnd_smb',
        'schema': {
            'desc': '债券违约信息表',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/担保违约',
            'rank': 5015001,
            'friendly_name': '债券违约信息表',
            'partition_date': None,
            'primary_key': ['bnd_cd', 'dft_dt','instrument'],
            'fields': {
                'bnd_cd': {'desc': '债券内部编码', 'type': 'str'},
                'frs_anc_dt': {'desc': '首次公告日期', 'type': 'datetime64[ns]'},
                'late_anc_dt': {'desc': '最新更新日期', 'type': 'datetime64[ns]'},
                'late_pay_dt': {'desc': '最新支付日期', 'type': 'datetime64[ns]'},
                'thrt_dt': {'desc': '理论支付日', 'type': 'datetime64[ns]'},
                'dft_dt': {'desc': '违约发生日', 'type': 'datetime64[ns]'},
                'dft_typ': {'desc': '违约类型代码', 'type': 'str'},
                'dft_dt_amt': {'desc': '违约日债券余额(元)', 'type': 'float64'},
                'dft_dt_amt1': {'desc': '违约日债券余额(日终)(元)', 'type': 'float64'},
                'dft_dt_prcp_hun': {'desc': '违约发生日百元应兑付本金(元)', 'type': 'float64'},
                'dft_dt_int_hun': {'desc': '违约发生日百元应兑付利息(元)', 'type': 'float64'},
                'dft_dt_prcp_int_hun': {'desc': '违约发生日百元应兑付本息(元)', 'type': 'float64'},
                'dft_dt_prcp_hun_actl': {'desc': '违约发生日实际百元兑付本金(元)', 'type': 'float64'},
                'dft_dt_int_hun_actl': {'desc': '违约发生日实际百元兑付利息(元)', 'type': 'float64'},
                'dft_dt_prcp_int_hun_actl': {'desc': '违约发生日实际百元兑付本息(元)', 'type': 'float64'},
                'pay_prcp': {'desc': '应付本金(元)', 'type': 'float64'},
                'pay_intr': {'desc': '应付利息(元)', 'type': 'float64'},
                'sel_bck': {'desc': '应付回售款(元)', 'type': 'float64'},
                'prcp_int_tot': {'desc': '应付本息及回售款(元)', 'type': 'float64'},
                'prcp_actl': {'desc': '实付本金(元)', 'type': 'float64'},
                'int_actl': {'desc': '实付利息(元)', 'type': 'float64'},
                'sel_bck_actl': {'desc': '实付回售款(元)', 'type': 'float64'},
                'prcp_int_tot_actl': {'desc': '实际兑付本息及回售款(元)', 'type': 'float64'},
                'dft_prcp_actl': {'desc': '实际违约本金规模', 'type': 'float64'},
                'dft_int_actl': {'desc': '实际违约利息规模', 'type': 'float64'},
                'dft_bck_actl': {'desc': '实际违约回售规模', 'type': 'float64'},
                'dft_prcp_int_actl': {'desc': '实际违约总规模', 'type': 'float64'},
                'is_dft_actl': {'desc': '是否债券实际违约', 'type': 'str'},
                'remark': {'desc': '备注', 'type': 'str'},
                'late_pay_sts': {'desc': '最新支付状态', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '违约发生日', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'IR_MNYMKTPRICE': {
        'source_table': 'AIWEBOND.IR_MNYMKTPRICE',
        'date': 'trd_dt',
        'date_format':'%Y-%m-%d' ,
        'instrument': 'ir_cd',
        'schema': {
            'desc': '货币市场行情',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/利率信息',
            'rank': 5016001,
            'friendly_name': '货币市场行情',
            'partition_date': 'Y',
            'primary_key': ['ir_cd', 'trd_dt','instrument'],
            'fields': {
                'ir_cd': {'desc': '利率内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'opn_ir': {'desc': '开盘利率(%)', 'type': 'float64'},
                'hi_ir': {'desc': '最高利率(%)', 'type': 'float64'},
                'lo_ir': {'desc': '最低利率(%)', 'type': 'float64'},
                'cls_quo_ir': {'desc': '收盘利率(%)', 'type': 'float64'},
                'wt_avg_ir': {'desc': '加权平均利率(%)', 'type': 'float64'},
                'up_dn_bp': {'desc': '升降(基点)', 'type': 'float64'},
                'chg_prc': {'desc': '涨跌(点)', 'type': 'float64'},
                'pct_chg': {'desc': '涨跌幅(%)', 'type': 'float64'},
                'amplt': {'desc': '振幅(%)', 'type': 'float64'},
                'vol': {'desc': '成交量(手)', 'type': 'float64'},
                'amt': {'desc': '成交金额(亿元)', 'type': 'float64'},
                'deals': {'desc': '成交笔数(笔)', 'type': 'float64'},
                'avg_each_amt': {'desc': '平均每笔成交金额(亿元）', 'type': 'float64'},
                'avg_each_vol': {'desc': '平均每笔成交量(手)', 'type': 'float64'},
                'prcp': {'desc': '本金额(亿元）', 'type': 'float64'},
                'incl_trm': {'desc': '内含期限(天)', 'type': 'float64'},
                'avg_rpch_trm': {'desc': '平均回购期限(天)', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '利率内部编码', 'type': 'str'},
            },
        },
    },
    'IR_GLBIBOR': {
        'source_table': 'AIWEBOND.IR_GLBIBOR',
        'date': 'trd_dt',
        'date_format':'%Y-%m-%d' ,
        'instrument': 'ir_cd',
        'schema': {
            'desc': '全球同业拆放利率表',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/利率信息',
            'rank': 5016002,
            'friendly_name': '全球同业拆放利率表',
            'partition_date': 'Y',
            'primary_key': ['ir_cd', 'trd_dt','instrument'],
            'fields': {
                'ir_cd': {'desc': '利率内部编码', 'type': 'str'},
                'ir_typ': {'desc': '利率类型', 'type': 'str'},
                'chn_nm': {'desc': '利率名称', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'intr_rat': {'desc': '利率(%)', 'type': 'float64'},
                'chg_prc': {'desc': '涨跌(bp)', 'type': 'float64'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '利率内部编码', 'type': 'str'},
            },
        },
    },
    'IR_REFBASERATE': {
        'source_table': 'AIWEBOND2.IR_REFBASERATE',
        'date': 'trd_dt',
        'date_format':'%Y-%m-%d' ,
        'instrument': 'ir_cd',
        'schema': {
            'desc': '证券产品表-基准利率参考指标',
            'active': True,
            'date_field': 'date',
            'category': '固定收益（原表）/利率信息',
            'rank': 5016003,
            'friendly_name': '证券产品表-基准利率参考指标',
            'partition_date': None,
            'primary_key': ['ir_cd', 'trd_dt','instrument'],
            'fields': {
                'ir_cd': {'desc': '利率内部编码', 'type': 'str'},
                'trd_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'smb': {'desc': '利率代码', 'type': 'str'},
                'chn_nm': {'desc': '基准利率名称', 'type': 'str'},
                'ir': {'desc': '利率（%）', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '利率内部编码', 'type': 'str'},
            },
        },
    },
}
if __name__ == "__main__":
    pass
    # print(list(TABLES_MAPS.keys()))
    for table in TABLES_MAPS:
        print(TABLES_MAPS[table]['schema']['desc'],'：',table)