"""2022-04-21数据结构，删除了技术性字段"""

TABLES_MAPS = {
    # 基本资料
    'FUND_BASICINFO': {
        'source_table': 'AIWEFUND.FUND_BASICINFO',
        'date': None,
        'date_format': None,
        'instrument': 'smb',    # 基金代码，需要处理为ZOF\HOF
        'schema': {
            'desc': '基金基本信息',
            'active': True,
            'date_field': None,
            'category': '基金(原表)/基本资料',
            'rank': 1001001,
            'friendly_name': '基金基本信息',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'instrument'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'chn_nm': {'desc': '基金名称', 'type': 'str'},
                'fnd_dscr': {'desc': '基金简介', 'type': 'str'},
                'fnd_evl': {'desc': '基金沿革', 'type': 'str'},
                'chn_sht_nm': {'desc': '基金简称', 'type': 'str'},
                'smb': {'desc': '基金代码', 'type': 'str'},
                'frnt_smb': {'desc': '前端代码', 'type': 'str'},
                'bck_smb': {'desc': '后端代码', 'type': 'str'},
                'fnd_typ': {'desc': '运作方式', 'type': 'str'},
                'par_val': {'desc': '面值', 'type': 'float64'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'exg_cd': {'desc': '证券市场', 'type': 'str'},
                'trd_plc': {'desc': '交易市场', 'type': 'str'},
                'blg_ser': {'desc': '所属基金系列', 'type': 'str'},
                'is_rgl_opn': {'desc': '是否定期开放型基金', 'type': 'str'},
                'mng_nm': {'desc': '管理人名称', 'type': 'str'},
                'mng_cd': {'desc': '管理人代码', 'type': 'str'},
                'cstd_nm': {'desc': '托管人名称(废弃)', 'type': 'str'},
                'cstd_cd': {'desc': '托管人代码', 'type': 'str'},
                'found_dt': {'desc': '成立日期', 'type': 'datetime64[ns]'},
                'lst_dt': {'desc': '上市日期', 'type': 'datetime64[ns]'},
                'delst_dt': {'desc': '退市日期', 'type': 'datetime64[ns]'},
                'due_dt': {'desc': '到期日期', 'type': 'datetime64[ns]'},
                'rmn_trm': {'desc': '存续期', 'type': 'float64'},
                'orig_end_dt': {'desc': '原存续终止日', 'type': 'datetime64[ns]'},
                'cle_start_dt': {'desc': '清算日期', 'type': 'datetime64[ns]'},
                'cle_end_dt': {'desc': '清算截止日', 'type': 'datetime64[ns]'},
                'inv_scp': {'desc': '投资范围', 'type': 'str'},
                'inv_tgt': {'desc': '投资目标', 'type': 'str'},
                'inv_idea': {'desc': '投资理念', 'type': 'str'},
                'inv_strt': {'desc': '投资策略', 'type': 'str'},
                'inv_styl': {'desc': '投资风格', 'type': 'str'},
                'inv_typ': {'desc': '投资类型', 'type': 'str'},
                'dcd_bas': {'desc': '决策依据', 'type': 'str'},
                'dcd_pro': {'desc': '决策程序', 'type': 'str'},
                'inv_std': {'desc': '投资标准', 'type': 'str'},
                'rsk_ern_ftr': {'desc': '风险收益特征', 'type': 'str'},
                'alc_prc': {'desc': '收益分配原则', 'type': 'str'},
                'cls_opr_trm': {'desc': '封闭运作期', 'type': 'int64'},
                'cls_opr_trm_unt': {'desc': '运作期单位', 'type': 'str'},
                'pfm_bchm': {'desc': '业绩基准', 'type': 'str'},
                'rsk_mng_tool': {'desc': '风险管理工具及主要指标', 'type': 'str'},
                'cry_ovr_mod': {'desc': '份额结转方式', 'type': 'str'},
                'cry_ovr_day': {'desc': '每月份额结转日', 'type': 'str'},
                'ern_pay_mod': {'desc': '收益支付方式', 'type': 'str'},
                'shr_typ': {'desc': '分级基金份额类型', 'type': 'str'},
                'main_smb': {'desc': '主基金代码', 'type': 'str'},
                'join_fnd_smb': {'desc': '联接型基金所联接基金代码', 'type': 'str'},
                'trc_idx_smb': {'desc': '指数型基金跟踪指数', 'type': 'str'},
                'rch_cfm_dt': {'desc': '申购确认天数', 'type': 'str'},
                'rdm_cfm_dt': {'desc': '赎回确认天数', 'type': 'str'},
                'rdm_pay_dt': {'desc': '赎回交收天数', 'type': 'str'},
                'fee_mng': {'desc': '管理费（%）', 'type': 'float64'},
                'fee_cstd': {'desc': '托管费（%）', 'type': 'float64'},
                'fee_sale': {'desc': '销售服务费（%）', 'type': 'float64'},
                'is_ini_fnd': {'desc': '是否为初始基金', 'type': 'str'},
                'inv_rgn': {'desc': '投资区域', 'type': 'str'},
                'reg_cd': {'desc': '登记备案机构代码', 'type': 'str'},
                'reg_nm': {'desc': '登记备案机构名称(废弃)', 'type': 'str'},
                'nav_pbl_mth': {'desc': '净值披露方式', 'type': 'str'},
                'ta_typ': {'desc': 'TA类型', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
            },
        },
    },
    'FUND_CLASSIFICATION': {
        'source_table': 'AIWEFUND.FUND_CLASSIFICATION',
        'date': 'start_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金分类',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/基本资料',
            'rank': 1001002,
            'friendly_name': '基金分类',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'cls_sys_cd', 'cls_cd_1st', 'start_dt', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'cls_sys_cd': {'desc': '分类口径', 'type': 'str'},
                'cls_cd_1st': {'desc': '一级分类代码', 'type': 'str'},
                'cls_nm_1st': {'desc': '一级分类名称', 'type': 'str'},
                'cls_cd_2nd': {'desc': '二级分类代码', 'type': 'str'},
                'cls_nm_2nd': {'desc': '二级分类名称', 'type': 'str'},
                'cls_cd_3rd': {'desc': '三级分类代码', 'type': 'str'},
                'cls_nm_3rd': {'desc': '三级分类名称', 'type': 'str'},
                'cls_cd_4th': {'desc': '四级分类代码', 'type': 'str'},
                'cls_nm_4th': {'desc': '四级分类名称', 'type': 'str'},
                'start_dt': {'desc': '变动起始日', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '变动截止日', 'type': 'datetime64[ns]'},
                'cur_sgn': {'desc': '最新标志', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '变动起始日', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_OPERPERIOD': {
        'source_table': 'AIWEFUND.FUND_OPERPERIOD',
        'date': 'start_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金运作周期表',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/基本资料',
            'rank': 1001003,
            'friendly_name': '基金运作周期表',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'dt_typ', 'start_dt', 'instrument'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'dt_typ': {'desc': '日期类型', 'type': 'str'},
                'start_dt': {'desc': '起始日', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '截止日', 'type': 'datetime64[ns]'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '起始日', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_PFMBCHM': {
        'source_table': 'AIWEFUND.FUND_PFMBCHM',
        'date': 'start_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金业绩比较基准指数权重',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/基本资料',
            'rank': 1001004,
            'friendly_name': '基金业绩比较基准指数权重',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'start_dt', 'ord_num', 'instrument'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'start_dt': {'desc': '起始日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '截止日期', 'type': 'datetime64[ns]'},
                'ord_num': {'desc': '序号', 'type': 'str'},
                'bchm_idx_cd': {'desc': '基准指数内部编码', 'type': 'str'},
                'bchm_cpn_cd': {'desc': '基准指数成分内部编码', 'type': 'str'},
                'idx_wt': {'desc': '指数权重', 'type': 'float64'},
                'opr_smb': {'desc': '运算符', 'type': 'str'},
                'const': {'desc': '常数', 'type': 'float64'},
                'is_tax': {'desc': '是否税后', 'type': 'str'},
                'is_late': {'desc': '是否最新', 'type': 'str'},
                'exr_cd': {'desc': '汇率代码', 'type': 'str'},
                'is_cmpd': {'desc': '是否复利', 'type': 'str'},
                'pfm_bchm_dscr': {'desc': '业绩比较基准描述', 'type': 'str'},
                'pfm_bchm_trm': {'desc': '基准收益率计算周期', 'type': 'str'},
                'remark': {'desc': '备注', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '起始日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_FEE': {
        'source_table': 'AIWEFUND.FUND_FEE',
        'date': 'anc_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金费率表',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/基本资料',
            'rank': 1001005,
            'friendly_name': '基金费率表',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'anc_dt', 'ord_nbr', 'fee_nm2', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'start_dt': {'desc': '起始日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '截止日期', 'type': 'datetime64[ns]'},
                'ord_nbr': {'desc': '序号', 'type': 'str'},
                'fee_nm1': {'desc': '费率名称大项', 'type': 'str'},
                'fee_nm2': {'desc': '费率名称子项', 'type': 'str'},
                'fee_calc_mod': {'desc': '费用计算方式', 'type': 'str'},
                'fee_calc_mtd_frnt': {'desc': '认申购费用计算方法', 'type': 'str'},
                'fee_calc_mtd_bck': {'desc': '后端认申购（或赎回）费用计算方法', 'type': 'str'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'fee_unt': {'desc': '费率费用单位', 'type': 'str'},
                'fee_lo': {'desc': '费率费用下限', 'type': 'float64'},
                'fee_rel': {'desc': '费率条件关系', 'type': 'str'},
                'fee_hi': {'desc': '费率费用上限', 'type': 'float64'},
                'amt_lo': {'desc': '适用金额下限(万元)', 'type': 'int64'},
                'amt_rel': {'desc': '金额条件关系', 'type': 'str'},
                'amt_hi': {'desc': '适用金额上限(万元)', 'type': 'int64'},
                'trm_unt': {'desc': '持有期限单位', 'type': 'str'},
                'trm_lo': {'desc': '持有期限下限', 'type': 'int64'},
                'trm_rel': {'desc': '期限条件关系', 'type': 'str'},
                'trm_hi': {'desc': '持有期限上限', 'type': 'int64'},
                'apl_obj': {'desc': '适用对象', 'type': 'str'},
                'is_cnv': {'desc': '份额是否可以转换', 'type': 'str'},
                'cnv_fnd_cd': {'desc': '转换基金代码', 'type': 'str'},
                'fee_dscr': {'desc': '费率补充说明', 'type': 'str'},
                'is_new': {'desc': '是否最新数据', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
            },
        },
    },

    # 行情净值
    'FUND_NETVALUE': {
        'source_table': 'AIWEFUND.FUND_NETVALUE',
        'date': 'nav_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '公募基金净值表',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/行情净值',
            'rank': 1002001,
            'friendly_name': '公募基金净值表',
            'partition_date': 'Y',
            'primary_key': ['fnd_cd', 'nav_dt', 'instrument', 'date'],
            'fields': {
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'nav_dt': {'desc': '净值日期', 'type': 'datetime64[ns]'},
                'is_xrt_dt': {'desc': '是否净值除权日', 'type': 'str'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'unt_nav': {'desc': '单位净值(元)', 'type': 'float64'},
                'nav_inc_rat': {'desc': '净值增长率(%)(T+1更新)', 'type': 'float64'},
                'acm_unt_nav': {'desc': '累计单位净值(元)', 'type': 'float64'},
                'adj_fct': {'desc': '复权因子', 'type': 'float64'},
                'adj_unt_nav': {'desc': '复权单位净值', 'type': 'float64'},
                'net_ast': {'desc': '资产净值(元)', 'type': 'float64'},
                'is_mrg': {'desc': '是否为合并数据', 'type': 'str'},
                'tot_net_ast': {'desc': '合计资产净值', 'type': 'float64'},
                'remark': {'desc': '备注', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '净值日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_NETVALUE_MMF': {
        'source_table': 'AIWEFUND.FUND_NETVALUE_MMF',
        'date': 'start_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '货币基金净值表',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/行情净值',
            'rank': 1002002,
            'friendly_name': '货币基金净值表',
            'partition_date': 'Y',
            'primary_key': ['fnd_cd', 'start_dt', 'end_dt', 'instrument', 'date'],
            'fields': {
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'start_dt': {'desc': '起始日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '截止日期', 'type': 'datetime64[ns]'},
                'inc_10k_shr': {'desc': '每万份基金单位收益', 'type': 'float64'},
                'anl_yld_7d': {'desc': '近七日年化收益率', 'type': 'float64'},
                'anl_yld_1m': {'desc': '最近1月年化收益率', 'type': 'float64'},
                'remark': {'desc': '备注', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '起始日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_EODPRICE': {
        'source_table': 'AIWEFUND.FUND_EODPRICE',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金日行情',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/行情净值',
            'rank': 1002003,
            'friendly_name': '基金日行情',
            'partition_date': 'Y',
            'primary_key': ['fnd_cd', 'end_dt', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'end_dt': {'desc': '交易日期', 'type': 'datetime64[ns]'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'pre_cls_prc': {'desc': '昨收盘(元)', 'type': 'float64'},
                'opn_prc': {'desc': '开盘价(元)', 'type': 'float64'},
                'hi_prc': {'desc': '最高价(元)', 'type': 'float64'},
                'lo_prc': {'desc': '最低价(元)', 'type': 'float64'},
                'cls_prc': {'desc': '收盘价(元)', 'type': 'float64'},
                'vol': {'desc': '成交量(份)', 'type': 'float64'},
                'amt': {'desc': '成交金额(元)', 'type': 'float64'},
                'deals': {'desc': '成交笔数(笔)', 'type': 'float64'},
                'avg_prc': {'desc': '成交均价(元)', 'type': 'float64'},
                'vol_per_deal': {'desc': '平均每笔成交量(份)', 'type': 'float64'},
                'amt_per_deal': {'desc': '平均每笔成交额(元)', 'type': 'float64'},
                'dcnt_rat': {'desc': '贴水率(%)', 'type': 'float64'},
                'chg_prc': {'desc': '涨跌', 'type': 'float64'},
                'pct_chg': {'desc': '涨跌幅(%)', 'type': 'float64'},
                'amplt': {'desc': '振幅(%)', 'type': 'float64'},
                'trn_rat': {'desc': '换手率(%)', 'type': 'float64'},
                'adj_fct': {'desc': '复权因子', 'type': 'float64'},
                'pre_cls_prc_adj': {'desc': '复权昨收盘价(元)', 'type': 'float64'},
                'opn_prc_adj': {'desc': '复权开盘价(元)', 'type': 'float64'},
                'hi_prc_adj': {'desc': '复权最高价(元)', 'type': 'float64'},
                'lo_prc_adj': {'desc': '复权最低价(元)', 'type': 'float64'},
                'cls_prc_adj': {'desc': '复权收盘价(元)', 'type': 'float64'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '交易日期', 'type': 'datetime64[ns]'},
            },
        },
    },

    # 份额
    'FUND_SHARES': {
        'source_table': 'AIWEFUND.FUND_SHARES',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金份额',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/份额',
            'rank': 1003001,
            'friendly_name': '基金份额',
            'partition_date': 'Y',
            'primary_key': ['fnd_cd', 'end_dt', 'instrument', 'date'],
            'fields': {
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'end_dt': {'desc': '变动日期', 'type': 'datetime64[ns]'},
                'fnd_shr': {'desc': '基金份额(份)', 'type': 'float64'},
                'crc_shr': {'desc': '流通份额(份)', 'type': 'float64'},
                'on_exg_shr': {'desc': '场内份额(份)', 'type': 'float64'},
                'tot_shr': {'desc': '基金总份额(份)', 'type': 'float64'},
                'is_mrg': {'desc': '是否为合并数据', 'type': 'str'},
                'chg_rsn': {'desc': '基金份额变动原因', 'type': 'str'},
                'remark': {'desc': '备注', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '变动日期', 'type': 'datetime64[ns]'},
            },
        },
    },

    # 财务
    'FUND_FIN_INCOME': {
        'source_table': 'AIWEFUND.FUND_FIN_INCOME',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金利润表',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/财务',
            'rank': 1004001,
            'friendly_name': '基金利润表',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'end_dt', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金编码', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '截止日期', 'type': 'datetime64[ns]'},
                'act_std_cd': {'desc': '会计准则', 'type': 'str'},
                'ccy_cd': {'desc': '货币代码', 'type': 'str'},
                'inc_int': {'desc': '一、利息收入', 'type': 'float64'},
                'inc_int_dpst': {'desc': '(1.1)存款利息收入', 'type': 'float64'},
                'inc_int_bnd': {'desc': '(1.2)债券利息收入', 'type': 'float64'},
                'inc_int_abs': {'desc': '(1.3)资产支持证券利息收入', 'type': 'float64'},
                'inc_fin_ast_slbk': {'desc': '(1.4)买入返售金融资产收入', 'type': 'float64'},
                'inc_int_oth': {'desc': '(1.5)其他利息收入', 'type': 'float64'},
                'inc_inv': {'desc': '二、投资收益', 'type': 'float64'},
                'inc_inv_stk': {'desc': '(2.1)股票投资收益', 'type': 'float64'},
                'inc_inv_fnd': {'desc': '(2.2)基金投资收益', 'type': 'float64'},
                'inc_inv_bnd': {'desc': '(2.3)债券投资收益', 'type': 'float64'},
                'inc_inv_abs': {'desc': '(2.4)资产支持证券投资收益', 'type': 'float64'},
                'inc_inv_prec_metal': {'desc': '(2.5)贵金属投资收益', 'type': 'float64'},
                'inc_inv_deri': {'desc': '(2.6)衍生工具收益', 'type': 'float64'},
                'inc_stk_dvd': {'desc': '(2.7)股利收益', 'type': 'float64'},
                'inc_fnd_dvd': {'desc': '(2.8)基金分红收益', 'type': 'float64'},
                'inc_inv_oth': {'desc': '(2.9)其他投资收益', 'type': 'float64'},
                'inc_fv_chg': {'desc': '三、公允价值变动收益', 'type': 'float64'},
                'inc_fx_exg': {'desc': '四、汇兑收益', 'type': 'float64'},
                'inc_oth': {'desc': '五、其他收入', 'type': 'float64'},
                'spc_inc': {'desc': '收入差额(特殊报表科目)', 'type': 'float64'},
                'adj_inc': {'desc': '收入差额(合计平衡科目)', 'type': 'float64'},
                'tot_inc': {'desc': '收入合计', 'type': 'float64'},
                'mng_exp': {'desc': '一、管理人报酬', 'type': 'float64'},
                'cstd_exp': {'desc': '二、托管费', 'type': 'float64'},
                'sale_exp': {'desc': '三、销售服务费', 'type': 'float64'},
                'trd_exp': {'desc': '四、交易费用', 'type': 'float64'},
                'int_exp': {'desc': '五、利息支出', 'type': 'float64'},
                'fin_ast_repo_exp': {'desc': '其中：卖出回购金融资产支出', 'type': 'float64'},
                'tax_surchrg': {'desc': '六、税金及附加', 'type': 'float64'},
                'oth_exp': {'desc': '七、其他费用', 'type': 'float64'},
                'spc_exp': {'desc': '费用差额(特殊报表科目)', 'type': 'float64'},
                'adj_exp': {'desc': '费用差额(合计平衡科目)', 'type': 'float64'},
                'tot_exp': {'desc': '费用合计', 'type': 'float64'},
                'adj_pft_pvs': {'desc': '以前年度损益调整', 'type': 'float64'},
                'spc_pft': {'desc': '利润差额(特殊报表科目)', 'type': 'float64'},
                'adj_pft': {'desc': '利润差额(合计平衡科目)', 'type': 'float64'},
                'tot_pft': {'desc': '利润总额', 'type': 'float64'},
                'inc_tax': {'desc': '减：所得税费用', 'type': 'float64'},
                'net_pft': {'desc': '净利润', 'type': 'float64'},
                'remark': {'desc': '备注说明', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '截止日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_FIN_BALANCE': {
        'source_table': 'AIWEFUND.FUND_FIN_BALANCE',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金资产负责表',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/财务',
            'rank': 1004002,
            'friendly_name': '基金资产负责表',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'end_dt', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金编码', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '截止日期', 'type': 'datetime64[ns]'},
                'act_std_cd': {'desc': '会计准则', 'type': 'str'},
                'ccy_cd': {'desc': '货币代码', 'type': 'str'},
                'bnk_dpst': {'desc': '银行存款', 'type': 'float64'},
                'prvs_stl': {'desc': '结算备付金', 'type': 'float64'},
                'mrgn_paid': {'desc': '存出保证金', 'type': 'float64'},
                'fin_ast_tras': {'desc': '交易性金融资产', 'type': 'float64'},
                'stk_cst': {'desc': '其中：股票投资成本', 'type': 'float64'},
                'stk_inv': {'desc': '股票投资', 'type': 'float64'},
                'stk_val_add': {'desc': '其中：股票投资估值增值', 'type': 'float64'},
                'fnd_inv': {'desc': '基金投资', 'type': 'float64'},
                'bnd_inv': {'desc': '债券投资', 'type': 'float64'},
                'bnd_cst': {'desc': '其中：债券投资成本', 'type': 'float64'},
                'bnd_val_add': {'desc': '其中：债券投资估值增值', 'type': 'float64'},
                'gov_bnd_cst': {'desc': '其中：国债投资成本', 'type': 'float64'},
                'gov_bnd_val_add': {'desc': '其中：国债投资估值增值', 'type': 'float64'},
                'cnv_bnd_cst': {'desc': '其中：可转债投资成本', 'type': 'float64'},
                'cnv_bnd_val_add': {'desc': '其中：可转债投资估值增值', 'type': 'float64'},
                'abs_inv': {'desc': '资产支持证券投资', 'type': 'float64'},
                'fin_ast_deri': {'desc': '衍生金融资产', 'type': 'float64'},
                'wrnt_inv': {'desc': '权证投资', 'type': 'float64'},
                'wrnt_cst': {'desc': '其中：权证投资成本', 'type': 'float64'},
                'fin_ast_slbk': {'desc': '买入反售金融资产', 'type': 'float64'},
                'oth_fin_ast_tras': {'desc': '其它交易性金融资产', 'type': 'float64'},
                'rcv_sec_clr': {'desc': '应收证券清算款', 'type': 'float64'},
                'rcv_int': {'desc': '应收利息', 'type': 'float64'},
                'rcv_dvd': {'desc': '应收股利', 'type': 'float64'},
                'rcv_pch': {'desc': '应收申购款', 'type': 'float64'},
                'rcv_acc': {'desc': '应收账款', 'type': 'float64'},
                'rcv_oth': {'desc': '其它应收款', 'type': 'float64'},
                'ast_df_tax': {'desc': '递延所得税资产', 'type': 'float64'},
                'exp_df': {'desc': '待摊费用', 'type': 'float64'},
                'ast_oth': {'desc': '其它资产', 'type': 'float64'},
                'spc_ast': {'desc': '资产差额(归并报表科目)', 'type': 'float64'},
                'adj_ast': {'desc': '资产差额(合计平衡科目)', 'type': 'float64'},
                'ast_tot': {'desc': '资产', 'type': 'float64'},
                'brw_st': {'desc': '短期借款', 'type': 'float64'},
                'fin_lbl_tras': {'desc': '交易性金融负债', 'type': 'float64'},
                'fin_lbl_deri': {'desc': '衍生金融负债', 'type': 'float64'},
                'fnd_rp': {'desc': '卖出回购金融资产款', 'type': 'float64'},
                'pay_sec_clr': {'desc': '应付证券清算款', 'type': 'float64'},
                'pay_rdm': {'desc': '应付赎回款', 'type': 'float64'},
                'pay_rdm_fee': {'desc': '应付赎回费', 'type': 'float64'},
                'pay_mng': {'desc': '应付管理人报酬', 'type': 'float64'},
                'pay_cstd': {'desc': '应付托管费', 'type': 'float64'},
                'pay_sale': {'desc': '应付销售服务费', 'type': 'float64'},
                'pay_trd': {'desc': '应付交易费用(应付佣金)', 'type': 'float64'},
                'pay_tax': {'desc': '应交税费', 'type': 'float64'},
                'pay_int': {'desc': '应付利息', 'type': 'float64'},
                'pay_pft': {'desc': '应付利润', 'type': 'float64'},
                'pay_acc': {'desc': '应付账款', 'type': 'float64'},
                'pay_oth': {'desc': '其它应付款', 'type': 'float64'},
                'lbl_df_tax': {'desc': '递延所得税负债', 'type': 'float64'},
                'exp_accr': {'desc': '预提费用', 'type': 'float64'},
                'oth_lbl': {'desc': '其它负债', 'type': 'float64'},
                'spc_lbl': {'desc': '负债差额(归并报表科目)', 'type': 'float64'},
                'adj_lbl': {'desc': '负债差额(合计平衡科目)', 'type': 'float64'},
                'lbl_tot': {'desc': '负债', 'type': 'float64'},
                'paid_cap': {'desc': '实收资本', 'type': 'float64'},
                'undtrb_pft': {'desc': '未分配利润', 'type': 'float64'},
                'unrelz_pft': {'desc': '未实现利得', 'type': 'float64'},
                'oth_eqt': {'desc': '其它权益', 'type': 'float64'},
                'spc_oe': {'desc': '权益差额(归并报表科目)', 'type': 'float64'},
                'adj_oe': {'desc': '权益差额(合计平衡科目)', 'type': 'float64'},
                'oe_tot': {'desc': '所有者权益', 'type': 'float64'},
                'spc_lbl_oe': {'desc': '负债及权益差额(归并报表科目)', 'type': 'float64'},
                'adj_lbl_oe': {'desc': '负债及权益差额(合计平衡科目)', 'type': 'float64'},
                'tot_lbl_oe': {'desc': '负债和所有者权益', 'type': 'float64'},
                'unt_nav': {'desc': '期末基金分额净值', 'type': 'float64'},
                'tot_shr': {'desc': '合计基金份额', 'type': 'float64'},
                'remark': {'desc': '备注说明', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '截止日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_FIN_INDICATOR': {
        'source_table': 'AIWEFUND.FUND_FIN_INDICATOR',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金主要会计数据和财务指标',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/财务',
            'rank': 1004003,
            'friendly_name': '基金主要会计数据和财务指标',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'end_dt', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金编码', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '截止日期', 'type': 'datetime64[ns]'},
                'act_std_cd': {'desc': '会计准则', 'type': 'str'},
                'ccy_cd': {'desc': '货币代码', 'type': 'str'},
                'rlz_rvn': {'desc': '本期已实现收益', 'type': 'float64'},
                'tot_pft': {'desc': '本期利润', 'type': 'float64'},
                'wavg_pft_per_shr': {'desc': '加权平均基金分额本期利润', 'type': 'float64'},
                'wavg_pft_rat': {'desc': '本期加权平均净值利润率(%)', 'type': 'float64'},
                'rtn_nav': {'desc': '本期基金分额净值增长率(%)', 'type': 'float64'},
                'pft_dtrb': {'desc': '期末可供分配利润', 'type': 'float64'},
                'pft_dtrb_per_shr': {'desc': '期末可供分配基金份额利润', 'type': 'float64'},
                'net_ast': {'desc': '期末基金资产净值', 'type': 'float64'},
                'nav': {'desc': '期末基金份额净值', 'type': 'float64'},
                'tot_shr': {'desc': '期末基金总份额', 'type': 'float64'},
                'acm_rtn_nav': {'desc': '基金份额累计净值增长率(%)', 'type': 'float64'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '截止日期', 'type': 'datetime64[ns]'},
            },
        },
    },

    # 分红
    'FUND_SHRCNVSPLIT': {
        'source_table': 'AIWEFUND.FUND_SHRCNVSPLIT',
        'date': 'splt_cnv_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金拆份折算',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/分红',
            'rank': 1005001,
            'friendly_name': '基金拆份折算',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'splt_cnv_dt', 'instrument', 'date'],
            'fields': {
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'splt_cnv_dt': {'desc': '拆份折算日期', 'type': 'datetime64[ns]'},
                'splt_cnv_rat': {'desc': '拆分折算比例', 'type': 'float64'},
                'cnv_rat_slf': {'desc': '折算成本基金的比例', 'type': 'float64'},
                'cnv_rat_rel': {'desc': '折算成关联基金的比例', 'type': 'float64'},
                'rel_fnd_cd': {'desc': '关联基金内部编码', 'type': 'str'},
                'xrt_dt': {'desc': '折分折算场内除权日', 'type': 'datetime64[ns]'},
                'shr_reg_dt': {'desc': '基金份额变更登记日', 'type': 'datetime64[ns]'},
                'splt_cnv_typ': {'desc': '拆分折算类型', 'type': 'str'},
                'shr_pre': {'desc': '拆分折算前份额', 'type': 'float64'},
                'nav_pre': {'desc': '拆分折算前单位净值', 'type': 'float64'},
                'shr_aft': {'desc': '拆分折算后份额', 'type': 'float64'},
                'nav_aft': {'desc': '拆分折算后单位净值', 'type': 'float64'},
                'remark': {'desc': '备注', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_DIVIDEND': {
        'source_table': 'AIWEFUND.FUND_DIVIDEND',
        'date': 'xr_dt_act',  # 非主键，实际除息日
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金分红表',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/分红',
            'rank': 1005002,
            'friendly_name': '基金分红表',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'dvd_year', 'dvd_tms', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'dvd_year': {'desc': '分红年度', 'type': 'str'},
                'dvd_tms': {'desc': '本年度第N次分红', 'type': 'int64'},
                'dvd_obj': {'desc': '分红对象', 'type': 'str'},
                'dvd_prgr': {'desc': '最新分红进程', 'type': 'str'},
                'inc_pay_mod': {'desc': '分红分配方式', 'type': 'str'},
                'anc_dt_impl': {'desc': '分红实施公告日', 'type': 'datetime64[ns]'},
                'bas_dt_inc_pay': {'desc': '收益分配基准日', 'type': 'datetime64[ns]'},
                'reg_dt': {'desc': '权益登记日', 'type': 'datetime64[ns]'},
                'xd_dt_on_exch': {'desc': '场内除息日', 'type': 'datetime64[ns]'},
                'xd_dt_out_exch': {'desc': '场外除息日', 'type': 'datetime64[ns]'},
                'xr_dt_act': {'desc': '实际除息日', 'type': 'datetime64[ns]'},
                'dtrb_dt_on_exg': {'desc': '场内红利发放日', 'type': 'datetime64[ns]'},
                'dtrb_dt_out_exg': {'desc': '场外红利发放日', 'type': 'datetime64[ns]'},
                'inc_pay_dt': {'desc': '收益支付日(货币型)', 'type': 'datetime64[ns]'},
                'bas_lot': {'desc': '基准份额(份)', 'type': 'float64'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'unt_dvd_bfr_tax': {'desc': '单位税前红利(元/份)', 'type': 'float64'},
                'unt_dvd_aft_tax': {'desc': '单位税后红利(元/份)', 'type': 'float64'},
                'unt_reinv': {'desc': '单位红利再投资(份)', 'type': 'float64'},
                'act_dvd_amt': {'desc': '收益分配金额(元)', 'type': 'float64'},
                'pay_dvd_amt': {'desc': '可供分配收益(元)', 'type': 'float64'},
                'rmn_dvd_amt': {'desc': '剩余收益(元)', 'type': 'float64'},
                'unt_prc_aft_dtrb': {'desc': '分配后每基金单位净值', 'type': 'float64'},
                'bas_dt_reinv': {'desc': '红利再投资份额净值基准日', 'type': 'datetime64[ns]'},
                'acct_dt_reinv': {'desc': '红利再投资份额到帐日', 'type': 'datetime64[ns]'},
                'rdm_dt_reinv': {'desc': '红利再投资份额可赎回日', 'type': 'datetime64[ns]'},
                'remark': {'desc': '备注', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '实际除息日', 'type': 'datetime64[ns]'},
            },
        },
    },

    # 基金经理
    'FUND_MANAGER': {
        'source_table': 'AIWEFUND.FUND_MANAGER',
        'date': 'start_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金经理',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/基金经理',
            'rank': 1006001,
            'friendly_name': '基金经理',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'nm', 'start_dt', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'psn_cd': {'desc': '人员代码', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'nm': {'desc': '姓名', 'type': 'str'},
                'start_dt': {'desc': '任职日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '离职日期', 'type': 'datetime64[ns]'},
                'memo': {'desc': '备注', 'type': 'str'},
                'dty': {'desc': '职务', 'type': 'str'},
                'fnd_typ': {'desc': '基金类别', 'type': 'str'},
                'is_pos': {'desc': '是否现任', 'type': 'str'},
                'lve_rsn': {'desc': '离任原因', 'type': 'str'},
                'is_drw_slr': {'desc': '是否领薪', 'type': 'str'},
                'late_slr': {'desc': '最新年薪', 'type': 'float64'},
                'no_slr_rsn': {'desc': '不领薪原因', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '姓名', 'type': 'str'},
                'date': {'desc': '任职日期', 'type': 'datetime64[ns]'},
            },
        },
    },

    # 基金投资比例
    'FUND_INVPOSLMT': {
        'source_table': 'AIWEFUND.FUND_INVPOSLMT',
        'date': 'chg_dt',
        'date_format': '%Y%m%d',    # 注意：这个字段在数据库中是varchar(10)类型
        'instrument': 'smb',
        'schema': {
            'desc': '基金投资比例信息表',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/基金投资比例',
            'rank': 1007001,
            'friendly_name': '基金投资比例信息表',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'chg_dt', 'inv_rto_typ', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'chg_dt': {'desc': '变动日期', 'type': 'str'},
                'inv_rto_typ': {'desc': '基金投资占比类型代码', 'type': 'str'},
                'stk_inv_pct_flr': {'desc': '股票投资比例下限', 'type': 'float64'},
                'stk_inv_pct_ceil': {'desc': '股票投资比例上限', 'type': 'float64'},
                'bnd_inv_pct_flr': {'desc': '债券投资比例下限', 'type': 'float64'},
                'bnd_inv_pct_ceil': {'desc': '债券投资比例上限', 'type': 'float64'},
                'mmi_inv_pct_flr': {'desc': '货币工具比例下限', 'type': 'float64'},
                'mmi_inv_pct_ceil': {'desc': '货币工具比例上限', 'type': 'float64'},
                'fnd_inv_pct_flr': {'desc': '基金投资比例下限', 'type': 'float64'},
                'fnd_inv_pct_ceil': {'desc': '基金投资比例上限', 'type': 'float64'},
                'cmdt_inv_pct_flr': {'desc': '商品衍生品投资比例下限', 'type': 'float64'},
                'cmdt_inv_pct_ceil': {'desc': '商品衍生品投资比例上限', 'type': 'float64'},
                'is_tot_pct': {'desc': '是否合计占比', 'type': 'float64'},
                'oth_inv_pct_flr': {'desc': '其他非股票投资比例下限', 'type': 'float64'},
                'oth_inv_pct_ceil': {'desc': '其他非股票投资比例上限', 'type': 'float64'},
                'ccpt_sbj_typ': {'desc': '概念主题类别名称', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '变动日期', 'type': 'datetime64[ns]'},
            },
        },
    },

    # 权益信息
    'FUND_HOLDERSTRUC': {
        'source_table': 'AIWEFUND.FUND_HOLDERSTRUC',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金持有人结构',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/权益信息',
            'rank': 1008001,
            'friendly_name': '基金持有人结构',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'end_dt', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'start_dt': {'desc': '开始日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
                'hld_num': {'desc': '基金持有人户数', 'type': 'str'},
                'avg_hld_shr': {'desc': '平均每户持有基金份额', 'type': 'float64'},
                'org_hld_shr': {'desc': '机构投资这持有份额', 'type': 'float64'},
                'org_hld_rat': {'desc': '机构投资者持有份额占总份额比例', 'type': 'float64'},
                'psn_hld_shr': {'desc': '个人投资者持有份额', 'type': 'float64'},
                'psn_hld_rat': {'desc': '个人投资这持有份额占总份额比例', 'type': 'float64'},
                'mng_hld_shr': {'desc': '基金管理人持有份额', 'type': 'float64'},
                'mng_hld_rat': {'desc': '基金管理人持有份额占总份额比例', 'type': 'float64'},
                'fnd_hld_shr': {'desc': '基金持有份额', 'type': 'float64'},
                'fnd_hld_rat': {'desc': '基金持有份额占总份额比例', 'type': 'float64'},
                'shh_hld_shr': {'desc': '基金公司股东持有份额', 'type': 'float64'},
                'shh_hld_rat': {'desc': '基金公司股东持有份额占总份额比例', 'type': 'float64'},
                'emp_hld_num': {'desc': '基金公司员工持有人数', 'type': 'float64'},
                'emp_hld_shr': {'desc': '基金公司员工持有份额', 'type': 'float64'},
                'emp_hld_rat': {'desc': '基金公司员工持有份额占总份额比例', 'type': 'float64'},
                'unc_shr': {'desc': '未确认份额', 'type': 'float64'},
                'unc_shr_rat': {'desc': '未确认份额占总份额比例', 'type': 'float64'},
                'remark': {'desc': '备注', 'type': 'str'},
                'is_stat': {'desc': '是否参与统计', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
            },
        },
    },

    # 投资组合
    'FUND_PFL_SECLIST_QDII': {
        'source_table': 'AIWEFUND.FUND_PFL_SECLIST_QDII',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': 'QDII基金投资组合（个券）',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/投资组合',
            'rank': 1009001,
            'friendly_name': 'QDII基金投资组合（个券）',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'end_dt', 'sec_smb', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
                'sec_typ': {'desc': '持有个券类别', 'type': 'str'},
                'sec_smb': {'desc': '持有个券代码', 'type': 'str'},
                'sec_nm': {'desc': '持有个券名称', 'type': 'str'},
                'hld_mkv': {'desc': '持有个券市值(元)', 'type': 'float64'},
                'hld_num': {'desc': '持有个券数量（张）', 'type': 'float64'},
                'hld_rat': {'desc': '持有个券市值占基金净值比例(%)', 'type': 'float64'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_PFL_SECLIST': {
        'source_table': 'AIWEFUND.FUND_PFL_SECLIST',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金投资组合（个券）',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/投资组合',
            'rank': 1009002,
            'friendly_name': '基金投资组合（个券）',
            'partition_date': 'M',
            'primary_key': ['fnd_cd', 'end_dt', 'sec_cd', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'end_dt': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
                'sec_cd': {'desc': '持有个券内部编码', 'type': 'str'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'sec_typ': {'desc': '持有个券类别', 'type': 'str'},
                'sec_nm': {'desc': '持有个券名称', 'type': 'str'},
                'hld_mkv': {'desc': '持有个券市值(元)', 'type': 'float64'},
                'hld_num': {'desc': '持有个券数量（张）', 'type': 'float64'},
                'hld_rat': {'desc': '持有个券市值占基金净值比例(%)', 'type': 'float64'},
                'mkv_actv': {'desc': '积极投资持有股票市值(元)', 'type': 'float64'},
                'vol_actv': {'desc': '积极投资持有股数（股）', 'type': 'float64'},
                'nav_pct_actv': {'desc': '积极投资持有股票市值占净资产比例(%)', 'type': 'float64'},
                'mkv_psv': {'desc': '指数投资持有股票市值(元)', 'type': 'float64'},
                'vol_psv': {'desc': '指数投资持有股数（股）', 'type': 'float64'},
                'nav_pct_psv': {'desc': '指数投资持有股票市值占净资产比例(%)', 'type': 'float64'},
                'is_stat': {'desc': '是否参与统计', 'type': 'str'},
                'remark': {'desc': '备注', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_PFL_INDUSTRY': {
        'source_table': 'AIWEFUND.FUND_PFL_INDUSTRY',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金投资组合（行业）',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/投资组合',
            'rank': 1009003,
            'friendly_name': '基金投资组合（行业）',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'end_dt', 'indu_nm', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'end_dt': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'indu_cd': {'desc': '行业代码', 'type': 'str'},
                'indu_val': {'desc': '市值', 'type': 'float64'},
                'indu_val_pos': {'desc': '其中：积极投资部分（市值）', 'type': 'float64'},
                'indu_val_pas': {'desc': '其中：指数投资部分（市值）', 'type': 'float64'},
                'indu_rat': {'desc': '市值占净资产的比例', 'type': 'float64'},
                'indu_rat_pos': {'desc': '其中：积极投资部分（市值占净资产的比例）', 'type': 'float64'},
                'indu_rat_pas': {'desc': '其中：指数投资部分（市值占净资产的比例）', 'type': 'float64'},
                'is_stat': {'desc': '是否参与统计', 'type': 'str'},
                'indu_nm': {'desc': '行业名称', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
            },
        },
    },
    'FUND_PFL_ASSET': {
        'source_table': 'AIWEFUND.FUND_PFL_ASSET',
        'date': 'end_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'smb',
        'schema': {
            'desc': '基金投资组合_资产配置表',
            'active': True,
            'date_field': 'date',
            'category': '基金(原表)/投资组合',
            'rank': 1009004,
            'friendly_name': '基金投资组合_资产配置表',
            'partition_date': None,
            'primary_key': ['fnd_cd', 'end_dt', 'instrument', 'date'],
            'fields': {
                'fnd_cd': {'desc': '基金内部编码', 'type': 'str'},
                'end_dt': {'desc': '截止日期', 'type': 'datetime64[ns]'},
                'nav': {'desc': '基金净值总额', 'type': 'float64'},
                'tot_ast': {'desc': '基金总资产', 'type': 'float64'},
                'eqt_mkv': {'desc': '1.权益投资市值', 'type': 'float64'},
                'eqt_rat': {'desc': '权益投资占净值比例', 'type': 'float64'},
                'stk_mkv': {'desc': 'A.其中:股票投资市值', 'type': 'float64'},
                'stk_rat': {'desc': '股票投资占净值比例', 'type': 'float64'},
                'dr_mkv': {'desc': 'B.存托凭证市值', 'type': 'float64'},
                'dr_rat': {'desc': '存托凭证占净值比例', 'type': 'float64'},
                'reits_mkv': {'desc': 'C.房地产信托凭证', 'type': 'float64'},
                'reits_rat': {'desc': '房地产信托凭证占净值比例', 'type': 'float64'},
                'fix_inc_mkv': {'desc': '2.固定收益投资市值', 'type': 'float64'},
                'fix_inc_rat': {'desc': '固定收益投资占净值比例', 'type': 'float64'},
                'bnd_mkv': {'desc': 'A.其中:债券投资市值', 'type': 'float64'},
                'bnd_rat': {'desc': '债券投资占净值比例', 'type': 'float64'},
                'trsr_bnd_mkv': {'desc': '1)国债市值', 'type': 'float64'},
                'trsr_bnd_rat': {'desc': '国债占净值比例', 'type': 'float64'},
                'cbb_mkv': {'desc': '2)央行票据', 'type': 'float64'},
                'cbb_rat': {'desc': '央行票据占净值比例', 'type': 'float64'},
                'fin_dbt_mkv': {'desc': '3)金融债市值', 'type': 'float64'},
                'fin_dbt_rat': {'desc': '金融债占净值比例', 'type': 'float64'},
                'plcy_fin_dbt_mkv': {'desc': 'a)其中:政策性金融债', 'type': 'float64'},
                'plcy_fin_dbt_rat': {'desc': '政策性金融债占净值比例', 'type': 'float64'},
                'entp_dbt_mkv': {'desc': '4)企业债市值', 'type': 'float64'},
                'entp_dbt_rat': {'desc': '企业债占净值比例', 'type': 'float64'},
                'st_fin_mkv': {'desc': '5)企业短期融资券', 'type': 'float64'},
                'st_fin_rat': {'desc': '企业短期融资券占净值比例', 'type': 'float64'},
                'mtn_mkv': {'desc': '6)中期票据', 'type': 'float64'},
                'mtn_rat': {'desc': '中期票据占净值比例', 'type': 'float64'},
                'cnv_bnd_mkv': {'desc': '7)可转换债券市值', 'type': 'float64'},
                'cnv_bnd_rat': {'desc': '可转债占净值比例', 'type': 'float64'},
                'priv_mkv': {'desc': '8)中小企业私募债券市值', 'type': 'float64'},
                'priv_rat': {'desc': '中小企业私募债券占净值比例', 'type': 'float64'},
                'ncds_mkv': {'desc': '9)同业存单', 'type': 'float64'},
                'ncds_rat': {'desc': '同业存单占净值比例', 'type': 'float64'},
                'loc_gov_dbt_mkv': {'desc': '10)地方政府债', 'type': 'float64'},
                'loc_gov_dbt_rat': {'desc': '地方政府债占净值比例', 'type': 'float64'},
                'oth_bnd_mkv': {'desc': '11)其他债券', 'type': 'float64'},
                'oth_bnd_rat': {'desc': '其他债券占净值比例', 'type': 'float64'},
                'abs_mkv': {'desc': 'B.资产支持证券投资市值', 'type': 'float64'},
                'abs_rat': {'desc': '资产支持证券投资占净值比例', 'type': 'float64'},
                'fnd_mkv': {'desc': '3.基金投资市值合计', 'type': 'float64'},
                'fnd_rat': {'desc': '基金投资市值占净值比例', 'type': 'float64'},
                'fin_deri_mkv': {'desc': '4.金融衍生品投资市值', 'type': 'float64'},
                'fin_deri_rat': {'desc': '金融衍生品投资占净值比例', 'type': 'float64'},
                'fwd_mkv': {'desc': 'A.其中:远期投资市值', 'type': 'float64'},
                'fwd_rat': {'desc': '远期投资占净值比例', 'type': 'float64'},
                'ftr_mkv': {'desc': 'B.期货投资市值', 'type': 'float64'},
                'ftr_rat': {'desc': '期货投资占净值比例', 'type': 'float64'},
                'opt_mkv': {'desc': 'C.期权投资市值', 'type': 'float64'},
                'opt_rat': {'desc': '期权投资占净值比例', 'type': 'float64'},
                'wrnt_mkv': {'desc': 'D.权证投资市值', 'type': 'float64'},
                'wrnt_rat': {'desc': '权证投资占净值比例', 'type': 'float64'},
                'sec_slbk_mkv': {'desc': '5.买入返售金融资产投资市值', 'type': 'float64'},
                'sec_slbk_rat': {'desc': '买入返售金融资产投资占净值比例', 'type': 'float64'},
                'mmi_mkv': {'desc': '6.货币市场工具投资市值', 'type': 'float64'},
                'mmi_rat': {'desc': '货币市场工具投资占净值比例', 'type': 'float64'},
                'dps_rsv': {'desc': '7.银行存款和结算备付金投资市值合计', 'type': 'float64'},
                'dps_rsv_rat': {'desc': '银行存款和结算备付金投资占净值比例', 'type': 'float64'},
                'dps': {'desc': 'A.银行存款', 'type': 'float64'},
                'dps_rat': {'desc': '银行存款占净值比例', 'type': 'float64'},
                'cle_rsv': {'desc': 'B.清算备付金', 'type': 'float64'},
                'cle_rsv_rat': {'desc': '清算备付金占净值比例', 'type': 'float64'},
                'oth_mkv': {'desc': '8.其他投资市值', 'type': 'float64'},
                'oth_rat': {'desc': '其他投资占净值比例', 'type': 'float64'},
                'pms_inv': {'desc': '9.贵金属投资', 'type': 'float64'},
                'pms_rat': {'desc': '贵金属投资占净值比例', 'type': 'float64'},
                'sec_rp_mkv': {'desc': '卖出回购证券余额', 'type': 'float64'},
                'sec_rp_rat': {'desc': '卖出回购证券占净值比例', 'type': 'float64'},
                'crd_bal': {'desc': '贷方余额', 'type': 'float64'},
                'crd_bal_rat': {'desc': '贷方余额占净值比例', 'type': 'float64'},
                'tot_inv': {'desc': '投资市值合计', 'type': 'float64'},
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'is_stat': {'desc': '是否参与统计', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '证券代码', 'type': 'str'},
                'date': {'desc': '截止日期', 'type': 'datetime64[ns]'},
            },
        },
    },

}


if __name__ == "__main__":
    pass
    print(",".join(list(TABLES_MAPS.keys())))
    # for table in TABLES_MAPS:
    #     print(table, len(list(TABLES_MAPS[table]['schema']['fields'].keys())))
