TABLES_MAPS = {
    # 全局-交易日期-交易日期表
    'REF_CALENDAR': {
        'source_table': 'AIWEGLOBAL.REF_CALENDAR',
        'date': 'cld_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'exg_cd',
        'schema': {
            'desc': '交易日历表',
            'active': True,
            'date_field': 'date',
            'category': '全局(原表)/交易日期',
            'rank': 1000001,
            'friendly_name': '交易日历表',
            'partition_date': None,
            'primary_key': ['exg_cd', 'cld_dt', 'instrument'],
            'fields': {
                'exg_cd': {'desc': '交易所内部编码', 'type': 'str'},
                'cld_dt': {'desc': '日期', 'type': 'datetime64[ns]'},
                'is_trd_dt': {'desc': '交易日标识', 'type': 'str'},
                'is_eow': {'desc': '是否周末', 'type': 'str'},
                'is_eom': {'desc': '是否月末', 'type': 'str'},
                'is_eoq': {'desc': '是否季末', 'type': 'str'},
                'is_eoy': {'desc': '是否年末', 'type': 'str'},
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '交易所内部编码', 'type': 'str'},
                'date': {'desc': '日期', 'type': 'datetime64[ns]'},
            },
        },
    },

    # 全局-常量-地域常量表
    'REF_REGION': {
        'source_table': 'AIWEGLOBAL.REF_REGION',
        'date': None,
        'date_format': None,
        'instrument': None,
        'schema': {
            'desc': '地域常量表',
            'active': True,
            'date_field': None,
            'category': '全局(原表)/常量',
            'rank': 1000001,
            'friendly_name': '地域常量表',
            'partition_date': None,
            'primary_key': ['rgn_cd'],
            'fields': {
                'rgn_cd': {'desc': '地域内部编码', 'type': 'str'},
                'chn_nm': {'desc': '中文名称', 'type': 'str'},
                'chn_sht_nm': {'desc': '中文简称', 'type': 'str'},
                'eng_nm': {'desc': '英文名称', 'type': 'str'},
                'eng_sht_nm': {'desc': '英文简称', 'type': 'str'},
                'iso_3n_cd': {'desc': 'ISO编码', 'type': 'str'},
                'iso_3l_cd': {'desc': '阿尔法-3码', 'type': 'str'},
                'iso_2l_cd': {'desc': '阿尔法-2码', 'type': 'str'},
                'prn_rgn_cd': {'desc': '父级编码', 'type': 'str'},
                'rgn_lvl': {'desc': '地域层级', 'type': 'int64'},
                'tm_zon_cd': {'desc': '时区编码', 'type': 'str'},
                'afl_ctn': {'desc': '所属洲', 'type': 'str'},
                'afl_cnr': {'desc': '所属国家', 'type': 'str'},
                'afl_pvc': {'desc': '所属省份', 'type': 'str'},
                'afl_cty': {'desc': '所属城市', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},
            },
        },
    },

    # 主体-基本资料-主体基本资料 # 实际存在aiweglobal库中
    'PTY_BASICINFO': {
        'source_table': 'AIWEGLOBAL.PTY_BASICINFO',
        'date': None,
        'date_format': None,
        'instrument': 'pty_cd',
        'schema': {
            'desc': '主体基本资料表',
            'active': True,
            'date_field': None,
            'category': '全局(原表)/主体',
            'rank': 1000011,
            'friendly_name': '主体基本资料表',
            'partition_date': None,
            'primary_key': ['pty_cd', 'instrument'],
            'fields': {
                'pty_cd': {'desc': '公司内部编码', 'type': 'str'},
                'chn_nm': {'desc': '中文全称', 'type': 'str'},
                'chn_sht_nm': {'desc': '中文简称', 'type': 'str'},
                'eng_nm': {'desc': '英文全称', 'type': 'str'},
                'eng_sht_nm': {'desc': '英文简称', 'type': 'str'},
                'found_dt': {'desc': '成立日期', 'type': 'datetime64[ns]'},
                'pty_dscr': {'desc': '简介', 'type': 'str'},
                'reg_addr': {'desc': '注册地址', 'type': 'str'},
                'reg_zip': {'desc': '注册地址邮编', 'type': 'str'},
                'cnr': {'desc': '国家', 'type': 'str'},
                'pvc': {'desc': '省份', 'type': 'str'},
                'reg_cty': {'desc': '注册所在城市', 'type': 'str'},
                'addr_dscr': {'desc': '地区说明', 'type': 'str'},
                'lgp_rprs': {'desc': '法定代表人', 'type': 'str'},
                'org_cd': {'desc': '组织机构代码', 'type': 'str'},
                'crd_cd': {'desc': '统一社会信用代码', 'type': 'str'},
                'reg_cpt': {'desc': '注册资本(元)', 'type': 'float64'},
                'ccy_cd': {'desc': '注册资本币种', 'type': 'str'},
                'bus_lcn': {'desc': '营业执照号码', 'type': 'str'},
                'cnr_tax_reg_nbr': {'desc': '国税登记号码', 'type': 'str'},
                'loc_tax_reg_nbr': {'desc': '地税登记号码', 'type': 'str'},
                'ecn_chr': {'desc': '经济性质', 'type': 'str'},
                'pty_ctg': {'desc': '机构类别', 'type': 'str'},
                'is_fin_inst': {'desc': '是否金融机构', 'type': 'int64'},
                'ofc_adr': {'desc': '办公地址', 'type': 'str'},
                'ofc_adr_zip': {'desc': '办公地址邮编', 'type': 'str'},
                'web_adr': {'desc': '网址', 'type': 'str'},
                'mbx': {'desc': '邮箱', 'type': 'str'},
                'tel_nbr': {'desc': '联系电话', 'type': 'str'},
                'fax': {'desc': '传真', 'type': 'str'},
                'srv_tel': {'desc': '客服电话', 'type': 'str'},
                'srv_fax': {'desc': '客服传真', 'type': 'str'},
                'chairman': {'desc': '董事长', 'type': 'str'},
                'bod_secre': {'desc': '董事会秘书', 'type': 'str'},
                'bod_secre_tel': {'desc': '董秘电话', 'type': 'str'},
                'bod_secre_fax': {'desc': '董秘传真', 'type': 'str'},
                'bod_secre_mbx': {'desc': '董秘电子邮件', 'type': 'str'},
                'gm': {'desc': '总经理', 'type': 'str'},
                'sec_rprs': {'desc': '证券/股证事务代表', 'type': 'str'},
                'sec_rprs_tel': {'desc': '证券事务代表电话', 'type': 'str'},
                'sec_rprs_fax': {'desc': '证券事务代表传真', 'type': 'str'},
                'sec_rprs_mbx': {'desc': '证券事务代表电子邮件', 'type': 'str'},
                'pbl_web_adr': {'desc': '信息披露网址', 'type': 'str'},
                'pbl_ppr': {'desc': '信息披露报纸', 'type': 'str'},
                'aut_rprs': {'desc': '董秘授权代表', 'type': 'str'},
                'law_csl': {'desc': '法律顾问', 'type': 'str'},
                'act_firm': {'desc': '会计师事务所', 'type': 'str'},
                'mjr_bus': {'desc': '主营业务', 'type': 'str'},
                'bus_scp': {'desc': '经营范围', 'type': 'str'},
                'emp_nbr': {'desc': '员工人数', 'type': 'float64'},
                'cls_dt': {'desc': '存续截止日', 'type': 'datetime64[ns]'},
                'sts': {'desc': '存续状态', 'type': 'str'},
                # 'ch_ecn_chr': {'desc': '财汇经济性质', 'type': 'str'},
                # 'ch_pty_typ': {'desc': '财汇机构类别', 'type': 'str'},
                # 'wind_ecn_chr': {'desc': '万得经济性质', 'type': 'str'},
                # 'wind_pty_typ': {'desc': '万得机构类别', 'type': 'str'},
                # 没要 财汇经济性质 财汇机构类别 万得经济性质 万得机构类别；前面有经济性质和机构类别字段
                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'str'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'str'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'instrument': {'desc': '公司内部编码', 'type': 'str'},

            },
        },
    },
    # 主体-基本资料-主体行业分类表 # 实际存在aiweglobal库中
    'PTY_INDUSTRY': {
        'source_table': 'AIWEGLOBAL.PTY_INDUSTRY',
        'date': 'start_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'pty_cd',
        'schema': {
            'desc': '主体行业分类表',
            'active': True,
            'date_field': 'date',
            'category': '全局(原表)/主体',
            'rank': 1000012,
            'friendly_name': '主体行业分类表',
            'partition_date': None,
            'primary_key': ['idt_sys_cd', 'pty_cd', 'start_dt', 'instrument'],
            'fields': {
                'pty_cd': {'desc': '主体编码', 'type': 'str'},
                'start_dt': {'desc': '变动起始日', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '变动截止日', 'type': 'datetime64[ns]'},
                'idt_sys_cd': {'desc': '行业分类体系内部编码', 'type': 'str'},
                'idt_cd_1st': {'desc': '一级行业分类代码', 'type': 'str'},
                'idt_nm_1st': {'desc': '一级行业分类名称', 'type': 'str'},
                'idt_cd_2nd': {'desc': '二级行业分类代码', 'type': 'str'},
                'idt_nm_2nd': {'desc': '二级行业分类名称', 'type': 'str'},
                'idt_cd_3rd': {'desc': '三级行业分类代码', 'type': 'str'},
                'idt_nm_3rd': {'desc': '三级行业分类名称', 'type': 'str'},
                'idt_cd_4th': {'desc': '四级行业分类代码', 'type': 'str'},
                'idt_nm_4th': {'desc': '四级行业分类名称', 'type': 'str'},
                'cur_sgn': {'desc': '当前标记', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '变动起始日', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '主体编码', 'type': 'str'},
            },
        },
    },
    # 主体-财务报表-主体利润分配表      130字段
    'PTY_FIN_INCOME': {
        'source_table': 'AIWEGLOBAL.PTY_FIN_INCOME',
        'date': 'anc_dt',  # 信息发布日期 非主键，但是它作为时间列来被筛选更符合使用常理
        'date_format': '%Y-%m-%d',
        'instrument': 'pty_cd',
        'schema': {
            'desc': '主体利润分配表',
            'active': True,
            'date_field': 'date',
            'category': '全局(原表)/主体',
            'rank': 1000013,
            'friendly_name': '主体利润分配表',
            'partition_date': 'Y',   # 按年拆分主要是因为字段有点多，理论上条数不会多的
            'primary_key': ['end_dt', 'pty_cd', 'rpt_typ', 'instrument'],
            'fields': {
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'pty_cd': {'desc': '主体内部编码', 'type': 'str'},
                'end_dt': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
                'rpt_trm_typ': {'desc': '报告期类型', 'type': 'str'},
                'rpt_typ': {'desc': '报表类型', 'type': 'str'},
                'pty_typ': {'desc': '主体类型', 'type': 'str'},
                'rpt_cpl': {'desc': '报表完整性', 'type': 'str'},
                'is_adt': {'desc': '是否审计', 'type': 'str'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'dat_src': {'desc': '数据来源', 'type': 'str'},
                'is_act_pbl': {'desc': '是否实际公布', 'type': 'str'},
                'tot_bus_inc': {'desc': '一、营业总收入', 'type': 'float64'},
                'inc_bus': {'desc': '营业收入', 'type': 'float64'},
                'inc_mjr_bus': {'desc': '其中：主营业务收入', 'type': 'float64'},
                'inc_mnr_bus': {'desc': '其中：其他业务收入', 'type': 'float64'},
                'net_inc_int': {'desc': '利息净收入', 'type': 'float64'},
                'inc_int': {'desc': '其中：利息收入', 'type': 'float64'},
                'exp_int': {'desc': '其中：利息支出', 'type': 'float64'},
                'net_inc_cmsn': {'desc': '手续费及佣金净收入', 'type': 'float64'},
                'inc_cmsn': {'desc': '其中:手续费及佣金收入', 'type': 'float64'},
                'exp_cmsn': {'desc': '其中:手续费及佣金支出', 'type': 'float64'},
                'net_inc_agn': {'desc': '代理买卖证券业务净收入', 'type': 'float64'},
                'net_inc_uw': {'desc': '证券承销业务净收入', 'type': 'float64'},
                'net_inc_trust': {'desc': '受托客户资产管理业务净收入', 'type': 'float64'},
                'prem_ern': {'desc': '已赚保费', 'type': 'float64'},
                'inc_prem': {'desc': '保险业务收入', 'type': 'float64'},
                'inc_reins': {'desc': '其中:分保费收入', 'type': 'float64'},
                'prem_out': {'desc': '减:分出保费', 'type': 'float64'},
                'chrg_undue_rsv': {'desc': '提取未到期责任准备金', 'type': 'float64'},
                'inc_real_estt': {'desc': '房地产销售收入', 'type': 'float64'},
                'inc_oth_bus': {'desc': '其他业务收入', 'type': 'float64'},
                'spc_bus_inc': {'desc': '营业总收入差额(特殊报表科目)', 'type': 'float64'},
                'adj_bus_inc': {'desc': '营业总收入差额(合计平衡项目)', 'type': 'float64'},
                'tot_bus_cst': {'desc': '二、营业总成本', 'type': 'float64'},
                'cst_opr': {'desc': '营业成本', 'type': 'float64'},
                'cst_mjr_bus': {'desc': '其中：主营业务成本', 'type': 'float64'},
                'cst_mnr_bus': {'desc': '其中：其他业务成本', 'type': 'float64'},
                'tax_surchrg': {'desc': '营业税金及附加', 'type': 'float64'},
                'fee_sale': {'desc': '销售费用', 'type': 'float64'},
                'fee_mng': {'desc': '管理费用', 'type': 'float64'},
                'fee_fin': {'desc': '财务费用', 'type': 'float64'},
                'fee_int': {'desc': '其中：利息费用', 'type': 'float64'},
                'rvn_int': {'desc': '其中：利息收入', 'type': 'float64'},
                'exp_rd': {'desc': '研发费用', 'type': 'float64'},
                'los_ast_dval': {'desc': '资产减值损失', 'type': 'float64'},
                'los_crd_dval': {'desc': '信用减值损失', 'type': 'float64'},
                'exp_bus': {'desc': '营业支出', 'type': 'float64'},
                'srdr': {'desc': '退保金', 'type': 'float64'},
                'exp_cps': {'desc': '赔付支出', 'type': 'float64'},
                'amrz_cps_exp': {'desc': '减:摊回赔付支出', 'type': 'float64'},
                'rsv_ins': {'desc': '提取保险责任准备金', 'type': 'float64'},
                'amrz_rsv_ins': {'desc': '减:摊回保险责任准备金', 'type': 'float64'},
                'exp_ins_dvd': {'desc': '保单红利支出', 'type': 'float64'},
                'exp_reins': {'desc': '分保费用', 'type': 'float64'},
                'amrz_reins_exp': {'desc': '减:摊回分保费用', 'type': 'float64'},
                'exp_ins_bus': {'desc': '保险业务支出', 'type': 'float64'},
                'cst_real_estt': {'desc': '房地产销售成本', 'type': 'float64'},
                'cst_oth_bus': {'desc': '其他业务成本', 'type': 'float64'},
                'spc_bus_cst': {'desc': '营业总成本差额(特殊报表科目)', 'type': 'float64'},
                'adj_bus_cst': {'desc': '营业总成本差额(合计平衡项目)', 'type': 'float64'},
                'net_rvn_oth': {'desc': '三、非经营性净收益', 'type': 'float64'},
                'inc_fv_chg': {'desc': '公允价值变动净收益', 'type': 'float64'},
                'pft_oth_bus': {'desc': '其他业务利润', 'type': 'float64'},
                'inc_inv': {'desc': '投资净收益', 'type': 'float64'},
                'inc_inv_entp': {'desc': '其中:对联营合营企业的投资收益', 'type': 'float64'},
                'inc_cstd': {'desc': '托管收益', 'type': 'float64'},
                'inc_ftr': {'desc': '期货损益', 'type': 'float64'},
                'inc_hdg': {'desc': '净敞口套期收益', 'type': 'float64'},
                'inc_fx_exg': {'desc': '汇兑收益', 'type': 'float64'},
                'inc_ast_dspl': {'desc': '资产处置收益', 'type': 'float64'},
                'inc_oth': {'desc': '其他收益', 'type': 'float64'},
                'spc_bus_pft': {'desc': '营业利润差额(特殊报表科目)', 'type': 'float64'},
                'adj_bus_pft': {'desc': '营业利润差额(合计平衡项目)', 'type': 'float64'},
                'bus_pft': {'desc': '四、营业利润', 'type': 'float64'},
                'ern_oth': {'desc': '其他业务收入', 'type': 'float64'},
                'inc_alwnc': {'desc': '其中：补贴收入', 'type': 'float64'},
                'gain_ast_disp': {'desc': '其中：非流动资产处置利得', 'type': 'float64'},
                'exp_oth_bus': {'desc': '营业外支出', 'type': 'float64'},
                'los_ast_disp': {'desc': '其中:非流动资产处置净损失', 'type': 'float64'},
                'spc_tot_pft': {'desc': '利润总额差额(特殊报表科目)', 'type': 'float64'},
                'adj_tot_pft': {'desc': '利润总额差额(合计平衡科目）', 'type': 'float64'},
                'tot_pft': {'desc': '五、利润总额', 'type': 'float64'},
                'tax_inc': {'desc': '所得税', 'type': 'float64'},
                'los_inv_uncfm': {'desc': '未确认投资损失', 'type': 'float64'},
                'spc_net_pft': {'desc': '净利润差额(特殊报表科目)', 'type': 'float64'},
                'adj_net_pft': {'desc': '净利润差额(合计平衡科目)', 'type': 'float64'},
                'net_pft': {'desc': '六、净利润', 'type': 'float64'},
                'net_pft_ctn': {'desc': '(一)按经营持续性分类：持续经营净利润', 'type': 'float64'},
                'net_pft_tmn': {'desc': '(一)按经营持续性分类：终止经营净利润', 'type': 'float64'},
                'net_pft_prn': {'desc': '(二)按所有权归属分类：归属于母公司所有者的净利润', 'type': 'float64'},
                'pft_mnr': {'desc': '(二)按所有权归属分类：少数股东损益', 'type': 'float64'},
                'spc_net_pft_prn': {'desc': '母公司净利润差额（特殊报表科目）', 'type': 'float64'},
                'adj_net_pft_prn': {'desc': '母公司净利润差额（合计平衡科目）', 'type': 'float64'},
                'oci': {'desc': '七、其他综合收益', 'type': 'float64'},
                'oci_prn': {'desc': '归属于母公司所有者的其他综合收益', 'type': 'float64'},
                'oci_unrecls': {'desc': '(一)以后不能重分类进损益表的其他综合收益', 'type': 'float64'},
                'chg_rems': {'desc': ' 重新计量设定收益计划净负债或净资产的变动', 'type': 'float64'},
                'shr_eqtm_unrecls': {'desc': '权益法下在被投资单位不能重分类进损益表的其他综合收益中享有的份额', 'type': 'float64'},
                'fv_chg_eqt': {'desc': '其他权益工具投资公允价值变动', 'type': 'float64'},
                'fv_chg_crd': {'desc': '企业自身信用风险公允价值变动', 'type': 'float64'},
                'oci_recls': {'desc': '(二)以后能重分类进损益表的其他综合收益', 'type': 'float64'},
                'shr_eqtm_recls': {'desc': '权益法下在被投资单位能重分类进损益表的其他综合收益中享有的份额', 'type': 'float64'},
                'fv_chg_fsfa': {'desc': '可供出售金融资产公允价值变动损益', 'type': 'float64'},
                'pl_htm_recls': {'desc': '持有至到期投资重分类为可供出售金融资产损益', 'type': 'float64'},
                'cf_hdg': {'desc': '现金流量套期损益的有效部分', 'type': 'float64'},
                'dif_fx_rpt': {'desc': '外币财务报表分析折算差额', 'type': 'float64'},
                'oth': {'desc': '其他', 'type': 'float64'},
                'fv_chg_dbt': {'desc': '其他债权投资公允价值变动', 'type': 'float64'},
                'oci_fa_recls': {'desc': '金融资产重分类计入其他综合收益的金额', 'type': 'float64'},
                'prp_dbt_dval': {'desc': '其他债权投资信用减值准备', 'type': 'float64'},
                'oci_mnr': {'desc': '归属于少数股东的其他综合收益', 'type': 'float64'},
                'spc_oci': {'desc': '综合收益差额（合计平衡科目）', 'type': 'float64'},
                'tot_ci': {'desc': '八、综合收益总额', 'type': 'float64'},
                'ci_prn': {'desc': '归属于母公司所有者的综合收益总额', 'type': 'float64'},
                'ci_mnr': {'desc': '归属于少数股东的综合收益总额', 'type': 'float64'},
                'spc_ci_prn': {'desc': '母公司综合收益差额（合计平衡科目）', 'type': 'float64'},
                'eps_bas': {'desc': '基本每股收益', 'type': 'float64'},
                'eps_dlt': {'desc': '稀释每股收益', 'type': 'float64'},
                'net_pft_prn_ddct': {'desc': '扣除非经常性损益后归母净利润', 'type': 'float64'},
                'net_pft_ddct': {'desc': '扣除非经常性损益后的净利润', 'type': 'float64'},
                'ebit': {'desc': '息税前利润', 'type': 'float64'},
                'ebitda': {'desc': '息税折旧摊销前利润', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '主体内部编码', 'type': 'str'},
            },
        },
    },
    # 主体-财务报表-主体现金流量表      130字段
    'PTY_FIN_CASHFLOW': {
        'source_table': 'AIWEGLOBAL.PTY_FIN_CASHFLOW',
        'date': 'anc_dt',  # 信息发布日期 非主键，但是它作为时间列来被筛选更符合使用常理
        'date_format': '%Y-%m-%d',
        'instrument': 'pty_cd',
        'schema': {
            'desc': '主体现金流量表',
            'active': True,
            'date_field': 'date',
            'category': '全局(原表)/主体',
            'rank': 1000014,
            'friendly_name': '主体现金流量表',
            'partition_date': 'Y',
            'primary_key': ['end_dt', 'pty_cd', 'rpt_typ', 'instrument'],
            'fields': {
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'pty_cd': {'desc': '主体内部编码', 'type': 'str'},
                'end_dt': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
                'rpt_trm_typ': {'desc': '报告期类型', 'type': 'str'},
                'rpt_typ': {'desc': '报表类型', 'type': 'str'},
                'pty_typ': {'desc': '主体类型', 'type': 'str'},
                'rpt_cpl': {'desc': '报表完整性', 'type': 'str'},
                'is_adt': {'desc': '是否审计', 'type': 'int64'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'dat_src': {'desc': '数据来源', 'type': 'str'},
                'is_act_pbl': {'desc': '是否实际公布', 'type': 'str'},
                'rcp_sal_svc': {'desc': '销售商品、提供劳务收到的现金', 'type': 'float64'},
                'rcp_tax_rfnd': {'desc': '收到的税费返还', 'type': 'float64'},
                'icr_dps': {'desc': '客户存款和同业存放款项净增加额', 'type': 'float64'},
                'icr_brw_cntr_bnk': {'desc': '向中央银行借款净增加额', 'type': 'float64'},
                'icr_brw_ofi': {'desc': '向其他金融机构拆入资金净增加额', 'type': 'float64'},
                'icr_brw_oth': {'desc': '拆入资金净增加额', 'type': 'float64'},
                'rcp_int_cmsn': {'desc': '收取利息、手续费及佣金的现金', 'type': 'float64'},
                'icr_dpsl_tfa': {'desc': '处置交易性金融资产净增加额', 'type': 'float64'},
                'icr_rpch': {'desc': '回购业务资金净增加额', 'type': 'float64'},
                'rcp_orig_ins': {'desc': '收到原保险合同保费取得的现金', 'type': 'float64'},
                'rcp_reins': {'desc': '收到再保险业务现金净额', 'type': 'float64'},
                'icr_depo_ins': {'desc': '保户储金及投资款净增加额', 'type': 'float64'},
                'rcp_oth_opr': {'desc': '收到的其他与经营活动有关的现金', 'type': 'float64'},
                'rcp_agt_trd': {'desc': '代理买卖证券收到的现金净额', 'type': 'float64'},
                'spc_ocf_in': {'desc': '经营活动现金流入差额(特殊报表科目)', 'type': 'float64'},
                'adj_ocf_in': {'desc': '经营活动现金流入差额(合计平衡科目)', 'type': 'float64'},
                'ocf_in': {'desc': '经营活动现金流入小计', 'type': 'float64'},
                'pay_gds_svc': {'desc': '购买商品、接受劳务支付的现金', 'type': 'float64'},
                'pay_emp_slr': {'desc': '支付给职工以及为职工支付的现金', 'type': 'float64'},
                'pay_tax': {'desc': '支付的各项税费', 'type': 'float64'},
                'icr_loan_clt': {'desc': '客户贷款及垫款净增加额', 'type': 'float64'},
                'icr_dps_cntr_bnk': {'desc': '存放中央银行和同业款项净增加额', 'type': 'float64'},
                'icr_loan_oth': {'desc': '拆出资金净增加额', 'type': 'float64'},
                'icr_fin_out': {'desc': '融出资金净增加额', 'type': 'float64'},
                'pay_cmsn': {'desc': '支付手续费的现金', 'type': 'float64'},
                'pay_cps_ins': {'desc': '支付原保险合同赔付款项的现金', 'type': 'float64'},
                'pay_dvd_ins': {'desc': '支付保单红利的现金', 'type': 'float64'},
                'pay_oth_opr': {'desc': '支付其他与经营活动有关的现金', 'type': 'float64'},
                'spc_ocf_out': {'desc': '经营活动现金流出差额(特殊报表科目)', 'type': 'float64'},
                'adj_ocf_out': {'desc': '经营活动现金流出差额(合计平衡科目)', 'type': 'float64'},
                'ocf_out': {'desc': '经营活动现金流出小计', 'type': 'float64'},
                'spc_ocf': {'desc': '经营活动产生的现金流量净额差额(特殊报表科目)', 'type': 'float64'},
                'adj_ocf': {'desc': '经营活动产生的现金流量净额差额(合计平衡科目)', 'type': 'float64'},
                'ocf': {'desc': '经营活动产生的现金流量净额', 'type': 'float64'},
                'rcp_disinv': {'desc': '收回投资所收到的现金', 'type': 'float64'},
                'ret_inv': {'desc': '取得投资收益收到的现金', 'type': 'float64'},
                'rcp_dpsl_fiolta': {'desc': '处置固定资产、无形资产和其他长期资产所收回的现金净额', 'type': 'float64'},
                'rcp_dpsl_subcmp': {'desc': '处置子公司及其他营业单位收到的现金净额', 'type': 'float64'},
                'icr_dpsl_afsa': {'desc': '处置可供出售金融资产净增加额', 'type': 'float64'},
                'rcp_oth_inv': {'desc': '收到的其他与投资活动有关的现金', 'type': 'float64'},
                'spc_icf_in': {'desc': '投资活动现金流入差额(特殊报表科目)', 'type': 'float64'},
                'adj_icf_in': {'desc': '投资活动现金流入差额(合计平衡科目)', 'type': 'float64'},
                'icf_in': {'desc': '投资活动现金流入小计', 'type': 'float64'},
                'pay_obt_fiolta': {'desc': '购建固定资产、无形资产和其他长期资产支付的现金', 'type': 'float64'},
                'pay_inv': {'desc': '投资支付的现金', 'type': 'float64'},
                'pay_obt_sub_cmp': {'desc': '取得子公司及其他营业单位支付的现金净额', 'type': 'float64'},
                'icr_plg_loan': {'desc': '质押贷款净增加额', 'type': 'float64'},
                'pay_oth_inv': {'desc': '支付其他与投资活动有关的现金', 'type': 'float64'},
                'spc_icf_out': {'desc': '投资活动现金流出差额(特殊报表科目)', 'type': 'float64'},
                'adj_icf_out': {'desc': '投资活动现金流出差额(合计平衡科目)', 'type': 'float64'},
                'icf_out': {'desc': '投资活动现金流出小计', 'type': 'float64'},
                'spc_icf': {'desc': '投资活动产生的现金流量净额差额(特殊报表科目)', 'type': 'float64'},
                'adj_icf': {'desc': '投资活动产生的现金流量净额差额(合计平衡科目)', 'type': 'float64'},
                'icf': {'desc': '投资活动产生的现金流量净额', 'type': 'float64'},
                'rcp_inv': {'desc': '吸收投资收到的现金', 'type': 'float64'},
                'rcp_inv_sub_cmp': {'desc': '其中:子公司吸收少数股东投资收到的现金', 'type': 'float64'},
                'iss_bnd': {'desc': '发行债券收到的现金', 'type': 'float64'},
                'rcp_brw': {'desc': '取得借款收到的现金', 'type': 'float64'},
                'rcp_oth_fin': {'desc': '收到其他与筹资活动有关的现金', 'type': 'float64'},
                'spc_fcf_in': {'desc': '筹资活动现金流入差额(特殊报表科目)', 'type': 'float64'},
                'adj_fcf_in': {'desc': '筹资活动现金流入差额(合计平衡科目)', 'type': 'float64'},
                'fcf_in': {'desc': '筹资活动现金流入小计', 'type': 'float64'},
                'pay_dbt': {'desc': '偿还债务支付的现金', 'type': 'float64'},
                'pay_dvd': {'desc': '分配股利、利润或偿付利息支付的现金', 'type': 'float64'},
                'pay_dvd_sub_cmp': {'desc': '其中:子公司支付给少数股东的股利、利润或偿付的利息', 'type': 'float64'},
                'pay_oth_fin': {'desc': '支付其他与筹资活动有关的现金', 'type': 'float64'},
                'spc_fcf_out': {'desc': '筹资活动现金流出差额(特殊报表科目)', 'type': 'float64'},
                'adj_fcf_out': {'desc': '筹资活动现金流出差额(合计平衡科目)', 'type': 'float64'},
                'fcf_out': {'desc': '筹资活动现金流出小计', 'type': 'float64'},
                'spc_fcf': {'desc': '筹资活动产生的现金流量净额差额(特殊报表科目)', 'type': 'float64'},
                'adj_fcf': {'desc': '筹资活动产生的现金流量净额差额(合计平衡科目)', 'type': 'float64'},
                'fcf': {'desc': '筹资活动产生的现金流量净额', 'type': 'float64'},
                'eft_fx_flct': {'desc': '汇率变动对现金及现金等价物的影响', 'type': 'float64'},
                'spc_csh_eqv': {'desc': '现金及现金等价物差额(特殊报表科目)', 'type': 'float64'},
                'adj_csh_eqv': {'desc': '现金及现金等价物差额(合计平衡科目)', 'type': 'float64'},
                'icr_csh_eqv': {'desc': '现金及现金等价物净增加额', 'type': 'float64'},
                'csh_eqv_sop': {'desc': '期初现金及现金等价物余额', 'type': 'float64'},
                'spc_csh_eqv_eop': {'desc': '期末现金及现金等价物差额(特殊报表科目)', 'type': 'float64'},
                'adj_csh_eqv_eop': {'desc': '期末现金及现金等价物差额(合计平衡科目)', 'type': 'float64'},
                'csh_eqv_eop': {'desc': '期末现金及现金等价物余额', 'type': 'float64'},
                'net_pft': {'desc': '净利润', 'type': 'float64'},
                'pft_mnr': {'desc': '少数股东损益', 'type': 'float64'},
                'prp_fix_dval': {'desc': '资产减值准备', 'type': 'float64'},
                'los_inv_uncfm': {'desc': '未确认的投资损失', 'type': 'float64'},
                'depr_fix_ast': {'desc': '固定资产折旧', 'type': 'float64'},
                'depr_real_estt': {'desc': '投资性房地产折旧、摊销', 'type': 'float64'},
                'amrz_intang_ast': {'desc': '无形资产摊销', 'type': 'float64'},
                'amrz_exp_lt_df': {'desc': '长期待摊费用摊销', 'type': 'float64'},
                'dcr_exp_df': {'desc': '待摊费用减少(减:增加)', 'type': 'float64'},
                'icr_exp_accr': {'desc': '预提费用增加(减:减少)', 'type': 'float64'},
                'los_dpsl_fiolta': {'desc': '处置固定资产、无形资产和其他长期资产的损失', 'type': 'float64'},
                'los_fa_scrap': {'desc': '固定资产报废损失', 'type': 'float64'},
                'los_fv_chg': {'desc': '公允价值变动损失', 'type': 'float64'},
                'fee_fin': {'desc': '财务费用', 'type': 'float64'},
                'los_inv': {'desc': '投资损失', 'type': 'float64'},
                'dcr_df_tax_ast': {'desc': '递延所得税资产减少', 'type': 'float64'},
                'icr_df_tax_lbl': {'desc': '递延所得税负债增加', 'type': 'float64'},
                'dcr_ivtr': {'desc': '存货的减少', 'type': 'float64'},
                'dcr_opr_rcp': {'desc': '经营性应收项目的减少', 'type': 'float64'},
                'icr_opr_pay': {'desc': '经营性应付项目的增加', 'type': 'float64'},
                'oth': {'desc': '其他', 'type': 'float64'},
                'spc_ocf_indir': {'desc': '间接法-经营活动现金流量净额差额(特殊报表科目)', 'type': 'float64'},
                'adj_ocf_indir': {'desc': '间接法-经营活动现金流量净额差额(合计平衡科目)', 'type': 'float64'},
                'ocf_indir': {'desc': '间接法-经营活动产生的现金流量净额', 'type': 'float64'},
                'adj_ocf_bil': {'desc': '主附表经营活动现金流量净额差额(合计平衡科目)', 'type': 'float64'},
                'dbt_to_cpt': {'desc': '债务转为资本', 'type': 'float64'},
                'cb_due_1y': {'desc': '一年内到期的可转换公司债券', 'type': 'float64'},
                'fix_ast_fin_lse': {'desc': '融资租入固定资产', 'type': 'float64'},
                'csh_eop': {'desc': '现金的期末余额', 'type': 'float64'},
                'csh_sop': {'desc': '减:现金的期初余额', 'type': 'float64'},
                'eqv_eop': {'desc': '加:现金等价物的期末余额', 'type': 'float64'},
                'eqv_sop': {'desc': '减:现金等价物的期初余额', 'type': 'float64'},
                'spc_csh_eqv_indir': {'desc': '间接法-现金及现金等价物净增加额差额(特殊报表科目)', 'type': 'float64'},
                'adj_csh_eqv_indir': {'desc': '间接法-现金及现金等价物净增加额差额(合计平衡科目)', 'type': 'float64'},
                'icr_csh_eqv_indir': {'desc': '间接法-现金及现金等价物净增加额', 'type': 'float64'},
                'adj_csh_eqv_bil': {'desc': '主附表现金及现金等价物净增加额差额(合计平衡科目)', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '主体内部编码', 'type': 'str'},
            },
        },
    },
    # 主体-财务报表-主体资产负债表    190左右字段
    'PTY_FIN_BALANCE': {
        'source_table': 'AIWEGLOBAL.PTY_FIN_BALANCE',
        'date': 'anc_dt',   # 信息发布日期 非主键，但是它作为时间列来被筛选更符合使用常理
        'date_format': '%Y-%m-%d',
        'instrument': 'pty_cd',
        'schema': {
            'desc': '主体资产负债表',
            'active': True,
            'date_field': 'date',
            'category': '全局(原表)/主体',
            'rank': 1000015,
            'friendly_name': '主体资产负债表',
            'partition_date': 'Y',
            'primary_key': ['end_dt', 'pty_cd', 'rpt_typ', 'instrument'],
            'fields': {
                'anc_dt': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'pty_cd': {'desc': '主体内部编码', 'type': 'str'},
                'end_dt': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
                'rpt_trm_typ': {'desc': '报告期类型', 'type': 'str'},
                'rpt_typ': {'desc': '报表类型', 'type': 'str'},
                'pty_typ': {'desc': '主体类型', 'type': 'str'},
                'rpt_cpl': {'desc': '报表完整性', 'type': 'str'},
                'is_adt': {'desc': '是否审计', 'type': 'str'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'dat_src': {'desc': '数据来源', 'type': 'str'},
                'is_act_pbl': {'desc': '是否实际公布', 'type': 'str'},
                'mny_fund': {'desc': '货币资金', 'type': 'float64'},
                'dps_clt': {'desc': '其中：客户资金存款', 'type': 'float64'},
                'mny_fin_out': {'desc': '融出资金', 'type': 'float64'},
                'fin_ast_tras': {'desc': '交易性金融资产', 'type': 'float64'},
                'rcv_bil_acc': {'desc': '应收票据及应收账款', 'type': 'float64'},
                'rcv_bil': {'desc': '应收票据', 'type': 'float64'},
                'rcv_acc': {'desc': '应收账款', 'type': 'float64'},
                'prepay': {'desc': '预付款项', 'type': 'float64'},
                'rcv_int': {'desc': '应收利息', 'type': 'float64'},
                'rcv_dvd': {'desc': '应收股利', 'type': 'float64'},
                'rcv_mrgn': {'desc': '应收保证金', 'type': 'float64'},
                'rcv_oth': {'desc': '其他应收款', 'type': 'float64'},
                'rcv_oth_tot': {'desc': '其他应收款（合计）', 'type': 'float64'},
                'ivtr': {'desc': '存货', 'type': 'float64'},
                'ast_bio_csm': {'desc': '其中：消耗性生物资产', 'type': 'float64'},
                'ast_hfs': {'desc': '划分为持有待售的资产', 'type': 'float64'},
                'exp_df': {'desc': '待摊费用', 'type': 'float64'},
                'ast_noncur_1y': {'desc': '一年内到期的非流动资产', 'type': 'float64'},
                'ast_ctr': {'desc': '合同资产', 'type': 'float64'},
                'ast_oth_cur': {'desc': '其他流动资产', 'type': 'float64'},
                'spc_ast_cur': {'desc': '流动资产差额（归并报表科目）', 'type': 'float64'},
                'adj_ast_cur': {'desc': '流动资产差额（合计平衡科目）', 'type': 'float64'},
                'ast_cur': {'desc': '流动资产合计', 'type': 'float64'},
                'fin_ast_afs': {'desc': '可供出售金融资产', 'type': 'float64'},
                'inv_htm': {'desc': '持有至到期投资', 'type': 'float64'},
                'rcv_lt': {'desc': '长期应收款', 'type': 'float64'},
                'eqt_inv_lt': {'desc': '长期股权投资', 'type': 'float64'},
                'eqt_inv_oth': {'desc': '其他权益工具投资', 'type': 'float64'},
                'fin_ast_oth_noncur': {'desc': '其他非流动金融资产', 'type': 'float64'},
                'inv_dbt': {'desc': '债权投资', 'type': 'float64'},
                'inv_dbt_oth': {'desc': '其他债权投资', 'type': 'float64'},
                'inv_real_estt': {'desc': '投资性房地产', 'type': 'float64'},
                'ast_fix_orig': {'desc': '固定资产原值', 'type': 'float64'},
                'acm_depr_fix': {'desc': '累计折旧', 'type': 'float64'},
                'ast_fix_rm': {'desc': '固定资产净值', 'type': 'float64'},
                'prp_fix_dval': {'desc': '固定资产减值准备', 'type': 'float64'},
                'ast_fix': {'desc': '固定资产净额', 'type': 'float64'},
                'fix_ast_disp': {'desc': '固定资产清理', 'type': 'float64'},
                'ast_fix_tot': {'desc': '固定资产（合计）', 'type': 'float64'},
                'cstrc_prj': {'desc': '在建工程', 'type': 'float64'},
                'prj_mat': {'desc': '工程物资', 'type': 'float64'},
                'cstrc_prj_tot': {'desc': '在建工程（合计）', 'type': 'float64'},
                'ast_bio': {'desc': '生产性生物资产', 'type': 'float64'},
                'ast_oil': {'desc': '油气资产', 'type': 'float64'},
                'ast_intang': {'desc': '无形资产', 'type': 'float64'},
                'exp_dvlp': {'desc': '开发支出', 'type': 'float64'},
                'gdwl': {'desc': '商誉', 'type': 'float64'},
                'exp_lt_df': {'desc': '长期待摊费用', 'type': 'float64'},
                'ast_df_tax': {'desc': '递延所得税资产', 'type': 'float64'},
                'ast_oth_noncur': {'desc': '其他非流动资产', 'type': 'float64'},
                'spc_ast_noncur': {'desc': '非流动资产差额（归并报表科目）', 'type': 'float64'},
                'adj_ast_noncur': {'desc': '非流动资产差额（合计平衡科目）', 'type': 'float64'},
                'ast_noncur': {'desc': '非流动资产合计', 'type': 'float64'},
                'csh_dps_cntr_bnk': {'desc': '现金及存放中央银行款项', 'type': 'float64'},
                'inv_rcv': {'desc': '应收款项类投资', 'type': 'float64'},
                'rsv_stl': {'desc': '结算备付金', 'type': 'float64'},
                'rsv_clt': {'desc': '其中：客户备付金', 'type': 'float64'},
                'ast_dps_ib': {'desc': '存放同业款项', 'type': 'float64'},
                'pms': {'desc': '贵金属', 'type': 'float64'},
                'mny_lend_out': {'desc': '拆出资金', 'type': 'float64'},
                'fin_ast_deri': {'desc': '衍生金融资产', 'type': 'float64'},
                'fin_ast_slbk': {'desc': '买入返售金融资产', 'type': 'float64'},
                'loan_out': {'desc': '发放贷款及垫款', 'type': 'float64'},
                'rcv_prem': {'desc': '应收保费', 'type': 'float64'},
                'rcv_subr': {'desc': '应收代位追偿款', 'type': 'float64'},
                'rcv_reins': {'desc': '应收分保账款', 'type': 'float64'},
                'rcv_reins_undue': {'desc': '应收分保未到期责任准备金', 'type': 'float64'},
                'rcv_reins_clm': {'desc': '应收分保未决赔款准备金', 'type': 'float64'},
                'rcv_reins_life': {'desc': '应收分保寿险责任准备金', 'type': 'float64'},
                'rcv_reins_health': {'desc': '应收分保长期健康险责任准备金', 'type': 'float64'},
                'rcv_rsv_reins': {'desc': '应收分保合同准备金', 'type': 'float64'},
                'lend_plg': {'desc': '保户质押贷款', 'type': 'float64'},
                'dps_fix': {'desc': '定期存款', 'type': 'float64'},
                'mrgn_paid': {'desc': '存出保证金', 'type': 'float64'},
                'cpt_mrgn_paid': {'desc': '存出资本保证金', 'type': 'float64'},
                'indep_act_ast': {'desc': '独立账户资产', 'type': 'float64'},
                'ast_oth': {'desc': '其他资产', 'type': 'float64'},
                'ast_oth_itm': {'desc': '其它资产类科目', 'type': 'float64'},
                'spc_ast': {'desc': '总资产差额（归并报表科目）', 'type': 'float64'},
                'adj_ast': {'desc': '总资产差额（合计平衡科目）', 'type': 'float64'},
                'ast_tot': {'desc': '资产总计', 'type': 'float64'},
                'brw_st': {'desc': '短期借款', 'type': 'float64'},
                'fin_lbl_tras': {'desc': '交易性金融负债', 'type': 'float64'},
                'pay_bil_act': {'desc': '应付票据及应付账款', 'type': 'float64'},
                'pay_bil': {'desc': '应付票据', 'type': 'float64'},
                'pay_act': {'desc': '应付账款', 'type': 'float64'},
                'rcp_adv': {'desc': '预收款项', 'type': 'float64'},
                'pay_emp_slr': {'desc': '应付职工薪酬', 'type': 'float64'},
                'pay_tax': {'desc': '应交税费', 'type': 'float64'},
                'pay_mrgn': {'desc': '应付保证金', 'type': 'float64'},
                'pay_intr': {'desc': '应付利息', 'type': 'float64'},
                'pay_dvd': {'desc': '应付股利', 'type': 'float64'},
                'pay_oth': {'desc': '其他应付款', 'type': 'float64'},
                'pay_oth_tot': {'desc': '其他应付款（合计）', 'type': 'float64'},
                'exp_accr': {'desc': '预提费用', 'type': 'float64'},
                'df_reve_1y': {'desc': '一年内的递延收益', 'type': 'float64'},
                'pay_st_bnd': {'desc': '应付短期债券', 'type': 'float64'},
                'pay_st_fin': {'desc': '应付短期融资款', 'type': 'float64'},
                'lbl_hfs': {'desc': '划分为持有待售的负债', 'type': 'float64'},
                'lbl_noncur_1y': {'desc': '一年内到期的非流动负债', 'type': 'float64'},
                'lbl_ctr': {'desc': '合同负债', 'type': 'float64'},
                'lbl_oth_cur': {'desc': '其他流动负债', 'type': 'float64'},
                'spc_lbl_cur': {'desc': '流动负债差额（归并报表科目）', 'type': 'float64'},
                'adj_lbl_cur': {'desc': '流动负债差额（合计平衡科目）', 'type': 'float64'},
                'lbl_cur': {'desc': '流动负债合计', 'type': 'float64'},
                'pay_loan_lt': {'desc': '长期借款', 'type': 'float64'},
                'pay_emp_slr_lt': {'desc': '长期应付职工薪酬', 'type': 'float64'},
                'pay_bnd': {'desc': '应付债券', 'type': 'float64'},
                'pay_pref_stk': {'desc': '其中：优先股', 'type': 'float64'},
                'pay_ppt_bnd': {'desc': '其中：永续债', 'type': 'float64'},
                'pay_lt': {'desc': '长期应付款', 'type': 'float64'},
                'pay_lt_tot': {'desc': '长期应付款（合计）', 'type': 'float64'},
                'pay_spc_itm': {'desc': '专项应付款', 'type': 'float64'},
                'lbl_xpc': {'desc': '预计负债', 'type': 'float64'},
                'df_reve_lt': {'desc': '长期递延收益', 'type': 'float64'},
                'lbl_df_tax': {'desc': '递延所得税负债', 'type': 'float64'},
                'rsv_cps': {'desc': '担保责任赔偿准备金', 'type': 'float64'},
                'lbl_oth_noncur': {'desc': '其他非流动负债', 'type': 'float64'},
                'spc_lbl_noncur': {'desc': '非流动负债差额（归并报表科目）', 'type': 'float64'},
                'adj_lbl_noncur': {'desc': '非流动负债差额（合计平衡科目）', 'type': 'float64'},
                'lbl_noncur': {'desc': '非流动负债合计', 'type': 'float64'},
                'brw_cntr_bnk': {'desc': '向中央银行借款', 'type': 'float64'},
                'lbl_dps_ib': {'desc': '同业和其它金融机构存放款项', 'type': 'float64'},
                'mny_loan_in': {'desc': '拆入资金', 'type': 'float64'},
                'fin_lbl_deri': {'desc': '衍生金融负债', 'type': 'float64'},
                'fnd_rp': {'desc': '卖出回购金融资产款', 'type': 'float64'},
                'lbl_dps_clc': {'desc': '吸收存款', 'type': 'float64'},
                'lbl_dps': {'desc': '吸收存款及同业存放', 'type': 'float64'},
                'fnd_agt_trd': {'desc': '代理买卖证券款', 'type': 'float64'},
                'fnd_agt_uw': {'desc': '代理承销证券款', 'type': 'float64'},
                'rcp_mrgn': {'desc': '存入保证金', 'type': 'float64'},
                'rcp_prem_adv': {'desc': '预收保费', 'type': 'float64'},
                'pay_cmsn': {'desc': '应付手续费及佣金', 'type': 'float64'},
                'pay_reins': {'desc': '应付分保账款', 'type': 'float64'},
                'pay_cps': {'desc': '应付赔付款', 'type': 'float64'},
                'pay_ins_dvd': {'desc': '应付保单红利', 'type': 'float64'},
                'depo_ins': {'desc': '保户储金及投资款', 'type': 'float64'},
                'rsv_undue_lbl': {'desc': '未到期责任准备金', 'type': 'float64'},
                'rsv_clm': {'desc': '未决赔款准备金', 'type': 'float64'},
                'rsv_life_ins': {'desc': '寿险责任准备金', 'type': 'float64'},
                'rsv_lt_hlth': {'desc': '长期健康险责任准备金', 'type': 'float64'},
                'rsv_ins_ctr': {'desc': '保险合同准备金', 'type': 'float64'},
                'lbl_indep_act': {'desc': '独立账户负债', 'type': 'float64'},
                'lbl_oth_itm': {'desc': '其它负债类科目', 'type': 'float64'},
                'spc_lbl': {'desc': '负债差额（归并报表科目）', 'type': 'float64'},
                'adj_lbl': {'desc': '负债差额（合计平衡科目）', 'type': 'float64'},
                'lbl_tot': {'desc': '负债合计', 'type': 'float64'},
                'cpt_stk': {'desc': '实收资本（或股本）', 'type': 'float64'},
                'eqt_oth': {'desc': '其他权益工具', 'type': 'float64'},
                'eqt_pref_stk': {'desc': '其中：优先股', 'type': 'float64'},
                'eqt_ppt_bnd': {'desc': '其中：永续债', 'type': 'float64'},
                'rsv_cpt': {'desc': '资本公积', 'type': 'float64'},
                'stk_tsy': {'desc': '减：库存股', 'type': 'float64'},
                'oth_inc': {'desc': '其他综合收益', 'type': 'float64'},
                'rsv_spc': {'desc': '专项储备', 'type': 'float64'},
                'rsv_splus': {'desc': '盈余公积', 'type': 'float64'},
                'rsv_risk': {'desc': '一般风险准备', 'type': 'float64'},
                'uncfm_los_inv': {'desc': '未确定的投资损失', 'type': 'float64'},
                'undtrb_pft': {'desc': '未分配利润', 'type': 'float64'},
                'dif_ccy_tran': {'desc': '外币报表折算差额', 'type': 'float64'},
                'oe_oth_itm': {'desc': '其它股东权益类科目', 'type': 'float64'},
                'spc_oe_prn': {'desc': '归属母公司股东权益差额（归并报表科目）', 'type': 'float64'},
                'adj_oe_prn': {'desc': '归属母公司股东权益差额（合计平衡科目）', 'type': 'float64'},
                'oe_prn': {'desc': '归属于母公司股东权益合计', 'type': 'float64'},
                'oe_mnr': {'desc': '少数股东权益', 'type': 'float64'},
                'spc_oe': {'desc': '股东权益差额（归并报表科目）', 'type': 'float64'},
                'adj_oe': {'desc': '股东权益差额（合计平衡科目）', 'type': 'float64'},
                'oe_tot': {'desc': '所有者权益（或股东权益）合计', 'type': 'float64'},
                'spc_lbl_oe': {'desc': '负债及权益差额（归并报表科目）', 'type': 'float64'},
                'adj_lbl_oe': {'desc': '负债及权益差额（合计平衡科目）', 'type': 'float64'},
                'tot_lbl_oe': {'desc': '负债及股东权益总计', 'type': 'float64'},
                'adj_ast_lbl_oe': {'desc': '资产与负债权益（合计平衡科目）', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '信息发布日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '主体内部编码', 'type': 'str'},
            },
        },
    },
    # 主体-财务报表-主要财务指标   30字段
    'PTY_FIN_INDICATOR': {
        'source_table': 'AIWEGLOBAL.PTY_FIN_INDICATOR',
        'date': 'late_anc_dt',  # 末次公告日期 非主键，但是它作为时间列来被筛选更符合使用常理
        'date_format': '%Y-%m-%d',
        'instrument': 'pty_cd',
        'schema': {
            'desc': '主要财务指标',
            'active': True,
            'date_field': 'date',
            'category': '全局(原表)/主体',
            'rank': 1000016,
            'friendly_name': '主要财务指标',
            'partition_date': 'Y',
            'primary_key': ['end_dt', 'pty_cd', 'rpt_typ', 'instrument'],
            'fields': {
                'pty_cd': {'desc': '主体内部编码', 'type': 'str'},
                'frs_anc_dt': {'desc': '首次公告日期', 'type': 'datetime64[ns]'},
                'late_anc_dt': {'desc': '末次公告日期', 'type': 'datetime64[ns]'},
                'start_dt': {'desc': '报表起始日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
                'rpt_trm_typ': {'desc': '报告期类型', 'type': 'str'},
                'rpt_typ': {'desc': '报表类型', 'type': 'str'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'if_lis_dat': {'desc': '是否上市后数据', 'type': 'str'},
                'eps_dlut': {'desc': '每股收益-摊薄(元)', 'type': 'float64'},
                'eps_ddc_dlut': {'desc': '每股收益-扣除摊薄(元)', 'type': 'float64'},
                'eps_ddc_wt': {'desc': '每股收益-扣除加权(元)', 'type': 'float64'},
                'eps_ddc_bas': {'desc': '扣除非经常性损益后的基本每股收益', 'type': 'float64'},
                'roe_dlut': {'desc': '净资产收益率-摊薄(%)', 'type': 'float64'},
                'roe_wt': {'desc': '净资产收益率-加权(%)', 'type': 'float64'},
                'roe_ddc_dlut': {'desc': '净资产收益率-扣除摊薄(%)', 'type': 'float64'},
                'roe_ddc_wt': {'desc': '净资产收益率_扣除加权(%)', 'type': 'float64'},
                'naps_blg_cmp': {'desc': '归属于母公司股东的每股净资产(元)', 'type': 'float64'},
                'pro_int_std': {'desc': '国际会计准则净利润(元)', 'type': 'float64'},
                'non_rec_pro': {'desc': '非经常性损益(元)', 'type': 'float64'},
                'cur_rat': {'desc': '流动比(%)', 'type': 'float64'},
                'qck_rat': {'desc': '速动比(%)', 'type': 'float64'},
                'acc_lia_pro': {'desc': '资产负债率(%)', 'type': 'float64'},
                'soc_con_sha': {'desc': '每股社会贡献值(元)', 'type': 'float64'},
                'rep_per': {'desc': '会计年度', 'type': 'str'},
                'is_isr': {'desc': '是否实际准则', 'type': 'str'},
                'is_chg': {'desc': '是否更正', 'type': 'str'},
                'is_adt': {'desc': '是否审计', 'type': 'str'},
                'rpt_cpl': {'desc': '报表完整性', 'type': 'str'},
                'data_src': {'desc': '数据来源', 'type': 'str'},
                'is_act_pub': {'desc': '是否实际公布', 'type': 'str'},
                'remark': {'desc': '备注', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '末次公告日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '主体内部编码', 'type': 'str'},
            },
        },
    },
    # 主体-财务报表-主要财务指标衍生表   300字段
    'PTY_FIN_DRVIND': {
        'source_table': 'AIWEGLOBAL.PTY_FIN_DRVIND',
        'date': 'frs_anc_dt',   # 末次公告日期 非主键，但是它作为时间列来被筛选更符合使用常理
        'date_format': '%Y-%m-%d',
        'instrument': 'pty_cd',
        'schema': {
            'desc': '主要财务指标衍生表',
            'active': True,
            'date_field': 'date',
            'category': '全局(原表)/主体',
            'rank': 1000017,
            'friendly_name': '主要财务指标衍生表',
            'partition_date': 'Y',
            'primary_key': ['end_dt', 'pty_cd', 'rpt_typ', 'instrument'],
            'fields': {
                'pty_cd': {'desc': '主体内部编码', 'type': 'str'},
                'frs_anc_dt': {'desc': '首次公告日期', 'type': 'datetime64[ns]'},
                'late_anc_dt': {'desc': '末次公告日期', 'type': 'datetime64[ns]'},
                'end_dt': {'desc': '报告期截止日', 'type': 'datetime64[ns]'},
                'rpt_trm_typ': {'desc': '报告期类型', 'type': 'str'},
                'rpt_typ': {'desc': '报表类型', 'type': 'str'},
                'ccy_cd': {'desc': '币种', 'type': 'str'},
                'cas_liq_wit': {'desc': '货币资金占带息流动负债比', 'type': 'float64'},
                'cas_lia_cur': {'desc': '货币资金占流动负债比', 'type': 'float64'},
                'inv_inc': {'desc': '价值变动净收益', 'type': 'float64'},
                'inv_ebt': {'desc': '价值变动净收益占利润总额比率', 'type': 'float64'},
                'inv_cas_frt': {'desc': '投资活动产生的现金流量净额占比', 'type': 'float64'},
                'sal_or': {'desc': '销售商品提供劳务收到的现金占营业收入比率', 'type': 'float64'},
                'cfc_ass': {'desc': '经营和投资活动产生的净现金占负债总额比率', 'type': 'float64'},
                'cfc_lia_cur': {'desc': '经营和投资活动产生的净现金占流动负债比率', 'type': 'float64'},
                'ocf_me': {'desc': '经营活动产生的净现金占经营活动净收益比率', 'type': 'float64'},
                'ocf_or': {'desc': '经营活动产生的净现金占营业收入比率', 'type': 'float64'},
                'ocf_int': {'desc': '经营活动产生的现金流量净额同带息债务比', 'type': 'float64'},
                'ocf_net': {'desc': '经营活动产生的现金流量净额同净债务比', 'type': 'float64'},
                'ocf_deb': {'desc': '经营活动产生的现金流量净额同总负债比', 'type': 'float64'},
                'ocf_lia_cur': {'desc': '经营活动产生的现金流量净额占流动负债比率', 'type': 'float64'},
                'ocf_pro': {'desc': '经营活动产生的现金流量净额占营业利润比率', 'type': 'float64'},
                'ope_inc': {'desc': '经营活动净收益', 'type': 'float64'},
                'ope_ebt': {'desc': '经营活动净收益比利润总额比率', 'type': 'float64'},
                'opn_inv_sht': {'desc': '经营活动净现金和短期投资之和占短期债务比率', 'type': 'float64'},
                'opn_int': {'desc': '经营活动净现金同利息支出比', 'type': 'float64'},
                'opn_dep': {'desc': '经营活动净现金同折旧与摊销比', 'type': 'float64'},
                'opn_sht': {'desc': '经营活动净现金占短期债务比率', 'type': 'float64'},
                'opn_np': {'desc': '经营活动净现金占归属母公司的净利润比率', 'type': 'float64'},
                'opn_npc': {'desc': '经营活动净现金占含少数股东损益的净利润比率', 'type': 'float64'},
                'opn_si': {'desc': '经营活动净现金占销售收入比率', 'type': 'float64'},
                'opn_ltm': {'desc': '经营活动净现金占长期负债比率', 'type': 'float64'},
                'opn_tnc': {'desc': '经营活动净现金占总净现金流量比率', 'type': 'float64'},
                'opn_tde': {'desc': '经营活动净现金占总债务比率', 'type': 'float64'},
                'opn_ta': {'desc': '经营活动净现金占总资产比率', 'type': 'float64'},
                'opi_tic': {'desc': '经营活动现金流入占现金流入总量比率', 'type': 'float64'},
                'opn_cap': {'desc': '经营性现金流量对资本性支出比率', 'type': 'float64'},
                'acc_dep': {'desc': '累计折旧率', 'type': 'float64'},
                'fcff': {'desc': '企业自由现金流量(FCFF)', 'type': 'float64'},
                'fcfe_ps': {'desc': '每股股东自由现金流量', 'type': 'float64'},
                'ocfps': {'desc': '每股经营活动产生的现金流量净额', 'type': 'float64'},
                'bps': {'desc': '每股净资产', 'type': 'float64'},
                'ret_ps': {'desc': '每股留存收益', 'type': 'float64'},
                'dps': {'desc': '每股普通股股利', 'type': 'float64'},
                'fcff_ps': {'desc': '每股企业自由现金流量', 'type': 'float64'},
                'und_ps': {'desc': '每股未分配利润', 'type': 'float64'},
                'ebit_ps': {'desc': '每股息税前利润', 'type': 'float64'},
                'ebitda_ps': {'desc': '每股息税折旧摊销前利润_期末股数', 'type': 'float64'},
                'cfps': {'desc': '每股现金流量净额', 'type': 'float64'},
                'sur_res': {'desc': '每股盈余公积', 'type': 'float64'},
                'orps': {'desc': '每股营业收入', 'type': 'float64'},
                'gr_ps': {'desc': '每股营业总收入', 'type': 'float64'},
                'sur_cap': {'desc': '每股资本公积', 'type': 'float64'},
                'nap_ps': {'desc': '摊薄每股净资产_期末股数', 'type': 'float64'},
                'eps_dil_op': {'desc': '摊薄每股收益（营业利润）', 'type': 'float64'},
                'nap_adj': {'desc': '调整后每股净资产_期末股数', 'type': 'float64'},
                'pro_int': {'desc': '息前税后利润', 'type': 'float64'},
                'ebit_mar': {'desc': '息税前利润率', 'type': 'float64'},
                'ebit_gr': {'desc': '息税前利润同营业总收入比', 'type': 'float64'},
                'ebit_ass': {'desc': '息税前利润占总资产比率', 'type': 'float64'},
                'ebitda_mar': {'desc': '息税折旧摊销前利润率', 'type': 'float64'},
                'ebitda_deb': {'desc': '息税折旧摊销前利润同总负债比', 'type': 'float64'},
                'pre_opp': {'desc': '扣除财务费用前营业利润', 'type': 'float64'},
                'ded_pro': {'desc': '扣除非经常性损益后的净利润(扣除少数股东损益)', 'type': 'float64'},
                'op_gr': {'desc': '利润率', 'type': 'float64'},
                'tp_ebit': {'desc': '利润总额同息税前利润比', 'type': 'float64'},
                'pro_op': {'desc': '利润总额同营业收入比', 'type': 'float64'},
                'int_cut_cap': {'desc': '利息支出_扣除资本化利息', 'type': 'float64'},
                'ret_dea': {'desc': '留存收益', 'type': 'float64'},
                'ret_ta': {'desc': '留存收益占总资产比率', 'type': 'float64'},
                'gro_mar': {'desc': '毛利', 'type': 'float64'},
                'op_deb': {'desc': '营业利润同总负债比', 'type': 'float64'},
                'op_ebt': {'desc': '营业利润占利润总额比率', 'type': 'float64'},
                'op_lia_cur': {'desc': '营业利润占流动负债比', 'type': 'float64'},
                'opr_ta': {'desc': '营业收入占总资产比率', 'type': 'float64'},
                'nop_op': {'desc': '营业外收入占营业收入比率', 'type': 'float64'},
                'non_per_inc': {'desc': '营业外收支净额', 'type': 'float64'},
                'non_ebt': {'desc': '营业外收支净额占利润总额比率', 'type': 'float64'},
                'mai_pro': {'desc': '主营业务利润', 'type': 'float64'},
                'non_opp': {'desc': '非营业利润', 'type': 'float64'},
                'nop_ebt': {'desc': '非营业利润占利润总额比率', 'type': 'float64'},
                'pro_rat': {'desc': '净利润率(%)', 'type': 'float64'},
                'tur_day': {'desc': '营业周期', 'type': 'float64'},
                'gc_gr': {'desc': '营业总成本率', 'type': 'float64'},
                'pro_tog': {'desc': '营业总收入利润率', 'type': 'float64'},
                'div_pay_deb': {'desc': '分配利润或偿付利息支付的现金同总债务比', 'type': 'float64'},
                'ded_fit': {'desc': '经常性净利润占比', 'type': 'float64'},
                'net_per': {'desc': '母公司的净利润占营业总收入比率', 'type': 'float64'},
                'avg_ris_wgt': {'desc': '平均风险加权资产回报率', 'type': 'float64'},
                'ppop': {'desc': '拨备前利润', 'type': 'float64'},
                'exc_div_ris': {'desc': '拨备前利润同平均风险加权资产比', 'type': 'float64'},
                'exc_div_avg': {'desc': '拨备前利润占平均总资产比率', 'type': 'float64'},
                'np_tp': {'desc': '归属母公司的净利润占利润总额比率', 'type': 'float64'},
                'np_noc': {'desc': '归属母公司股东的净利润占含少数股东损益的净利润比率', 'type': 'float64'},
                'npc_tp': {'desc': '含少数股东损益的净利润占利润总额比率', 'type': 'float64'},
                'ebit_int': {'desc': '已获利息倍数(EBIT/利息费用)', 'type': 'float64'},
                'ebit_for': {'desc': 'EBIT_正推法', 'type': 'float64'},
                'ebitda_sco': {'desc': 'EBITDA利息保障倍数', 'type': 'float64'},
                'ebitda_ad': {'desc': 'EBITDA占总债务比率', 'type': 'float64'},
                'roeyoyb': {'desc': '权益净利率-同比增减（%）', 'type': 'float64'},
                'ebit_rat': {'desc': '税前利润率(%)', 'type': 'float64'},
                'tot_cpt': {'desc': '总资本', 'type': 'float64'},
                'rota': {'desc': '总资本回报率', 'type': 'float64'},
                'roa2': {'desc': '总资产报酬率', 'type': 'float64'},
                'roa': {'desc': '总资产净利率', 'type': 'float64'},
                'dup_roa': {'desc': '总资产净利率(杜邦分析)', 'type': 'float64'},
                'ass_rn': {'desc': '总资产周转率', 'type': 'float64'},
                'tat_day': {'desc': '总资产周转天数', 'type': 'float64'},
                'lia_tot_far': {'desc': '有形净值债务率', 'type': 'float64'},
                'tan_ass_net': {'desc': '有形资产(有形净资产)', 'type': 'float64'},
                'tan_deb': {'desc': '有形资产负债率', 'type': 'float64'},
                'nta_tot': {'desc': '有形资产净值同总债务比', 'type': 'float64'},
                'tan_int': {'desc': '有形资产同带息债务比', 'type': 'float64'},
                'tan_net': {'desc': '有形资产同净债务比', 'type': 'float64'},
                'tan_ass': {'desc': '有形资产占总资产比率', 'type': 'float64'},
                'dol_rat': {'desc': '长期资本负债率', 'type': 'float64'},
                'ltm_ass': {'desc': '长期资产适合率', 'type': 'float64'},
                'cap_tco': {'desc': '资本固定化比率(含少数股权的净资产）', 'type': 'float64'},
                'ltm_tac': {'desc': '资本化比率_含少数股权的净资产', 'type': 'float64'},
                'cap_pro': {'desc': '资本金利润率', 'type': 'float64'},
                'cap_da': {'desc': '资本支出同折旧和摊销比', 'type': 'float64'},
                'acc_lia_pro': {'desc': '资产负债率(%)', 'type': 'float64'},
                'imp_ttm': {'desc': '资产减值损失费用率', 'type': 'float64'},
                'ass_pro': {'desc': '资产减值损失占营业利润比率', 'type': 'float64'},
                'cur_rat': {'desc': '流动比(%)', 'type': 'float64'},
                'lia_cur_eqt': {'desc': '流动负债权益比率', 'type': 'float64'},
                'cur_lbl_cur': {'desc': '流动负债占总负债比率', 'type': 'float64'},
                'nit_cur': {'desc': '流动资产利润率', 'type': 'float64'},
                'opr_toc': {'desc': '流动资产营业利润率', 'type': 'float64'},
                'cat_ass': {'desc': '流动资产占总资产比率', 'type': 'float64'},
                'cat_rn': {'desc': '流动资产周转率', 'type': 'float64'},
                'cur_day': {'desc': '流动资产周转天数', 'type': 'float64'},
                'nca_ass': {'desc': '非流动资产占总资产比率', 'type': 'float64'},
                'nca_tur': {'desc': '非流动资产周转率', 'type': 'float64'},
                'fap_tio': {'desc': '固定资产比重', 'type': 'float64'},
                'tot_fat': {'desc': '固定资产合计周转率', 'type': 'float64'},
                'nfart': {'desc': '固定资产净值率', 'type': 'float64'},
                'fap_t': {'desc': '固定资产利润率', 'type': 'float64'},
                'fat_rn': {'desc': '固定资产周转率', 'type': 'float64'},
                'fat_day': {'desc': '固定资产周转天数', 'type': 'float64'},
                'equ_fa': {'desc': '归属母公司的净资产同固定资产比', 'type': 'float64'},
                'equ_tde': {'desc': '归属母公司的净资产同总债务比', 'type': 'float64'},
                'equ_int': {'desc': '归属于母公司的股东权益同带息债务比率', 'type': 'float64'},
                'equ_tal': {'desc': '归属于母公司的股东权益占全部投入资本比率', 'type': 'float64'},
                'equ_deb': {'desc': '归属于母公司的股东权益占总负债比率', 'type': 'float64'},
                'equ_ic': {'desc': '归属母公司净的资产同归属母公司的投入资本比', 'type': 'float64'},
                'equ_cut': {'desc': '剔除其他权益后的归属母公司净资产', 'type': 'float64'},
                'roi_yea': {'desc': '年化投入资本回报率', 'type': 'float64'},
                'roa2_yea': {'desc': '年化总资产报酬率', 'type': 'float64'},
                'roa_yea': {'desc': '年化总资产净利率', 'type': 'float64'},
                'roe_yea': {'desc': '年化净资产收益率', 'type': 'float64'},
                'roe_avg': {'desc': '平均净资产收益率(增发条件)', 'type': 'float64'},
                'ta_avg': {'desc': '平均资产总额', 'type': 'float64'},
                'equ_con': {'desc': '含少数股权的净资产', 'type': 'float64'},
                'roe_by_cut': {'desc': '净资产收益率_扣除前后净利润_归属母公司', 'type': 'float64'},
                'roe_dlut': {'desc': '摊薄净资产收益率', 'type': 'float64'},
                'roe_dlut_cut': {'desc': '摊薄净资产收益率_扣除非经常损益', 'type': 'float64'},
                'roe_avg_pref': {'desc': '净资产收益率_平均_披露优先', 'type': 'float64'},
                'roic': {'desc': '投入资本回报率', 'type': 'float64'},
                'cor_t1_car': {'desc': '核心一级资本充足率', 'type': 'float64'},
                'ccar_2013': {'desc': '核心资本充足率_2013', 'type': 'float64'},
                'car_2013': {'desc': '资本充足率_2013', 'type': 'float64'},
                'nco_t1_cap': {'desc': '核心一级资本净额', 'type': 'float64'},
                'nt1_cap': {'desc': '一级资本净额', 'type': 'float64'},
                'nt1_cap_2013': {'desc': '一级资本净额_2013', 'type': 'float64'},
                'nca_2013': {'desc': '资本净额_2013', 'type': 'float64'},
                'inv_cap': {'desc': '全部投入资本', 'type': 'float64'},
                'tot_alt': {'desc': '全部资本化比率', 'type': 'float64'},
                'ris_wgt_ass': {'desc': '风险加权资产', 'type': 'float64'},
                'ris_ass_2013': {'desc': '风险加权资产_2013', 'type': 'float64'},
                'net_wor_cap': {'desc': '营运流动资本', 'type': 'float64'},
                'opc_tot': {'desc': '营运资本对总资产比率', 'type': 'float64'},
                'wor_cap': {'desc': '营运资金', 'type': 'float64'},
                'net_ope_cap': {'desc': '净营运资本', 'type': 'float64'},
                'op_cap': {'desc': '净营运资本周转率', 'type': 'float64'},
                'tde_bt': {'desc': '总债务', 'type': 'float64'},
                'td_ebitda': {'desc': '总债务同EBITDA比', 'type': 'float64'},
                'tde_bt_ic': {'desc': '总债务同归属母公司的投入资本比', 'type': 'float64'},
                'tde_icc': {'desc': '总债务同含少数股权的投入资本比', 'type': 'float64'},
                'bvos': {'desc': '总债务占股权价值比率', 'type': 'float64'},
                'ltm_lia': {'desc': '长期负债比', 'type': 'float64'},
                'ltm_equ': {'desc': '长期负债同归属母公司的净资产比', 'type': 'float64'},
                'ltm_opc': {'desc': '长期负债与营运资本比率', 'type': 'float64'},
                'ltm_ta': {'desc': '长期负债占总资产比率', 'type': 'float64'},
                'ltm_deb': {'desc': '长期债务', 'type': 'float64'},
                'lon_wor': {'desc': '长期债务与营运资金比率', 'type': 'float64'},
                'sht_deb': {'desc': '短期债务', 'type': 'float64'},
                'sht_lia_tot': {'desc': '短期负债占负债总额比率', 'type': 'float64'},
                'net_deb': {'desc': '净债务', 'type': 'float64'},
                'nbvos': {'desc': '净债务占股权价值比率', 'type': 'float64'},
                'nde_equ': {'desc': '净债务占归属母公司的净资产比率', 'type': 'float64'},
                'int_deb': {'desc': '带息债务', 'type': 'float64'},
                'int_tal': {'desc': '带息债务占全部投入资本比率', 'type': 'float64'},
                'exi_non': {'desc': '无息非流动负债', 'type': 'float64'},
                'exi_cur': {'desc': '无息流动负债', 'type': 'float64'},
                'non_cl_equ': {'desc': '非流动负债权益比率', 'type': 'float64'},
                'lon_lia_tot': {'desc': '非流动负债占总负债比率', 'type': 'float64'},
                'lia_cur_ltm': {'desc': '负债结构比率', 'type': 'float64'},
                'acc_pay': {'desc': '应付账款周转率', 'type': 'float64'},
                'acc_day': {'desc': '应付账款周转天数', 'type': 'float64'},
                'art_rn': {'desc': '应收账款周转率', 'type': 'float64'},
                'art_day': {'desc': '应收账款周转天数', 'type': 'float64'},
                'stm_is': {'desc': '折旧与摊销', 'type': 'float64'},
                'com_dep': {'desc': '综合折旧率', 'type': 'float64'},
                'lia_tot_equ': {'desc': '产权比率', 'type': 'float64'},
                'fin_lex': {'desc': '财务费用率', 'type': 'float64'},
                'fin_tog': {'desc': '财务费用占营业总收入比率', 'type': 'float64'},
                'pro_tcr': {'desc': '成本费用利润率', 'type': 'float64'},
                'tc_exp': {'desc': '成本费用率', 'type': 'float64'},
                'opp_tot': {'desc': '成本费用营业利润率', 'type': 'float64'},
                'tc': {'desc': '成本费用总额', 'type': 'float64'},
                'mgt_exp': {'desc': '管理费用率', 'type': 'float64'},
                'adm_tog': {'desc': '管理费用占营业总收入比率', 'type': 'float64'},
                'tri_exp': {'desc': '三项费用', 'type': 'float64'},
                'tri_exp_rt': {'desc': '三项费用比重', 'type': 'float64'},
                'tri_pi': {'desc': '三项费用占营业总收入比率', 'type': 'float64'},
                'op_exp': {'desc': '营业费用率', 'type': 'float64'},
                'sal_tog': {'desc': '销售费用占营业总收入比率', 'type': 'float64'},
                'exp_sal': {'desc': '销售期间费用率', 'type': 'float64'},
                'z_val': {'desc': 'Z值', 'type': 'float64'},
                'desz': {'desc': 'Z值结果描述 ', 'type': 'str'},
                'yoy_z': {'desc': 'Z值-同比增减', 'type': 'float64'},
                'exc_res_rto': {'desc': '超额准备金比率', 'type': 'float64'},
                'bff_cas_frt': {'desc': '筹资活动产生的现金流量净额占比', 'type': 'float64'},
                'loa_dep': {'desc': '存贷比_折人民币_披露优先', 'type': 'float64'},
                'inv_rn': {'desc': '存货周转率', 'type': 'float64'},
                'inv_day': {'desc': '存货周转天数', 'type': 'float64'},
                'inv_cur': {'desc': '存货资产构成率', 'type': 'float64'},
                'loa_los_tot': {'desc': '贷款损失准备金同贷款总额比', 'type': 'float64'},
                'tmp_tli': {'desc': '当日总市值同总负债比率', 'type': 'float64'},
                'non_rec_pro': {'desc': '非经常性损益', 'type': 'float64'},
                'rig_tli': {'desc': '股东权益合计(含少数)占总负债比率', 'type': 'float64'},
                'equ_tur': {'desc': '股东权益周转率', 'type': 'float64'},
                'equ_tur_con': {'desc': '股东权益周转率(含少数股权权益）', 'type': 'float64'},
                'fcfe': {'desc': '股权自由现金流量(FCFE)', 'type': 'float64'},
                'liq_dva': {'desc': '清算价值比率1', 'type': 'float64'},
                'ass_equ': {'desc': '权益乘数', 'type': 'float64'},
                'dup_ass_equ': {'desc': '权益乘数(用于杜邦分析)', 'type': 'float64'},
                'cas_rat': {'desc': '保守速动比率', 'type': 'float64'},
                'qui_rat': {'desc': '速动比(%)', 'type': 'float64'},
                'tax_ebt': {'desc': '所得税率', 'type': 'float64'},
                'int_cas': {'desc': '投资收益收现率', 'type': 'float64'},
                'cas_rt': {'desc': '现金比率', 'type': 'float64'},
                'cas_hop': {'desc': '现金运营指数', 'type': 'float64'},
                'cas_con': {'desc': '现金周期', 'type': 'float64'},
                'cog_sal': {'desc': '销售成本率', 'type': 'float64'},
                'net_pro_mar': {'desc': '销售净利率', 'type': 'float64'},
                'gro_pro_mar': {'desc': '销售毛利率', 'type': 'float64'},
                'avg_ear': {'desc': '已赚保费增长率', 'type': 'float64'},
                'toc_or': {'desc': '营业成本占营业收入比率', 'type': 'float64'},
                'ope_inc_qfa': {'desc': '单季度.经营活动净收益', 'type': 'float64'},
                'inv_inc_qfa': {'desc': '单季度.价值变动净收益', 'type': 'float64'},
                'ded_pro_exp_qfa': {'desc': '单季度.扣除非经常损益后的净利润', 'type': 'float64'},
                'eps_qfa': {'desc': '单季度.每股收益', 'type': 'float64'},
                'net_pro_qfa': {'desc': '单季度.销售净利率', 'type': 'float64'},
                'gro_pro_qfa': {'desc': '单季度.销售毛利率', 'type': 'float64'},
                'exp_sal_qfa': {'desc': '单季度.销售期间费用率', 'type': 'float64'},
                'pro_tog_qfa': {'desc': '单季度.营业总收入利润率', 'type': 'float64'},
                'sal_gr_qfa': {'desc': '单季度.销售费用率', 'type': 'float64'},
                'adm_gr_qfa': {'desc': '单季度.管理费用率', 'type': 'float64'},
                'fin_gr_qfa': {'desc': '单季度.财务费用率', 'type': 'float64'},
                'imp_ttm_qfa': {'desc': '单季度.资产减值损失费用率', 'type': 'float64'},
                'gc_gr_qfa': {'desc': '单季度.营业总成本率', 'type': 'float64'},
                'op_gr_qfa': {'desc': '单季度.利润率', 'type': 'float64'},
                'roe_qfa': {'desc': '单季度.净资产收益率', 'type': 'float64'},
                'roe_ded_qfa': {'desc': '单季度.净资产收益率(扣除非经常损益)', 'type': 'float64'},
                'roa_qfa': {'desc': '单季度.总资产净利润率', 'type': 'float64'},
                'ope_ebt_qfa': {'desc': '单季度.经营活动净收益占利润总额比率', 'type': 'float64'},
                'inv_ebt_qfa': {'desc': '单季度.价值变动净收益占利润总额比率', 'type': 'float64'},
                'ded_pro_pro_qfa': {'desc': '单季度.经常性净利润占利润总额比率', 'type': 'float64'},
                'sal_or_qfa': {'desc': '单季度.销售商品提供劳务收到的现金占营业收入比率', 'type': 'float64'},
                'ocf_sal_qfa': {'desc': '单季度.经营活动产生的净现金占营业收入比率', 'type': 'float64'},
                'ocf_or_qfa': {'desc': '单季度.经营活动产生的净现金占经营活动净收益比率', 'type': 'float64'},
                'yoy_gr_qfa': {'desc': '单季度.营业总收入同比增长率(%)', 'type': 'float64'},
                'cgr_gr_qfa': {'desc': '单季度.营业总收入环比增长率(%)', 'type': 'float64'},
                'yoy_sal_qfa': {'desc': '单季度.营业收入同比增长率(%)', 'type': 'float64'},
                'cgr_sal_qfa': {'desc': '单季度.营业收入环比增长率(%)', 'type': 'float64'},
                'yoy_op_qfa': {'desc': '单季度.营业利润同比增长率(%)', 'type': 'float64'},
                'cgr_op_qfa': {'desc': '单季度.营业利润环比增长率(%)', 'type': 'float64'},
                'yoy_pro_qfa': {'desc': '单季度.净利润同比增长率(%)', 'type': 'float64'},
                'cgr_pro_qfa': {'desc': '单季度.净利润环比增长率(%)', 'type': 'float64'},
                'yoy_net_pro_qfa': {'desc': '单季度.归属母公司股东的净利润同比增长率(%)', 'type': 'float64'},
                'cgr_net_pro_qfa': {'desc': '单季度.归属母公司股东的净利润环比增长率(%)', 'type': 'float64'},
                'yoy_eps_bas': {'desc': '同比增长率-基本每股收益(%)', 'type': 'float64'},
                'yoy_eps_dil': {'desc': '同比增长率-稀释每股收益(%)', 'type': 'float64'},
                'yoy_ocf': {'desc': '同比增长率-每股经营活动产生的现金流量净额(%)', 'type': 'float64'},
                'yoy_op': {'desc': '同比增长率-营业利润(%)', 'type': 'float64'},
                'yoy_ebt_tot': {'desc': '同比增长率-利润总额(%)', 'type': 'float64'},
                'yoy_ebt': {'desc': '同比增长率-净利润(%)', 'type': 'float64'},
                'yoy_tr': {'desc': '同比增长率-营业总收入(%)', 'type': 'float64'},
                'yoy_or': {'desc': '同比增长率-营业收入(%)', 'type': 'float64'},
                'yoy_equ': {'desc': '同比增长率-净资产(%)', 'type': 'float64'},
                'yoy_net_pro': {'desc': '同比增长率-归属母公司股东的净利润(%)', 'type': 'float64'},
                'yoy_net_pro_ded': {'desc': '同比增长率-归属母公司股东的净利润-扣除非经常损益(%)', 'type': 'float64'},
                'yoy_cf': {'desc': '同比增长率-经营活动产生的现金流量净额(%)', 'type': 'float64'},
                'yoy_oe': {'desc': '同比增长率-净资产收益率(摊薄)(%)', 'type': 'float64'},
                'yoy_bps': {'desc': '相对年初增长率-每股净资产(%)', 'type': 'float64'},
                'yoy_ass': {'desc': '相对年初增长率-资产总计(%)', 'type': 'float64'},
                'yoy_equ_sha': {'desc': '相对年初增长率-归属母公司的股东权益(%)', 'type': 'float64'},
                'yoy_lia': {'desc': '相对年初增长率-总负债', 'type': 'float64'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '末次公告日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '主体内部编码', 'type': 'str'},
            },
        },
    },
    # 主体-信用评级-主体信用评级
    'PTY_RATING': {
        'source_table': 'AIWEGLOBAL.PTY_RATING',
        'date': 'rat_dt',
        'date_format': '%Y-%m-%d',
        'instrument': 'pty_cd',
        'schema': {
            'desc': '主体信用评级',
            'active': True,
            'date_field': 'date',
            'category': '全局(原表)/主体',
            'rank': 1000018,
            'friendly_name': '主体信用评级',
            'partition_date': 'Y',
            'primary_key': ['pty_cd', 'rat_dt', 'rat_org','rat_typ', 'instrument'],
            'fields': {
                'anc_dt': {'desc': '公告日期', 'type': 'datetime64[ns]'},
                'pty_cd': {'desc': '主体内部编码', 'type': 'str'},
                'chn_nm': {'desc': '主体中文全称', 'type': 'str'},
                'rat_dt': {'desc': '评级日期', 'type': 'datetime64[ns]'},
                'rat_org': {'desc': '评级机构', 'type': 'str'},
                'rat_typ': {'desc': '信用评级类型', 'type': 'str'},
                'pty_rol': {'desc': '主体角色', 'type': 'str'},
                'crd_rat': {'desc': '信用评级', 'type': 'str'},
                'rat_xpc': {'desc': '评级展望', 'type': 'str'},
                'rat_pre': {'desc': '前次信用评级', 'type': 'str'},
                'rat_chg_dir': {'desc': '评级变动方向', 'type': 'str'},
                'is_actv_rat': {'desc': '是否主动评级', 'type': 'str'},
                'remark': {'desc': '备注', 'type': 'str'},

                'sys_crt_tm': {'desc': '数据产生时间', 'type': 'datetime64[ns]'},
                'sys_upd_tm': {'desc': '最后修改时间', 'type': 'datetime64[ns]'},
                'sys_isvld': {'desc': '是否有效', 'type': 'str'},

                'date': {'desc': '末次公告日期', 'type': 'datetime64[ns]'},
                'instrument': {'desc': '主体内部编码', 'type': 'str'},
            },
        },
    },
}


# 盈利因子
"""
s_fa_roe 净资产收益率 无
s_fa_roa2 总资产报酬率(总资产报酬率?) PTY_FIN_DRVIND.roa2
s_fa_roa 总资产净利润(总资产净利率?) PTY_FIN_DRVIND.roa
s_fa_optogr 营业利润率(利润率?) PTY_FIN_DRVIND.op_gr
s_fa_profittogr 净利润率(营业总收入利润率?) PTY_FIN_DRVIND.pro_tog
s_fa_gctogr 营业总成本/营业总收入(营业总成本率?) PTY_FIN_DRVIND.gc_gr
s_fa_ebittogr 息税前利润率(息税前利润同营业总收入比?) PTY_FIN_DRVIND.ebit_gr
s_fa_grossprofitmargin 销售毛利率(销售毛利率,通过中文找到) PTY_FIN_DRVIND.gro_pro_mar
s_fa_netprofitmargin 销售净利率(销售净利率,通过中文找到) PTY_FIN_DRVIND.net_pro_mar
s_fa_cogstosales 销售成本率(销售成本率,通过中文找到) PTY_FIN_DRVIND.cog_sal
"""


# 成长因子
"""
s_fa_yoyeps_basic 同比增长率-基本每股收益(%)(同比增长率-基本每股收益(%),通过中文找到) PTY_FIN_DRVIND.yoy_eps_bas
s_fa_yoyeps_diluted 同比增长率-稀释每股收益(%)(同比增长率-稀释每股收益(%),通过中文找到) PTY_FIN_DRVIND.yoy_eps_dil
s_fa_yoyocfps 同比增长率-每股经营活动产生的现金流量净额(%)(同比增长率-每股经营活动产生的现金流量净额(%),通过中文找到) PTY_FIN_DRVIND.yoy_ocf
s_fa_yoyop 同比增长率-营业利润(%)(同比增长率-营业利润(%),通过中文找到) PTY_FIN_DRVIND.yoy_op
s_fa_yoyebt 同比增长率-利润总额(%)(同比增长率-利润总额(%),通过中文找到) PTY_FIN_DRVIND.yoy_ebt_tot
s_fa_yoynetprofit 同比增长率-归属母公司股东的净利润(%)(同比增长率-归属母公司股东的净利润(%),通过中文找到) PTY_FIN_DRVIND.yoy_net_pro
s_fa_yoy_tr 营业总收入同比增长率(%)(同比增长率-营业总收入(%)?, 通过中文找到) PTY_FIN_DRVIND.yoy_tr
s_fa_yoy_or 营业收入同比增长率 (%)(同比增长率-营业收入(%)?, 通过中文找到) PTY_FIN_DRVIND.yoy_or
s_fa_yoybps 相对年初增长率-每股净资产(%)(相对年初增长率-每股净资产(%)?, 通过中文找到) PTY_FIN_DRVIND.yoy_bps
s_fa_yoyassets 相对年初增长率-资产总计(%)(相对年初增长率-资产总计(%)?, 通过中文找到)  PTY_FIN_DRVIND.yoy_ass
s_fa_yoyequity 相对年初增长率-归属母公司的股东权益(%)(相对年初增长率-归属母公司的股东权益(%)?, 通过中文找到) PTY_FIN_DRVIND.yoy_equ_sha
"""

# 偿债因子
"""
s_fa_debttoassets 资产负债率(资产负债率(%),通过中文找到,PTY_FIN_INDICATOR也有，名字一样) PTY_FIN_DRVIND.acc_lia_pro
s_fa_assetstoequity 权益乘数(权益乘数,通过中文找到) PTY_FIN_DRVIND.ass_equ
s_fa_debttoequity 产权比率(产权比率,通过中文找到) PTY_FIN_DRVIND.lia_tot_equ
s_fa_ebittointerest 已获利息倍数(EBIT/利息费用)(已获利息倍数(EBIT/利息费用)?) PTY_FIN_DRVIND.ebit_int
s_fa_current 流动比率(流动比(%)??,通过中文找到,PTY_FIN_INDICATOR也有,名字一样) PTY_FIN_DRVIND.cur_rat
s_fa_quick 速动比率(速动比(%)??,通过中文找到,PTY_FIN_INDICATOR也有,但叫qck_rat) PTY_FIN_DRVIND.qui_rat
s_fa_cashratio 保守速动比率(保守速动比率,通过中文找到) PTY_FIN_DRVIND.cas_rat
s_fa_catoassets 流动资产/总资产(流动资产占总资产比率?,通过中文找到)  PTY_FIN_DRVIND.cat_ass
s_fa_ocftoshortdebt 经营活动产生的现金流量净额/流动负债(经营活动产生的现金流量净额占流动负债比率??) PTY_FIN_DRVIND.ocf_lia_cur
s_fa_equitytodebt 归属于母公司的股东权益/负债合计(归属于母公司的股东权益占总负债比率?,通过中文找到) PTY_FIN_DRVIND.equ_deb
s_fa_ocftodebt 经营活动产生的现金流量净额/负债合计(经营活动产生的现金流量净额同总负债比?) PTY_FIN_DRVIND.ocf_deb
"""


# 营运因子
"""
s_fa_invturn 存货周转率(存货周转率,通过中文找到) PTY_FIN_DRVIND.inv_rn
s_fa_arturn 应收账款周转率(应收账款周转率,通过中文找到) PTY_FIN_DRVIND.art_rn
s_fa_arturndays 应收账款周转天数(应收账款周转天数,通过中文找到) PTY_FIN_DRVIND.art_day
s_fa_faturn 固定资产周转率(固定资产周转率,通过中文找到) PTY_FIN_DRVIND.fat_rn
s_fa_caturn 流动资产周转率(流动资产周转率,通过中文找到) PTY_FIN_DRVIND.cat_rn
s_fa_assetsturn 总资产周转率(总资产周转率) PTY_FIN_DRVIND.ass_rn
s_fa_fcff 企业自由现金流量(FCFF)(企业自由现金流量(FCFF)) PTY_FIN_DRVIND.fcff
s_fa_workingcapital 营运资金(营运资金,通过中文找到) PTY_FIN_DRVIND.wor_cap
s_fa_networkingcapital 营运流动资本(营运流动资本,通过中文找到) PTY_FIN_DRVIND.net_wor_cap
"""

# 每股因子
"""
s_fa_eps_basic 基本每股收益(基本每股收益) PTY_FIN_INCOME.eps_bas
s_fa_eps_diluted 稀释每股收益(稀释每股收益) PTY_FIN_INCOME.eps_dlt
s_fa_bps 每股净资产(每股净资产) PTY_FIN_DRVIND.bps
s_fa_ocfps 每股经营活动产生的现金流量净额(每股经营活动产生的现金流量净额) PTY_FIN_DRVIND.ocfps
s_fa_grps 每股营业总收入(每股营业总收入) PTY_FIN_DRVIND.gr_ps
s_fa_orps 每股营业收入(每股营业收入) PTY_FIN_DRVIND.orps
s_fa_surpluscapitalps 每股资本公积(每股资本公积) PTY_FIN_DRVIND.sur_cap
s_fa_surplusreserveps 每股盈余公积(每股盈余公积) PTY_FIN_DRVIND.sur_res
s_fa_undistributedps 每股未分配利润(每股未分配利润) PTY_FIN_DRVIND.und_ps
s_fa_retainedps 每股留存收益(每股留存收益) PTY_FIN_DRVIND.ret_ps
s_fa_cfps 每股现金流量净额(每股现金流量净额) PTY_FIN_DRVIND.cfps
s_fa_ebitps 每股息税前利润(每股息税前利润) PTY_FIN_DRVIND.ebit_ps
s_fa_fcffps 每股企业自由现金流量(每股企业自由现金流量) PTY_FIN_DRVIND.fcff_ps
s_fa_fcfeps 每股股东自由现金流量(每股股东自由现金流量) PTY_FIN_DRVIND.fcfe_ps
"""
