schema = {
    'desc': 'A股内置基础因子数据',
    'category': 'A股数据/预计算因子',
    'rank': 1004001,
    'primary_key': ['date', 'instrument'],
    'active': False,
    'partition_date': 'Y',
    'friendly_name': 'A股内置基础因子数据',
    'date_field': 'date',
    'agg_name': '基础因子',
    'agg_key': 'features_CN_STOCK_A',
    'split_field': True,
    'split_file': True,
    'file_type': 'bdb',
    'fields': {
        'instrument': {'desc': '证券代码', 'type': 'str'},
        'date': {'desc': '日期', 'type': 'datetime64[ns]'},

        'adjust_factor_0': {'desc': '第前0个交易日的复权因子', 'type': 'float32'},
        'amount_0': {'desc': '第前0个交易日的交易额', 'type': 'float64'},
        'avg_amount_0': {'desc': '过去0个交易日的平均交易额', 'type': 'float64'},
        'close_0': {'desc': '第前0个交易日的收盘价', 'type': 'float32'},
        'daily_return_0': {'desc': '第前0个交易日的收益', 'type': 'float32'},
        'deal_number_0': {'desc': '第前0个交易日的成交笔数', 'type': 'int32'},
        'high_0': {'desc': '第前0个交易日的最高价', 'type': 'float32'},
        'low_0': {'desc': '第前0个交易日的最低价', 'type': 'float32'},
        'open_0': {'desc': '第前0个交易日的开盘价', 'type': 'float32'},
        'price_limit_status_0': {'desc': '股价在收盘时的涨跌停状态：1表示跌停，2表示未涨跌停，3则表示涨停', 'type': 'float32'},
        'rank_amount_0': {'desc': '第前0个交易日的交易额百分比排名', 'type': 'float32'},
        'rank_avg_amount_0': {'desc': '过去0个交易日的平均交易额，百分比排名', 'type': 'float32'},
        'rank_return_0': {'desc': '过去0个交易日的收益排名', 'type': 'float32'},
        'return_0': {'desc': '过去0个交易日的收益', 'type': 'float32'},
        'volume_0': {'desc': '第前0个交易日的交易量', 'type': 'int64'},
        'avg_turn_0': {'desc': '过去0个交易日的平均换手率', 'type': 'float32'},
        'rank_avg_turn_0': {'desc': '过去0个交易日的平均换手率排名', 'type': 'float32'},
        'turn_0': {'desc': '第前0个交易日的换手率', 'type': 'float32'},
        'rank_turn_0': {'desc': '过去0个交易日的换手率排名', 'type': 'float32'},
        'company_found_date_0': {'desc': '公司成立天数', 'type': 'int32'},
        'in_csi100_0': {'desc': '是否属于中证100指数成份', 'type': 'int8'},
        'in_csi300_0': {'desc': '是否属于沪深300指数成份', 'type': 'int8'},
        'in_csi500_0': {'desc': '是否属于中证500指数成份', 'type': 'int8'},
        'in_csi800_0': {'desc': '是否属于中证800指数成份', 'type': 'int8'},
        'in_sse180_0': {'desc': '是否属于上证180指数成份', 'type': 'int8'},
        'in_sse50_0': {'desc': '是否属于上证50指数成份', 'type': 'int8'},
        'in_szse100_0': {'desc': '是否属于深证100指数成份', 'type': 'int8'},
        'industry_sw_level1_0': {'desc': '申万一级行业类别', 'type': 'int32'},
        'industry_sw_level2_0': {'desc': '申万二级行业类别', 'type': 'int32'},
        'industry_sw_level3_0': {'desc': '申万三级行业类别', 'type': 'int32'},
        'list_board_0': {'desc': '上市板，主板：1，中小企业板：2，创业板：3', 'type': 'float32'},
        'list_days_0': {'desc': '已经上市的天数，按自然日计算', 'type': 'float32'},
        'st_status_0': {'desc': 'ST状态：0：正常股票，1：ST，2：*ST，11：暂停上市', 'type': 'float32'},
        'market_cap_0': {'desc': '总市值', 'type': 'float64'},
        'market_cap_float_0': {'desc': '流通市值', 'type': 'float64'},
        'pb_lf_0': {'desc': '市净率 (LF)', 'type': 'float32'},
        'pe_lyr_0': {'desc': '市盈率 (LYR)', 'type': 'float32'},
        'pe_ttm_0': {'desc': '市盈率 (TTM)', 'type': 'float32'},
        'ps_ttm_0': {'desc': '市销率 (TTM)', 'type': 'float32'},
        'rank_market_cap_0': {'desc': '总市值，升序百分比排名', 'type': 'float32'},
        'rank_market_cap_float_0': {'desc': '流通市值，升序百分比排名', 'type': 'float32'},
        'rank_pb_lf_0': {'desc': '市净率 (LF)，升序百分比排名', 'type': 'float32'},
        'rank_pe_lyr_0': {'desc': '市盈率 (LYR)，升序百分比排名', 'type': 'float32'},
        'rank_pe_ttm_0': {'desc': '市盈率(TTM),升序百分比排名', 'type': 'float32'},
        'rank_ps_ttm_0': {'desc': '市销率 (TTM)，升序百分比排名', 'type': 'float32'},
        'ta_ad_0': {'desc': '收集派发指标', 'type': 'float64'},
        'ta_adx_14_0': {'desc': 'ADX指标，timeperiod=14', 'type': 'float32'},
        'ta_adx_28_0': {'desc': 'ADX指标，timeperiod=28', 'type': 'float32'},
        'ta_aroon_down_14_0': {'desc': '阿隆指标aroondown，timeperiod=14', 'type': 'float32'},
        'ta_aroon_down_28_0': {'desc': '阿隆指标aroondown，timeperiod=28', 'type': 'float32'},
        'ta_aroon_up_14_0': {'desc': '阿隆指标aroonup，timeperiod=14', 'type': 'float32'},
        'ta_aroon_up_28_0': {'desc': '阿隆指标aroonup，timeperiod=28', 'type': 'float32'},
        'ta_aroonosc_14_0': {'desc': 'AROONOSC指标，timeperiod=14', 'type': 'float32'},
        'ta_aroonosc_28_0': {'desc': 'AROONOSC指标，timeperiod=28', 'type': 'float32'},
        'ta_atr_14_0': {'desc': 'ATR指标，timeperiod=14', 'type': 'float32'},
        'ta_atr_28_0': {'desc': 'ATR指标，timeperiod=28', 'type': 'float32'},
        'ta_bbands_lowerband_14_0': {'desc': 'BBANDS指标，timeperiod=14', 'type': 'float32'},
        'ta_bbands_lowerband_28_0': {'desc': 'BBANDS指标，timeperiod=28', 'type': 'float32'},
        'ta_bbands_middleband_14_0': {'desc': 'BBANDS指标，timeperiod=14', 'type': 'float32'},
        'ta_bbands_middleband_28_0': {'desc': 'BBANDS指标，timeperiod=28', 'type': 'float32'},
        'ta_bbands_upperband_14_0': {'desc': 'BBANDS指标，timeperiod=14', 'type': 'float32'},
        'ta_bbands_upperband_28_0': {'desc': 'BBANDS指标，timeperiod=28', 'type': 'float32'},
        'ta_cci_14_0': {'desc': 'CCI指标，timeperiod=14', 'type': 'float32'},
        'ta_cci_28_0': {'desc': 'CCI指标，timeperiod=28', 'type': 'float32'},
        'ta_ema_5_0': {'desc': '收盘价的5日指数移动平均值', 'type': 'float32'},
        'ta_ema_10_0': {'desc': '收盘价的10日指数移动平均值', 'type': 'float32'},
        'ta_ema_20_0': {'desc': '收盘价的20日指数移动平均值', 'type': 'float32'},
        'ta_ema_30_0': {'desc': '收盘价的30日指数移动平均值', 'type': 'float32'},
        'ta_ema_60_0': {'desc': '收盘价的60日指数移动平均值', 'type': 'float32'},
        'ta_macd_macd_12_26_9_0': {'desc': 'MACD', 'type': 'float32'},
        'ta_macd_macdhist_12_26_9_0': {'desc': 'MACD', 'type': 'float32'},
        'ta_macd_macdsignal_12_26_9_0': {'desc': 'MACD', 'type': 'float32'},
        'ta_mfi_14_0': {'desc': 'MFI指标，timeperiod=14', 'type': 'float32'},
        'ta_mfi_28_0': {'desc': 'MFI指标，timeperiod=28', 'type': 'float32'},
        'ta_mom_10_0': {'desc': 'MOM指标，timeperiod=10', 'type': 'float32'},
        'ta_mom_20_0': {'desc': 'MOM指标，timeperiod=20', 'type': 'float32'},
        'ta_mom_30_0': {'desc': 'MOM指标，timeperiod=30', 'type': 'float32'},
        'ta_mom_60_0': {'desc': 'MOM指标，timeperiod=60', 'type': 'float32'},
        'ta_obv_0': {'desc': 'OBV指标', 'type': 'float64'},
        'ta_rsi_14_0': {'desc': 'RSI指标，timeperiod=14', 'type': 'float32'},
        'ta_rsi_28_0': {'desc': 'RSI指标，timeperiod=28', 'type': 'float32'},
        'ta_sar_0': {'desc': 'SAR指标', 'type': 'float32'},
        'ta_sma_5_0': {'desc': '收盘价的5日简单移动平均值', 'type': 'float32'},
        'ta_sma_10_0': {'desc': '收盘价的10日简单移动平均值', 'type': 'float32'},
        'ta_sma_20_0': {'desc': '收盘价的20日简单移动平均值', 'type': 'float32'},
        'ta_sma_30_0': {'desc': '收盘价的30日简单移动平均值', 'type': 'float32'},
        'ta_sma_60_0': {'desc': '收盘价的60日简单移动平均值', 'type': 'float32'},
        'ta_stoch_slowd_5_3_0_3_0_0': {'desc': 'STOCH (KDJ) 指标D值', 'type': 'float32'},
        'ta_stoch_slowk_5_3_0_3_0_0': {'desc': 'STOCH (KDJ) 指标K值', 'type': 'float32'},
        'ta_trix_14_0': {'desc': 'TRIX指标，timeperiod=14', 'type': 'float32'},
        'ta_trix_28_0': {'desc': 'TRIX指标，timeperiod=28', 'type': 'float32'},
        'ta_willr_14_0': {'desc': 'WILLR指标，timeperiod=14', 'type': 'float32'},
        'ta_willr_28_0': {'desc': 'WILLR指标，timeperiod=28', 'type': 'float32'},
        'ta_wma_5_0': {'desc': '收盘价的5日加权移动平均值', 'type': 'float32'},
        'ta_wma_10_0': {'desc': '收盘价的10日加权移动平均值', 'type': 'float32'},
        'ta_wma_20_0': {'desc': '收盘价的20日加权移动平均值', 'type': 'float32'},
        'ta_wma_30_0': {'desc': '收盘价的30日加权移动平均值', 'type': 'float32'},
        'ta_wma_60_0': {'desc': '收盘价的60日加权移动平均值', 'type': 'float32'},
        'beta_csi100_10_0': {'desc': 'BETA值(中证100)，timeperiod=10', 'type': 'float32'},
        'beta_csi100_120_0': {'desc': 'BETA值(中证100)，timeperiod=120', 'type': 'float32'},
        'beta_csi100_180_0': {'desc': 'BETA值(中证100)，timeperiod=180', 'type': 'float32'},
        'beta_csi100_30_0': {'desc': 'BETA值(中证100)，timeperiod=30', 'type': 'float32'},
        'beta_csi100_5_0': {'desc': 'BETA值(中证100)，timeperiod=5', 'type': 'float32'},
        'beta_csi100_60_0': {'desc': 'BETA值(中证100)，timeperiod=60', 'type': 'float32'},
        'beta_csi100_90_0': {'desc': 'BETA值(中证100)，timeperiod=90', 'type': 'float32'},
        'beta_csi300_10_0': {'desc': 'BETA值(中证300)，timeperiod=10', 'type': 'float32'},
        'beta_csi300_120_0': {'desc': 'BETA值(中证300)，timeperiod=120', 'type': 'float32'},
        'beta_csi300_180_0': {'desc': 'BETA值(中证300)，timeperiod=180', 'type': 'float32'},
        'beta_csi300_30_0': {'desc': 'BETA值(中证300)，timeperiod=30', 'type': 'float32'},
        'beta_csi300_5_0': {'desc': 'BETA值(中证300)，timeperiod=5', 'type': 'float32'},
        'beta_csi300_60_0': {'desc': 'BETA值(中证300)，timeperiod=60', 'type': 'float32'},
        'beta_csi300_90_0': {'desc': 'BETA值(中证300)，timeperiod=90', 'type': 'float32'},
        'beta_csi500_10_0': {'desc': 'BETA值(中证500)，timeperiod=10', 'type': 'float32'},
        'beta_csi500_120_0': {'desc': 'BETA值(中证500)，timeperiod=120', 'type': 'float32'},
        'beta_csi500_180_0': {'desc': 'BETA值(中证500)，timeperiod=180', 'type': 'float32'},
        'beta_csi500_30_0': {'desc': 'BETA值(中证500)，timeperiod=30', 'type': 'float32'},
        'beta_csi500_5_0': {'desc': 'BETA值(中证500)，timeperiod=5', 'type': 'float32'},
        'beta_csi500_60_0': {'desc': 'BETA值(中证500)，timeperiod=60', 'type': 'float32'},
        'beta_csi500_90_0': {'desc': 'BETA值(中证500)，timeperiod=90', 'type': 'float32'},
        'beta_csi800_10_0': {'desc': 'BETA值(中证800)，timeperiod=10', 'type': 'float32'},
        'beta_csi800_120_0': {'desc': 'BETA值(中证800)，timeperiod=120', 'type': 'float32'},
        'beta_csi800_180_0': {'desc': 'BETA值(中证800)，timeperiod=180', 'type': 'float32'},
        'beta_csi800_30_0': {'desc': 'BETA值(中证800)，timeperiod=30', 'type': 'float32'},
        'beta_csi800_5_0': {'desc': 'BETA值(中证800)，timeperiod=5', 'type': 'float32'},
        'beta_csi800_60_0': {'desc': 'BETA值(中证800)，timeperiod=60', 'type': 'float32'},
        'beta_csi800_90_0': {'desc': 'BETA值(中证800)，timeperiod=90', 'type': 'float32'},
        'beta_gem_10_0': {'desc': 'BETA值(创业板)，timeperiod=10', 'type': 'float32'},
        'beta_gem_120_0': {'desc': 'BETA值(创业板)，timeperiod=120', 'type': 'float32'},
        'beta_gem_180_0': {'desc': 'BETA值(创业板)，timeperiod=180', 'type': 'float32'},
        'beta_gem_30_0': {'desc': 'BETA值(创业板)，timeperiod=30', 'type': 'float32'},
        'beta_gem_5_0': {'desc': 'BETA值(创业板)，timeperiod=5', 'type': 'float32'},
        'beta_gem_60_0': {'desc': 'BETA值(创业板)，timeperiod=60', 'type': 'float32'},
        'beta_gem_90_0': {'desc': 'BETA值(创业板)，timeperiod=90', 'type': 'float32'},
        'beta_industry_10_0': {'desc': 'BETA值(所在行业)，timeperiod=10', 'type': 'float32'},
        'beta_industry_120_0': {'desc': 'BETA值(所在行业)，timeperiod=120', 'type': 'float32'},
        'beta_industry_180_0': {'desc': 'BETA值(所在行业)，timeperiod=180', 'type': 'float32'},
        'beta_industry_30_0': {'desc': 'BETA值(所在行业)，timeperiod=30', 'type': 'float32'},
        'beta_industry_5_0': {'desc': 'BETA值(所在行业)，timeperiod=5', 'type': 'float32'},
        'beta_industry_60_0': {'desc': 'BETA值(所在行业)，timeperiod=60', 'type': 'float32'},
        'beta_industry_90_0': {'desc': 'BETA值(所在行业)，timeperiod=90', 'type': 'float32'},
        'beta_sse180_10_0': {'desc': 'BETA值(上证180)，timeperiod=10', 'type': 'float32'},
        'beta_sse180_120_0': {'desc': 'BETA值(上证180)，timeperiod=120', 'type': 'float32'},
        'beta_sse180_180_0': {'desc': 'BETA值(上证180)，timeperiod=180', 'type': 'float32'},
        'beta_sse180_30_0': {'desc': 'BETA值(上证180)，timeperiod=30', 'type': 'float32'},
        'beta_sse180_5_0': {'desc': 'BETA值(上证180)，timeperiod=5', 'type': 'float32'},
        'beta_sse180_60_0': {'desc': 'BETA值(上证180)，timeperiod=60', 'type': 'float32'},
        'beta_sse180_90_0': {'desc': 'BETA值(上证180)，timeperiod=90', 'type': 'float32'},
        'beta_sse50_10_0': {'desc': 'BETA值(上证50)，timeperiod=10', 'type': 'float32'},
        'beta_sse50_120_0': {'desc': 'BETA值(上证50)，timeperiod=120', 'type': 'float32'},
        'beta_sse50_180_0': {'desc': 'BETA值(上证50)，timeperiod=180', 'type': 'float32'},
        'beta_sse50_30_0': {'desc': 'BETA值(上证50)，timeperiod=30', 'type': 'float32'},
        'beta_sse50_5_0': {'desc': 'BETA值(上证50)，timeperiod=5', 'type': 'float32'},
        'beta_sse50_60_0': {'desc': 'BETA值(上证50)，timeperiod=60', 'type': 'float32'},
        'beta_sse50_90_0': {'desc': 'BETA值(上证50)，timeperiod=90', 'type': 'float32'},
        'beta_szzs_120_0': {'desc': 'BETA值(上证综指)，timeperiod=120', 'type': 'float32'},
        'beta_szzs_180_0': {'desc': 'BETA值(上证综指)，timeperiod=180', 'type': 'float32'},
        'beta_szzs_30_0': {'desc': 'BETA值(上证综指)，timeperiod=30', 'type': 'float32'},
        'beta_szzs_5_0': {'desc': 'BETA值(上证综指)，timeperiod=5', 'type': 'float32'},
        'beta_szzs_60_0': {'desc': 'BETA值(上证综指)，timeperiod=60', 'type': 'float32'},
        'beta_szzs_90_0': {'desc': 'BETA值(上证综指)，timeperiod=90', 'type': 'float32'},
        'beta_szzs_10_0': {'desc': 'BETA值(上证综指)，timeperiod=10', 'type': 'float32'},
        'rank_beta_csi100_10_0': {'desc': 'BETA值(中证100)，timeperiod=10, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi100_180_0': {'desc': 'BETA值(中证100)，timeperiod=180, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi300_10_0': {'desc': 'BETA值(中证300)，timeperiod=10, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi300_180_0': {'desc': 'BETA值(中证300)，timeperiod=180, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi300_30_0': {'desc': 'BETA值(中证300)，timeperiod=30, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi300_5_0': {'desc': 'BETA值(中证300)，timeperiod=5, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi500_10_0': {'desc': 'BETA值(中证500)，timeperiod=10, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi500_120_0': {'desc': 'BETA值(中证500)，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi500_180_0': {'desc': 'BETA值(中证500)，timeperiod=180, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi500_30_0': {'desc': 'BETA值(中证500)，timeperiod=30, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi500_90_0': {'desc': 'BETA值(中证500)，timeperiod=90, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi800_10_0': {'desc': 'BETA值(中证800)，timeperiod=10, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi800_120_0': {'desc': 'BETA值(中证800)，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi800_180_0': {'desc': 'BETA值(中证800)，timeperiod=180, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi800_5_0': {'desc': 'BETA值(中证800)，timeperiod=5, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi800_60_0': {'desc': 'BETA值(中证800)，timeperiod=60, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi800_90_0': {'desc': 'BETA值(中证800)，timeperiod=90, 升序百分比排名', 'type': 'float32'},
        'rank_beta_gem_10_0': {'desc': 'BETA值(创业板)，timeperiod=10, 升序百分比排名', 'type': 'float32'},
        'rank_beta_gem_120_0': {'desc': 'BETA值(创业板)，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_beta_gem_180_0': {'desc': 'BETA值(创业板)，timeperiod=180, 升序百分比排名', 'type': 'float32'},
        'rank_beta_gem_30_0': {'desc': 'BETA值(创业板)，timeperiod=30, 升序百分比排名', 'type': 'float32'},
        'rank_beta_gem_90_0': {'desc': 'BETA值(创业板)，timeperiod=90, 升序百分比排名', 'type': 'float32'},
        'rank_beta_industry_120_0': {'desc': 'BETA值(所在行业)，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_beta_industry_180_0': {'desc': 'BETA值(所在行业)，timeperiod=180, 升序百分比排名', 'type': 'float32'},
        'rank_beta_industry_30_0': {'desc': 'BETA值(所在行业)，timeperiod=30, 升序百分比排名', 'type': 'float32'},
        'rank_beta_industry_5_0': {'desc': 'BETA值(所在行业)，timeperiod=5, 升序百分比排名', 'type': 'float32'},
        'rank_beta_industry_90_0': {'desc': 'BETA值(所在行业)，timeperiod=90, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse180_10_0': {'desc': 'BETA值(上证180)，timeperiod=10, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse180_5_0': {'desc': 'BETA值(上证180)，timeperiod=5, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse180_60_0': {'desc': 'BETA值(上证180)，timeperiod=60, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse50_120_0': {'desc': 'BETA值(上证50)，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse50_180_0': {'desc': 'BETA值(上证50)，timeperiod=180, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse50_30_0': {'desc': 'BETA值(上证50)，timeperiod=30, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse50_5_0': {'desc': 'BETA值(上证50)，timeperiod=5, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse50_60_0': {'desc': 'BETA值(上证50)，timeperiod=60, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse50_90_0': {'desc': 'BETA值(上证50)，timeperiod=90, 升序百分比排名', 'type': 'float32'},
        'rank_beta_szzs_120_0': {'desc': 'BETA值(上证综指)，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_beta_szzs_180_0': {'desc': 'BETA值(上证综指)，timeperiod=180, 升序百分比排名', 'type': 'float32'},
        'rank_beta_szzs_60_0': {'desc': 'BETA值(上证综指)，timeperiod=60, 升序百分比排名', 'type': 'float32'},

        'rank_beta_csi100_120_0': {'desc': 'BETA值(中证100)，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi100_30_0': {'desc': 'BETA值(中证100)，timeperiod=30, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi100_5_0': {'desc': 'BETA值(中证100)，timeperiod=5, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi100_60_0': {'desc': 'BETA值(中证100)，timeperiod=60, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi100_90_0': {'desc': 'BETA值(中证100)，timeperiod=90, 升序百分比排名', 'type': 'float32'},

        'rank_beta_csi300_120_0': {'desc': 'BETA值(沪深300)，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi300_60_0': {'desc': 'BETA值(沪深300)，timeperiod=60, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi300_90_0': {'desc': 'BETA值(沪深300)，timeperiod=90, 升序百分比排名', 'type': 'float32'},

        'rank_beta_csi500_5_0': {'desc': 'BETA值(中证500)，timeperiod=5, 升序百分比排名', 'type': 'float32'},
        'rank_beta_csi500_60_0': {'desc': 'BETA值(中证500)，timeperiod=60, 升序百分比排名', 'type': 'float32'},

        'rank_beta_csi800_30_0': {'desc': 'BETA值(中证800)，timeperiod=30, 升序百分比排名', 'type': 'float32'},

        'rank_beta_gem_5_0': {'desc': 'BETA值(创业板)，timeperiod=5, 升序百分比排名', 'type': 'float32'},
        'rank_beta_gem_60_0': {'desc': 'BETA值(创业板)，timeperiod=60, 升序百分比排名', 'type': 'float32'},

        'rank_beta_industry_10_0': {'desc': 'BETA值(所在行业)，timeperiod=10, 升序百分比排名', 'type': 'float32'},
        'rank_beta_industry_60_0': {'desc': 'BETA值(所在行业)，timeperiod=60, 升序百分比排名', 'type': 'float32'},

        'rank_beta_sse180_120_0': {'desc': 'BETA值(上证180)，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse180_180_0': {'desc': 'BETA值(上证180)，timeperiod=180, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse180_30_0': {'desc': 'BETA值(上证180)，timeperiod=30, 升序百分比排名', 'type': 'float32'},
        'rank_beta_sse180_90_0': {'desc': 'BETA值(上证180)，timeperiod=90, 升序百分比排名', 'type': 'float32'},

        'rank_beta_sse50_10_0': {'desc': 'BETA值(上证50)，timeperiod=10, 升序百分比排名', 'type': 'float32'},

        'rank_beta_szzs_10_0': {'desc': 'BETA值(上证综指)，timeperiod=10, 升序百分比排名', 'type': 'float32'},
        'rank_beta_szzs_30_0': {'desc': 'BETA值(上证综指)，timeperiod=30, 升序百分比排名', 'type': 'float32'},
        'rank_beta_szzs_5_0': {'desc': 'BETA值(上证综指)，timeperiod=5, 升序百分比排名', 'type': 'float32'},
        'rank_beta_szzs_90_0': {'desc': 'BETA值(上证综指)，timeperiod=90, 升序百分比排名', 'type': 'float32'},

        'swing_volatility_10_0': {'desc': '振幅波动率，timeperiod=10', 'type': 'float32'},
        'swing_volatility_120_0': {'desc': '振幅波动率，timeperiod=120', 'type': 'float32'},
        'swing_volatility_240_0': {'desc': '振幅波动率，timeperiod=240', 'type': 'float32'},
        'swing_volatility_30_0': {'desc': '振幅波动率，timeperiod=30', 'type': 'float32'},
        'swing_volatility_5_0': {'desc': '振幅波动率，timeperiod=5', 'type': 'float32'},
        'swing_volatility_60_0': {'desc': '振幅波动率，timeperiod=60', 'type': 'float32'},
        'volatility_10_0': {'desc': '波动率，timeperiod=10', 'type': 'float32'},
        'volatility_120_0': {'desc': '波动率，timeperiod=120', 'type': 'float32'},
        'volatility_240_0': {'desc': '波动率，timeperiod=240', 'type': 'float32'},
        'volatility_30_0': {'desc': '波动率，timeperiod=30', 'type': 'float32'},
        'volatility_5_0': {'desc': '波动率，timeperiod=5', 'type': 'float32'},
        'rank_swing_volatility_120_0': {'desc': '振幅波动率，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_swing_volatility_240_0': {'desc': '振幅波动率，timeperiod=240, 升序百分比排名', 'type': 'float32'},
        'rank_swing_volatility_30_0': {'desc': '振幅波动率，timeperiod=30，升序百分比排名', 'type': 'float32'},
        'rank_swing_volatility_5_0': {'desc': '振幅波动率，timeperiod=5，升序百分比排名', 'type': 'float32'},
        'rank_volatility_120_0': {'desc': '波动率，timeperiod=120, 升序百分比排名', 'type': 'float32'},
        'rank_volatility_30_0': {'desc': '波动率，timeperiod=30，升序百分比排名', 'type': 'float32'},
        'rank_volatility_5_0': {'desc': '波动率，timeperiod=5，升序百分比排名', 'type': 'float32'},
        'rank_volatility_60_0': {'desc': '波动率，timeperiod=60，升序百分比排名', 'type': 'float32'},
        'rank_volatility_10_0': {'desc': '波动率，timeperiod=10，升序百分比排名', 'type': 'float32'},
        'rank_volatility_240_0': {'desc': '波动率，timeperiod=240，升序百分比排名', 'type': 'float32'},

        'volatility_60_0': {'desc': '波动率，timeperiod=60', 'type': 'float32'},
        'rank_swing_volatility_10_0': {'desc': '振幅波动率，timeperiod=10，升序百分比排名', 'type': 'float32'},
        'rank_swing_volatility_60_0': {'desc': '振幅波动率，timeperiod=60，升序百分比排名', 'type': 'float32'},

        # 财务相关的，自己加的
        'roa2_0': {'desc': '总资产报酬率', 'type': 'float64'},
        'roa_0': {'desc': '总资产净利率', 'type': 'float64'},
        'op_gr_0': {'desc': '利润率', 'type': 'float64'},
        'pro_tog_0': {'desc': '营业总收入利润率', 'type': 'float64'},
        'gc_gr_0': {'desc': '营业总成本率', 'type': 'float64'},
        'ebit_gr_0': {'desc': '息税前利润同营业总收入比', 'type': 'float64'},
        'gro_pro_mar_0': {'desc': '销售毛利率', 'type': 'float64'},
        'net_pro_mar_0': {'desc': '销售净利率', 'type': 'float64'},
        'cog_sal_0': {'desc': '销售成本率', 'type': 'float64'},
        'yoy_eps_bas_0': {'desc': '同比增长率-基本每股收益(%)', 'type': 'float64'},
        'yoy_eps_dil_0': {'desc': '同比增长率-稀释每股收益(%)', 'type': 'float64'},
        'yoy_ocf_0': {'desc': '同比增长率-每股经营活动产生的现金流量净额(%)', 'type': 'float64'},
        'yoy_op_0': {'desc': '同比增长率-营业利润(%)', 'type': 'float64'},
        'yoy_ebt_tot_0': {'desc': '同比增长率-利润总额(%)', 'type': 'float64'},
        'yoy_net_pro_0': {'desc': '同比增长率-归属母公司股东的净利润(%)', 'type': 'float64'},
        'yoy_tr_0': {'desc': '同比增长率-营业总收入(%)', 'type': 'float64'},
        'yoy_or_0': {'desc': '同比增长率-营业收入(%)', 'type': 'float64'},
        'yoy_bps_0': {'desc': '相对年初增长率-每股净资产(%)', 'type': 'float64'},
        'yoy_ass_0': {'desc': '相对年初增长率-资产总计(%)', 'type': 'float64'},
        'yoy_equ_sha_0': {'desc': '相对年初增长率-归属母公司的股东权益(%)', 'type': 'float64'},
        'acc_lia_pro_0': {'desc': '资产负债率(%)', 'type': 'float64'},
        'ass_equ_0': {'desc': '权益乘数', 'type': 'float64'},
        'lia_tot_equ_0': {'desc': '产权比率', 'type': 'float64'},
        'ebit_int_0': {'desc': '已获利息倍数(EBIT/利息费用)', 'type': 'float64'},
        'cur_rat_0': {'desc': '流动比(%)', 'type': 'float64'},
        'qui_rat_0': {'desc': '速动比(%)', 'type': 'float64'},
        'cas_rat_0': {'desc': '保守速动比率', 'type': 'float64'},
        'cat_ass_0': {'desc': '流动资产占总资产比率', 'type': 'float64'},
        'ocf_lia_cur_0': {'desc': '经营活动产生的现金流量净额占流动负债比率', 'type': 'float64'},
        'equ_deb_0': {'desc': '归属于母公司的股东权益占总负债比率', 'type': 'float64'},
        'ocf_deb_0': {'desc': '经营活动产生的现金流量净额同总负债比', 'type': 'float64'},
        'inv_rn_0': {'desc': '存货周转率', 'type': 'float64'},
        'art_rn_0': {'desc': '应收账款周转率', 'type': 'float64'},
        'art_day_0': {'desc': '应收账款周转天数', 'type': 'float64'},
        'fat_rn_0': {'desc': '固定资产周转率', 'type': 'float64'},
        'cat_rn_0': {'desc': '流动资产周转率', 'type': 'float64'},
        'ass_rn_0': {'desc': '总资产周转率', 'type': 'float64'},
        'fcff_0': {'desc': '企业自由现金流量(FCFF)', 'type': 'float64'},
        'wor_cap_0': {'desc': '营运资金', 'type': 'float64'},
        'net_wor_cap_0': {'desc': '营运流动资本', 'type': 'float64'},
        'eps_bas_0': {'desc': '基本每股收益', 'type': 'float64'},
        'eps_dlt_0': {'desc': '稀释每股收益', 'type': 'float64'},
        'bps_0': {'desc': '每股净资产', 'type': 'float64'},
        'ocfps_0': {'desc': '每股经营活动产生的现金流量净额', 'type': 'float64'},
        'gr_ps_0': {'desc': '每股营业总收入', 'type': 'float64'},
        'orps_0': {'desc': '每股营业收入', 'type': 'float64'},
        'sur_cap_0': {'desc': '每股资本公积', 'type': 'float64'},
        'sur_res_0': {'desc': '每股盈余公积', 'type': 'float64'},
        'und_ps_0': {'desc': '每股未分配利润', 'type': 'float64'},
        'ret_ps_0': {'desc': '每股留存收益', 'type': 'float64'},
        'cfps_0': {'desc': '每股现金流量净额', 'type': 'float64'},
        'ebit_ps_0': {'desc': '每股息税前利润', 'type': 'float64'},
        'fcff_ps_0': {'desc': '每股企业自由现金流量', 'type': 'float64'},
        'fcfe_ps_0': {'desc': '每股股东自由现金流量', 'type': 'float64'},

    }

}

print(len(schema['fields'].keys()))